In [1]:
from timescale import TimescaleDBManager
from dotenv import load_dotenv
from sqlalchemy import create_engine
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
import joblib
import json
import re

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay, accuracy_score, 
    precision_score, recall_score, f1_score, classification_report,
    roc_auc_score, roc_curve, RocCurveDisplay
)
from sklearn.inspection import permutation_importance
from sklearn.preprocessing import LabelEncoder, StandardScaler

from tensorflow.keras import layers, models
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import Callback, EarlyStopping, ReduceLROnPlateau

from scikeras.wrappers import KerasRegressor
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier


import optuna
from optuna.samplers import TPESampler
import tensorflow as tf
import seaborn as sns
from functools import partial
from tqdm import tqdm
import gc
import sys
import warnings

In [2]:
load_dotenv()
user_env        = os.getenv("USER_DB")
pass_env        = os.getenv("PASS_DB")
host_env        = os.getenv("HOST_DB", "localhost")
port_env        = os.getenv("DB_PORT_EXPOSED", "5432")
db_env          = os.getenv("NAME_DB", "tfm_db")
FOLDER_SALIDA   = os.getenv("FOLDER_SALIDA")
FOLDER_TMP      = os.getenv("FOLDER_TMP")

SEED            = 100#int(os.getenv("SEED"))

db = TimescaleDBManager(
    user=user_env,
    password=pass_env,
    host=host_env,
    port=port_env,
    dbname=db_env
)
db.conectar()
conexion_postgresql = db.connection

#esto es para usar una conexion postgrews para pandas que da un warning indicando que solo esta testeado para sqlalchemy
engine = create_engine(f'postgresql+psycopg2://{user_env}:{pass_env}@{host_env}:{port_env}/{db_env}')

[OK] Conexión establecida con TimescaleDB.

In [3]:
tabla_origen = 'vectores_logs'
tabla_split  = 'vectores_logs_split'
filename_lista_metric_name_vector = f'{FOLDER_SALIDA}/lista_metricas_filtradas_ord(metricas_logs).json'

In [4]:
SQL=f'select * from {tabla_origen}'
df = pd.read_sql(SQL, engine)

In [5]:
lista_label = df['label'].unique().tolist()

In [6]:
len(lista_label)

54

In [7]:
df_result=df[ ['vector_id','execution_name','label'] ].copy()

In [8]:
df_result

,vector_id,execution_name,label
0,115150,light-oauth2-data-1719592986.tar,correct
1,115151,light-oauth2-data-1719592986.tar,correct
2,115152,light-oauth2-data-1719592986.tar,correct
3,115153,light-oauth2-data-1719592986.tar,correct
4,115154,light-oauth2-data-1719592986.tar,correct
...,...,...,...
44121,159271,light-oauth2-data-1722744859.tar,get_user_404_no_user
44122,159272,light-oauth2-data-1722744859.tar,delete_user_404_no_user
44123,159273,light-oauth2-data-1722744859.tar,update_password_401_wrong_password
44124,159274,light-oauth2-data-1722744859.tar,update_password_404_user_not_found
44125,159275,light-oauth2-data-1722744859.tar,update_password_400_not_match

In [9]:
with open(filename_lista_metric_name_vector, "r", encoding="utf-8") as f:
    lista_metric_name_vector = json.load(f)

In [10]:
len(lista_metric_name_vector)

331

In [11]:
def reporte_uso_memoria():

    # Lista para almacenar la info y poder ordenarla
    variables_info = []
    
    for nombre, obj in list(globals().items()):
        # Evitamos variables del sistema que empiezan por '_'
        if not nombre.startswith('_'):
            peso_mb = sys.getsizeof(obj) / (1024 * 1024)
            
            # Cálculo más preciso para DataFrames de pandas o matrices de numpy
            if hasattr(obj, 'memory_usage'):
                try:
                    peso_mb = obj.memory_usage(deep=True).sum() / (1024 * 1024)
                except:
                    pass
            elif hasattr(obj, 'nbytes'):
                peso_mb = obj.nbytes / (1024 * 1024)
                
            variables_info.append({
                'nombre': nombre,
                'tipo': type(obj).__name__,
                'peso': peso_mb
            })
    
    # Ordenar de mayor a menor peso (descendente)
    variables_info = sorted(variables_info, key=lambda x: x['peso'], reverse=True)
    
    # Imprimir la tabla formateada
    print(f"{'Variable':<30} | {'Tipo':<20} | {'Tamaño (MB)':<12}")
    print("-" * 68)
    for var in variables_info:
        print(f"{var['nombre']:<30} | {var['tipo']:<20} | {var['peso']:>10.2f} MB")

In [12]:


def X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=None,lista_feature_sel=None):
    #X_matrix es la matriz completa
    #lista_feature_names son los nombres de las columnas
    #lista_idx_filas es la lista de indices de las filas que tomaremos
    #lista_feature_sel es la lista de nombres de las columnas que tomaremos, es un subconjunto de lista_feature_names
    if lista_idx_filas is None:
        lista_idx_filas   = range(0,X_matrix.shape[0])
    if lista_feature_sel is None:
        lista_feature_sel = lista_feature_names.copy()

    lista_feature_idx = []
    idx=0
    for feature in lista_feature_names:
        if feature in lista_feature_sel:
            lista_feature_idx.append(idx)
        idx += 1        

    # 1. Filtramos primero las filas
    X_temp = X_matrix[list(lista_idx_filas), :]
    
    # 2. Filtramos después las columnas sobre el resultado anterior
    X_matrix_sub = X_temp[:, lista_feature_idx]
    
    return X_matrix_sub

In [13]:
def evaluar_modelo(paquete_modelo,lista_feature_names,X_test,Y_test_etiquetas,encoder_etiquetas):
    #lista_feature_names  es el nombre de las columnas de X_test
    lista_feature_names_modelo = paquete_modelo['lista_features']
    model = paquete_modelo['model']
    lista_feature_idx = []
    idx=0
    for feature in lista_feature_names:
        if feature in lista_feature_names_modelo:
            lista_feature_idx.append(idx )
        idx += 1
        
    X_test_sub                                  = X_test[:, lista_feature_idx]
    Y_pred                                      = model.predict(X_test_sub)
    Y_pred_tipos                                = encoder_etiquetas.inverse_transform(Y_pred)
    Y_pred_probabilidades                       = model.predict_proba(X_test_sub)
    reporte_dict                                = classification_report(Y_test_etiquetas, Y_pred_tipos, output_dict=True, zero_division=0)
    classification_report_str                   = classification_report(Y_test_etiquetas, Y_pred_tipos)    
    accuracy                                    = reporte_dict['accuracy']
    macro_f1                                    = reporte_dict['macro avg']['f1-score']
    macro_precision                             = reporte_dict['macro avg']['precision']
    macro_recall                                = reporte_dict['macro avg']['recall']

    resultado                                   = {'accuracy': accuracy,  'precision':macro_precision   , 'recall':macro_recall  , 'f1':macro_f1 }

    paquete_modelo['resultado']                 = resultado
    paquete_modelo['probabilidades']            = Y_pred_probabilidades
    paquete_modelo['reporte_dict']              = reporte_dict
    paquete_modelo['classification_report_str'] = classification_report_str
    
    return resultado,reporte_dict,Y_pred_probabilidades

def predict_modelo(paquete_modelo,lista_feature_names,X_test):
    lista_feature_names_modelo = paquete_modelo['lista_features']
    model = paquete_modelo['model']
    lista_feature_idx = []
    idx=0
    for feature in lista_feature_names:
        if feature in lista_feature_names_modelo:
            lista_feature_idx.append(idx )
        idx += 1

    X_test_sub                                  = X_test[:, lista_feature_idx]        
    Y_pred                                      = model.predict(X_test_sub)   
    return Y_pred

    

def get_lista_feature_sin_lag(lista_features):
    lista_features_result=[]
    for feature in lista_features:
        feature_limpia = re.sub(r'\(lag_\d+\)$', '', feature)
        if feature_limpia not in  lista_features_result:
            lista_features_result.append(feature_limpia)
    return lista_features_result

In [14]:
#para optimizacion con OPTUNA
def print_callback(study, trial):
    # Si el trial falló por cualquier motivo, lo saltamos visualmente
    if trial.state != optuna.trial.TrialState.COMPLETE:
        pbar.update(1)
        return

    current_acc = trial.user_attrs.get('accuracy', trial.value)
    current_params = trial.params
    
    # Línea 1: Información de la iteración actual
    print(f"Trial {trial.number:2d}                | Actual Acc: {current_acc:.4f} | Parámetros: {current_params}")
    
    # Línea 2: Mejor resultado histórico hasta ahora
    print(f"   -> MEJOR HASTA AHORA | Mejor Acc:  {study.best_value:.4f} | Parámetros: {study.best_params}")
    print("-" * 100)
    
    # Actualización de la barra de progreso
    pbar.update(1)
    pbar.set_postfix({
        "Mejor_Acc": f"{study.best_value:.4f}",
        "Trial": trial.number
    })

In [15]:
def objective_universal(trial, config, clasificador_cls, X_train, X_test, Y_train_encoded, Y_test_encoded):
    params = {}
    
    for key, values in config.items():
        params[key] = trial.suggest_categorical(key, values)

    params['random_state'] = SEED
    if 'n_jobs' in clasificador_cls().get_params():
        params['n_jobs'] = -1

    model = clasificador_cls(**params)
    model.fit(X_train, Y_train_encoded)
    
    preds = model.predict(X_test)
    accuracy = accuracy_score(Y_test_encoded, preds)
    
    trial.set_user_attr('accuracy', accuracy)
    return accuracy

In [16]:
def obtener_importancias_agrupadas(importancias, lista_features):
    """
    Procesa las importancias de un modelo, elimina los sufijos de lag/sum,
    las agrupa por característica base y calcula cuántas características tienen importancia cero.
    """
    # 1. Crear el DataFrame inicial con las características y sus importancias
    df_importancias = pd.DataFrame({
        'caracteristica_con_lag': lista_features,
        'importancia': importancias
    }).sort_values(by='importancia', ascending=False).reset_index(drop=True)
    
    # 2. Limpiar los sufijos de lags y sumas para obtener la característica base
    df_importancias['caracteristica'] = (
        df_importancias['caracteristica_con_lag']
        .str.replace(r'\(lag_\d+\)', '', regex=True)
        .str.replace(r'\(sum\)', '', regex=False)
    )
    
    # 3. Agrupar por característica base sumando sus importancias
    df_importancias_agrupada = (
        df_importancias.groupby('caracteristica', as_index=False)['importancia']
        .sum()
        .sort_values(by='importancia', ascending=False)
        .reset_index(drop=True)
    )
    
    # 4. Contar cuántas características agrupadas tienen una importancia igual a 0
    caracteristicas_cero = df_importancias_agrupada[df_importancias_agrupada['importancia'] == 0]
    
    return df_importancias_agrupada, importancias, len(caracteristicas_cero)

# <span style="color:#2ca02c">1. Recuperamos separación ya hecha en conjuntos de train, val y test</span>

In [17]:
SQL=f'select * from {tabla_split}'
df_split = pd.read_sql(SQL, engine)

In [18]:
df_split

       vector_id split_type
0         115150       test
1         115151      train
2         115152      train
3         115153      train
4         115154      train
...          ...        ...
44121     159271      train
44122     159272      train
44123     159273      train
44124     159274      train
44125     159275      train

[44126 rows x 2 columns]

In [19]:
df_result = pd.merge(df_result, df_split, on="vector_id", how="inner")

In [20]:
df_result

,vector_id,execution_name,label,split_type
0,115150,light-oauth2-data-1719592986.tar,correct,test
1,115151,light-oauth2-data-1719592986.tar,correct,train
2,115152,light-oauth2-data-1719592986.tar,correct,train
3,115153,light-oauth2-data-1719592986.tar,correct,train
4,115154,light-oauth2-data-1719592986.tar,correct,train
...,...,...,...,...
44121,159271,light-oauth2-data-1722744859.tar,get_user_404_no_user,train
44122,159272,light-oauth2-data-1722744859.tar,delete_user_404_no_user,train
44123,159273,light-oauth2-data-1722744859.tar,update_password_401_wrong_password,train
44124,159274,light-oauth2-data-1722744859.tar,update_password_404_user_not_found,train
44125,159275,light-oauth2-data-1722744859.tar,update_password_400_not_match,train

In [21]:
dic_idx_train = {}
#dic_idx_resto = {}
dic_idx_val   = {}
dic_idx_test  = {}

In [22]:
for label in lista_label:
    idx_train = df_result[  (df_result['label']==label) & (df_result['split_type'] == 'train') ].index.values
    idx_val   = df_result[  (df_result['label']==label) & (df_result['split_type'] == 'val'  ) ].index.values
    idx_test  = df_result[  (df_result['label']==label) & (df_result['split_type'] == 'test') ].index.values
    dic_idx_train[label] = idx_train
    dic_idx_val[label]   = idx_val
    dic_idx_test[label]  = idx_test

<span style="color:#2ca02c"> Convetimos los vectores del df en una matriz, seran los datos que pasemos a los algoritmo   </span>

In [23]:
lista_matrix        = []
lista_feature_names = []

X_matrix1 = np.array(df['vector'].tolist())
X_matrix1.shape

(44126, 993)

In [24]:
N_puntos=3
lista_features = []
lista_features_orig = lista_metric_name_vector.copy()
for lag in range(0,N_puntos):
    for feature in lista_features_orig:
        lista_features.append(f'{feature}(lag_{lag})')
lista_feature_names1 = lista_features.copy()
lista_feature_names.extend(lista_feature_names1)
lista_matrix.append(X_matrix1)

In [25]:
lista_features_names_3puntos = lista_features.copy()

In [26]:
num_columnas_total = X_matrix1.shape[1]
tercio_n = num_columnas_total // N_puntos

# Definimos los límites de los 3 tercios
inicio_1, fin_1 = 0, tercio_n
inicio_2, fin_2 = tercio_n, tercio_n * 2
inicio_3, fin_3 = tercio_n * 2, num_columnas_total  # Coge el resto hasta el final por si acaso

# 2. Extraemos cada tercio como una submatriz
t1 = X_matrix1[:, inicio_1:fin_1]
t2 = X_matrix1[:, inicio_2:fin_2]
t3 = X_matrix1[:, inicio_3:fin_3]

# 3. Sumamos las columnas homólogas de los tres tercios (columna i del tercio 1 + columna i del tercio 2 + columna i del tercio 3)
# Como t1, t2 y t3 tienen exactamente la misma forma (n_filas, tercio_n), la suma de NumPy los alinea automáticamente.
X_matrix1_sum = t1 + t2 + t3
del t1,t2,t3
gc.collect()

0

In [27]:
lista_feature_names1_sum = []
for feature in lista_feature_names1:
    feature_sum = re.sub(r'\(lag_\d+\)', '(sum)', feature)
    if feature_sum not in lista_feature_names1_sum:
        lista_feature_names1_sum.append(feature_sum)

In [28]:
lista_matrix.append(X_matrix1_sum)
lista_feature_names.extend(lista_feature_names1_sum)

In [29]:
X_matrix = np.concatenate(lista_matrix, axis=1)

In [30]:
len(lista_feature_names)

1324

In [31]:
print(f'len(lista_feature_names1_sum)  = {len(lista_feature_names1_sum)}')
print(f'len(lista_feature_names1)      = {len(lista_feature_names1)}')
print(f'len(lista_feature_names)       = {len(lista_feature_names)}')

len(lista_feature_names1_sum)  = 331
len(lista_feature_names1)      = 993
len(lista_feature_names)       = 1324

In [32]:
lista_feature_names_1punto_sum=lista_feature_names1_sum.copy()

In [33]:
len(lista_feature_names_1punto_sum)

331

# <span style="color:#2ca02c">2. Preparacion de datos para entrenamiento/test</span>

In [34]:
#1. Establecemos la semilla para tener reproducibilidad
rng = np.random.default_rng(SEED)

# 2. Primero calculamos los mínimos por clase asegurando barajado aleatorio previo si se desea
min_train = float('inf')
min_test  = float('inf')
min_val   = float('inf')

for label in lista_label:
    if label == 'correct':
        continue
    
    min_train = min(min_train, len(dic_idx_train[label]))
    min_test  = min(min_test,  len(dic_idx_test[label]))
    min_val   = min(min_val,   len(dic_idx_val[label]))

# 3. Inicializamos los arrays de índices vacíos
idx_train = np.array([], dtype=int)
idx_test  = np.array([], dtype=int)
idx_val   = np.array([], dtype=int)

# 4. Bucle de selección aleatoria balanceada usando la SEED
for label in lista_label:
    if label == 'correct':
        continue
    
    # Barajamos los índices de forma aleatoria con la semilla antes de recortar
    arr_train = rng.permutation(dic_idx_train[label])
    arr_test  = rng.permutation(dic_idx_test[label])
    arr_val   = rng.permutation(dic_idx_val[label])
    
    # Concatenamos la cantidad mínima común de forma aleatoria, todas las clases tienen la misma cantidad de datos para que esten balanceadas
    idx_train = np.concatenate((idx_train, arr_train[:min_train]))
    idx_test  = np.concatenate((idx_test,  arr_test[:min_test]))
    idx_val   = np.concatenate((idx_val,   arr_val[:min_val]))

In [35]:
X_train = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_train,lista_feature_sel=lista_feature_names1)
print(X_train.shape)
X_test  = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_feature_names1)
print(X_test.shape)
X_val   = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_feature_names1)
print(X_val.shape)

(10282, 993)
(3445, 993)
(3445, 993)

In [36]:
X_train_sum = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_train,lista_feature_sel=lista_feature_names1_sum)
print(X_train_sum.shape)
X_test_sum  = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_feature_names1_sum)
print(X_test_sum.shape)
X_val_sum   = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_feature_names1_sum)
print(X_val_sum.shape)

(10282, 331)
(3445, 331)
(3445, 331)

In [37]:
X_matrix.shape

(44126, 1324)

In [38]:
df_result

,vector_id,execution_name,label,split_type
0,115150,light-oauth2-data-1719592986.tar,correct,test
1,115151,light-oauth2-data-1719592986.tar,correct,train
2,115152,light-oauth2-data-1719592986.tar,correct,train
3,115153,light-oauth2-data-1719592986.tar,correct,train
4,115154,light-oauth2-data-1719592986.tar,correct,train
...,...,...,...,...
44121,159271,light-oauth2-data-1722744859.tar,get_user_404_no_user,train
44122,159272,light-oauth2-data-1722744859.tar,delete_user_404_no_user,train
44123,159273,light-oauth2-data-1722744859.tar,update_password_401_wrong_password,train
44124,159274,light-oauth2-data-1722744859.tar,update_password_404_user_not_found,train
44125,159275,light-oauth2-data-1722744859.tar,update_password_400_not_match,train

In [39]:
#esta parte hay que hacerla si no hemos crado antes el label encoder, si lo hemos creado , recuperamos el label encoder de fichero
# encoder_etiquetas = LabelEncoder()

ruta_encoder = f'{FOLDER_SALIDA}/models/encoder_etiquetas.joblib'
encoder_etiquetas = joblib.load(ruta_encoder)


for indice, etiqueta in enumerate(encoder_etiquetas.classes_):
    print(f"Índice {indice} --> {etiqueta}")

Índice 0 --> access_token_auth_header_error_401
Índice 1 --> access_token_authorization_form_401
Índice 2 --> access_token_client_id_not_found_404
Índice 3 --> access_token_client_secret_wrong_401
Índice 4 --> access_token_form_urlencoded_400
Índice 5 --> access_token_illegal_grant_type_400
Índice 6 --> access_token_missing_authorization_header_400
Índice 7 --> authorization_code_client_id_missing_400
Índice 8 --> authorization_code_invalid_client_id_404
Índice 9 --> authorization_code_invalid_password_401
Índice 10 --> authorization_code_missing_response_type_400
Índice 11 --> authorization_code_response_not_code_400
Índice 12 --> code_challenge_invalid_format_pkce_400
Índice 13 --> code_challenge_too_long_pkce_400
Índice 14 --> code_challenge_too_short_pkce_400
Índice 15 --> code_verifier_missing_pkce_400
Índice 16 --> code_verifier_too_long_pkce_400
Índice 17 --> code_verifier_too_short_pkce_400
Índice 18 --> delete_client_404_no_client
Índice 19 --> delete_service_404_no_service
Índice 20 --> delete_token_404
Índice 21 --> delete_user_404_no_user
Índice 22 --> get_client_404_no_client
Índice 23 --> get_client_page_400_no_page
Índice 24 --> get_service_404_no_service
Índice 25 --> get_service_page_400_no_page
Índice 26 --> get_token_404
Índice 27 --> get_token_page_400_no_page
Índice 28 --> get_user_404_no_user
Índice 29 --> get_user_page_400_no_page
Índice 30 --> invalid_code_challenge_method_pkce_400
Índice 31 --> invalid_code_verifier_format_PKCE_400
Índice 32 --> register_client_400_clientProfile
Índice 33 --> register_client_400_clientType
Índice 34 --> register_client_404_no_user
Índice 35 --> register_service_400_service_id
Índice 36 --> register_service_400_service_type
Índice 37 --> register_service_404_no_user
Índice 38 --> register_user_400_email_exists
Índice 39 --> register_user_400_no_password
Índice 40 --> register_user_400_password_no_match
Índice 41 --> register_user_400_user_exists
Índice 42 --> update_client_400_clientProfile
Índice 43 --> update_client_400_clientType
Índice 44 --> update_client_404_clientId
Índice 45 --> update_client_404_ownerId
Índice 46 --> update_password_400_not_match
Índice 47 --> update_password_401_wrong_password
Índice 48 --> update_password_404_user_not_found
Índice 49 --> update_service_404_service_id
Índice 50 --> update_service_404_user_id
Índice 51 --> update_user_404_no_user
Índice 52 --> verification_failed_pkce_400

In [40]:
Y_train_etiquetas = df.loc[idx_train , 'label']
Y_test_etiquetas  = df.loc[idx_test  , 'label']
Y_val_etiquetas   = df.loc[idx_val  , 'label']

Y_train_encoded = encoder_etiquetas.transform(Y_train_etiquetas)
Y_test_encoded  = encoder_etiquetas.transform(Y_test_etiquetas)
Y_val_encoded   = encoder_etiquetas.transform(Y_val_etiquetas)

In [41]:
Y_train_encoded

array([32, 32, 32, ...,  8,  8,  8], shape=(10282,))

In [42]:
reporte_uso_memoria()

Variable                       | Tipo                 | Tamaño (MB)
--------------------------------------------------------------------
X_matrix                       | ndarray              |     445.73 MB
df                             | DataFrame            |     380.93 MB
X_matrix1                      | ndarray              |     334.30 MB
X_matrix1_sum                  | ndarray              |     111.43 MB
X_train                        | ndarray              |      77.90 MB
X_test                         | ndarray              |      26.10 MB
X_val                          | ndarray              |      26.10 MB
X_train_sum                    | ndarray              |      25.97 MB
df_result                      | DataFrame            |      10.16 MB
X_test_sum                     | ndarray              |       8.70 MB
X_val_sum                      | ndarray              |       8.70 MB
df_split                       | DataFrame            |       2.92 MB
Y_train_etiquetas              | Series               |       0.94 MB
Y_test_etiquetas               | Series               |       0.31 MB
Y_val_etiquetas                | Series               |       0.31 MB
idx_train                      | ndarray              |       0.08 MB
Y_train_encoded                | ndarray              |       0.08 MB
idx_val                        | ndarray              |       0.03 MB
idx_test                       | ndarray              |       0.03 MB
Y_test_encoded                 | ndarray              |       0.03 MB
Y_val_encoded                  | ndarray              |       0.03 MB
lista_feature_names            | list                 |       0.01 MB
lista_features                 | list                 |       0.01 MB
lista_feature_names1           | list                 |       0.01 MB
lista_features_names_3puntos   | list                 |       0.01 MB
arr_train                      | ndarray              |       0.00 MB
lista_metric_name_vector       | list                 |       0.00 MB
lista_feature_names1_sum       | list                 |       0.00 MB
lista_features_orig            | list                 |       0.00 MB
lista_feature_names_1punto_sum | list                 |       0.00 MB
TimescaleDBManager             | type                 |       0.00 MB
GridSearchCV                   | ABCMeta              |       0.00 MB
IsolationForest                | ABCMeta              |       0.00 MB
RandomForestClassifier         | ABCMeta              |       0.00 MB
ConfusionMatrixDisplay         | type                 |       0.00 MB
RocCurveDisplay                | type                 |       0.00 MB
LabelEncoder                   | type                 |       0.00 MB
StandardScaler                 | type                 |       0.00 MB
Model                          | type                 |       0.00 MB
Sequential                     | type                 |       0.00 MB
Dense                          | type                 |       0.00 MB
BatchNormalization             | type                 |       0.00 MB
Dropout                        | type                 |       0.00 MB
Adam                           | type                 |       0.00 MB
Callback                       | type                 |       0.00 MB
EarlyStopping                  | type                 |       0.00 MB
ReduceLROnPlateau              | type                 |       0.00 MB
KerasRegressor                 | type                 |       0.00 MB
XGBClassifier                  | type                 |       0.00 MB
LGBMClassifier                 | type                 |       0.00 MB
TPESampler                     | ABCMeta              |       0.00 MB
tqdm                           | type                 |       0.00 MB
dic_idx_train                  | dict                 |       0.00 MB
dic_idx_val                    | dict                 |       0.00 MB
dic_idx_test                   | dict                 |       0.00 MB
arr_test                       | ndarray              |       0.00 MB
arr_val                        | ndarray              |       0.00 MB
partial                        | type                 |       0.00 MB
Out                            | dict                 |       0.00 MB
lista_label                    | list                 |       0.00 MB
In                             | list                 |       0.00 MB
conexion_postgresql            | connection           |       0.00 MB
rng                            | Generator            |       0.00 MB
filename_lista_metric_name_vector | str                  |       0.00 MB
f                              | TextIOWrapper        |       0.00 MB
ruta_encoder                   | str                  |       0.00 MB
open                           | function             |       0.00 MB
load_dotenv                    | function             |       0.00 MB
create_engine                  | function             |       0.00 MB
train_test_split               | function             |       0.00 MB
confusion_matrix               | function             |       0.00 MB
accuracy_score                 | function             |       0.00 MB
precision_score                | function             |       0.00 MB
recall_score                   | function             |       0.00 MB
f1_score                       | function             |       0.00 MB
classification_report          | function             |       0.00 MB
roc_auc_score                  | function             |       0.00 MB
roc_curve                      | function             |       0.00 MB
permutation_importance         | function             |       0.00 MB
load_model                     | function             |       0.00 MB
Input                          | function             |       0.00 MB
reporte_uso_memoria            | function             |       0.00 MB
X_matrix_sel_data              | function             |       0.00 MB
evaluar_modelo                 | function             |       0.00 MB
predict_modelo                 | function             |       0.00 MB
get_lista_feature_sin_lag      | function             |       0.00 MB
print_callback                 | function             |       0.00 MB
objective_universal            | function             |       0.00 MB
obtener_importancias_agrupadas | function             |       0.00 MB
label                          | str                  |       0.00 MB
lista_matrix                   | list                 |       0.00 MB
feature                        | str                  |       0.00 MB
feature_sum                    | str                  |       0.00 MB
SQL                            | str                  |       0.00 MB
etiqueta                       | str                  |       0.00 MB
pd                             | module               |       0.00 MB
os                             | module               |       0.00 MB
plt                            | module               |       0.00 MB
np                             | module               |       0.00 MB
joblib                         | module               |       0.00 MB
json                           | module               |       0.00 MB
re                             | module               |       0.00 MB
layers                         | module               |       0.00 MB
models                         | module               |       0.00 MB
optuna                         | module               |       0.00 MB
tf                             | module               |       0.00 MB
sns                            | module               |       0.00 MB
gc                             | module               |       0.00 MB
sys                            | module               |       0.00 MB
warnings                       | module               |       0.00 MB
tabla_split                    | str                  |       0.00 MB
get_ipython                    | method               |       0.00 MB
tabla_origen                   | str                  |       0.00 MB
pass_env                       | str                  |       0.00 MB
user_env                       | str                  |       0.00 MB
host_env                       | str                  |       0.00 MB
exit                           | ZMQExitAutocall      |       0.00 MB
quit                           | ZMQExitAutocall      |       0.00 MB
db                             | TimescaleDBManager   |       0.00 MB
engine                         | Engine               |       0.00 MB
encoder_etiquetas              | LabelEncoder         |       0.00 MB
db_env                         | str                  |       0.00 MB
FOLDER_SALIDA                  | str                  |       0.00 MB
FOLDER_TMP                     | str                  |       0.00 MB
port_env                       | str                  |       0.00 MB
SEED                           | int                  |       0.00 MB
N_puntos                       | int                  |       0.00 MB
lag                            | int                  |       0.00 MB
num_columnas_total             | int                  |       0.00 MB
tercio_n                       | int                  |       0.00 MB
fin_1                          | int                  |       0.00 MB
inicio_2                       | int                  |       0.00 MB
fin_2                          | int                  |       0.00 MB
inicio_3                       | int                  |       0.00 MB
fin_3                          | int                  |       0.00 MB
min_train                      | int                  |       0.00 MB
min_test                       | int                  |       0.00 MB
min_val                        | int                  |       0.00 MB
indice                         | int                  |       0.00 MB
inicio_1                       | int                  |       0.00 MB

# <span style="color:#2ca02c">3. N/A</span>

# <span style="color:#2ca02c">4. Clasificacion de anomalias</span>

## <span style="color:#2ca02c">4.1 Clasificador Random Forest con metricas_logs</span>

In [44]:
ALGORITMO_CLASIFICADOR = RandomForestClassifier
nombre_algoritmo       = 'RandomForest'

### <span style="color:#2ca02c">4.1.1 Clasificador Random Forest (3 puntos) con metricas_logs</span>

In [444]:
N_puntos = 3
DATOS    = 'metricas_logs 3 puntos'

In [507]:
len(lista_feature_names)

1324

In [554]:
#hacemos esto para preparar los datos en las mismas variables todos los algoritmos

lista_features = lista_features_names_3puntos

X_train = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_train,lista_feature_sel=lista_features)
print(X_train.shape)
X_test  = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_features)
print(X_test.shape)
X_val   = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_val ,lista_feature_sel=lista_features)
print(X_val.shape)

(10282, 993)
(3445, 993)
(3445, 993)

In [448]:
params_grid = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 10, 20, 30, 40],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2', 0.5],
    'class_weight': [None, 'balanced', 'balanced_subsample']
}

In [449]:
optuna.logging.set_verbosity(optuna.logging.WARNING)
N_trials = 30

# Barra de progreso global
pbar = tqdm(total=N_trials, desc=f"Optimizando {nombre_algoritmo}")

# Crear el estudio

study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=SEED) 
)

# Enlazamos DIRECTAMENTE 'objective_universal' en el partial (evita usar alias antiguos)
objective_func = partial(
    objective_universal, 
    config=params_grid,
    clasificador_cls=ALGORITMO_CLASIFICADOR,
    X_train=X_train,
    X_test=X_test,
    Y_train_encoded=Y_train_encoded,
    Y_test_encoded=Y_test_encoded
)

# Ejecutar la optimización
print(f"=== INICIANDO OPTIMIZACIÓN DE {nombre_algoritmo} CON OPTUNA ===")
try:
    study.optimize(objective_func, n_trials=N_trials, callbacks=[print_callback], n_jobs=1)
finally:
    pbar.close()

# Resultados finales
print(f"\n=== MEJOR COMBINACIÓN ENCONTRADA ({nombre_algoritmo}) ===")
print(study.best_params)
print(f"Mejor Accuracy: {study.best_value:.4f}")

# Reconstruir el modelo final con los mejores parámetros óptimos
mejores_params = study.best_params.copy()
mejores_params['random_state'] = SEED
if 'n_jobs' in ALGORITMO_CLASIFICADOR().get_params():
    mejores_params['n_jobs'] = -1

Optimizando RandomForest:   0%|          | 0/30 [00:00<?, ?it/s]

=== INICIANDO OPTIMIZACIÓN DE RandomForest CON OPTUNA ===

Optimizando RandomForest:   3%|▎         | 1/30 [00:05<02:33,  5.29s/it, Mejor_Acc=0.5997, Trial=0]

Trial  0                | Actual Acc: 0.5997 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.5997 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:   7%|▋         | 2/30 [00:06<01:21,  2.90s/it, Mejor_Acc=0.5997, Trial=1]

Trial  1                | Actual Acc: 0.5753 | Parámetros: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.5997 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  10%|█         | 3/30 [00:24<04:30, 10.01s/it, Mejor_Acc=0.6061, Trial=2]

Trial  2                | Actual Acc: 0.6061 | Parámetros: {'n_estimators': 100, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6061 | Parámetros: {'n_estimators': 100, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  13%|█▎        | 4/30 [01:18<11:47, 27.21s/it, Mejor_Acc=0.6186, Trial=3]

Trial  3                | Actual Acc: 0.6186 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6186 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  17%|█▋        | 5/30 [01:38<10:15, 24.62s/it, Mejor_Acc=0.6186, Trial=4]

Trial  4                | Actual Acc: 0.3373 | Parámetros: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6186 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  20%|██        | 6/30 [01:41<06:52, 17.18s/it, Mejor_Acc=0.6186, Trial=5]

Trial  5                | Actual Acc: 0.5045 | Parámetros: {'n_estimators': 300, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'log2', 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6186 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  23%|██▎       | 7/30 [01:44<04:51, 12.67s/it, Mejor_Acc=0.6186, Trial=6]

Trial  6                | Actual Acc: 0.5666 | Parámetros: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6186 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  27%|██▋       | 8/30 [01:45<03:14,  8.85s/it, Mejor_Acc=0.6186, Trial=7]

Trial  7                | Actual Acc: 0.4746 | Parámetros: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'log2', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6186 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  30%|███       | 9/30 [02:11<04:56, 14.12s/it, Mejor_Acc=0.6186, Trial=8]

Trial  8                | Actual Acc: 0.5123 | Parámetros: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6186 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  33%|███▎      | 10/30 [02:17<03:53, 11.67s/it, Mejor_Acc=0.6186, Trial=9]

Trial  9                | Actual Acc: 0.6032 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6186 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  37%|███▋      | 11/30 [02:55<06:17, 19.86s/it, Mejor_Acc=0.6232, Trial=10]

Trial 10                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  40%|████      | 12/30 [03:32<07:31, 25.11s/it, Mejor_Acc=0.6232, Trial=11]

Trial 11                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  43%|████▎     | 13/30 [04:08<07:59, 28.21s/it, Mejor_Acc=0.6232, Trial=12]

Trial 12                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  47%|████▋     | 14/30 [04:42<08:02, 30.15s/it, Mejor_Acc=0.6232, Trial=13]

Trial 13                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  50%|█████     | 15/30 [05:16<07:50, 31.34s/it, Mejor_Acc=0.6232, Trial=14]

Trial 14                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  53%|█████▎    | 16/30 [05:28<05:56, 25.45s/it, Mejor_Acc=0.6232, Trial=15]

Trial 15                | Actual Acc: 0.3257 | Parámetros: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  57%|█████▋    | 17/30 [05:30<03:57, 18.30s/it, Mejor_Acc=0.6232, Trial=16]

Trial 16                | Actual Acc: 0.4853 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  60%|██████    | 18/30 [06:04<04:36, 23.00s/it, Mejor_Acc=0.6232, Trial=17]

Trial 17                | Actual Acc: 0.6206 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  63%|██████▎   | 19/30 [06:37<04:45, 25.97s/it, Mejor_Acc=0.6232, Trial=18]

Trial 18                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  67%|██████▋   | 20/30 [06:39<03:08, 18.88s/it, Mejor_Acc=0.6232, Trial=19]

Trial 19                | Actual Acc: 0.4731 | Parámetros: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  70%|███████   | 21/30 [07:11<03:25, 22.81s/it, Mejor_Acc=0.6232, Trial=20]

Trial 20                | Actual Acc: 0.6134 | Parámetros: {'n_estimators': 200, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  73%|███████▎  | 22/30 [07:44<03:26, 25.79s/it, Mejor_Acc=0.6232, Trial=21]

Trial 21                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  77%|███████▋  | 23/30 [08:17<03:15, 27.91s/it, Mejor_Acc=0.6232, Trial=22]

Trial 22                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  80%|████████  | 24/30 [08:49<02:55, 29.31s/it, Mejor_Acc=0.6232, Trial=23]

Trial 23                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  83%|████████▎ | 25/30 [09:22<02:32, 30.43s/it, Mejor_Acc=0.6232, Trial=24]

Trial 24                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  87%|████████▋ | 26/30 [09:50<01:58, 29.61s/it, Mejor_Acc=0.6232, Trial=25]

Trial 25                | Actual Acc: 0.5980 | Parámetros: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  90%|█████████ | 27/30 [10:23<01:31, 30.62s/it, Mejor_Acc=0.6232, Trial=26]

Trial 26                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  93%|█████████▎| 28/30 [10:27<00:45, 22.64s/it, Mejor_Acc=0.6232, Trial=27]

Trial 27                | Actual Acc: 0.5112 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  97%|█████████▋| 29/30 [10:29<00:16, 16.39s/it, Mejor_Acc=0.6232, Trial=28]

Trial 28                | Actual Acc: 0.5678 | Parámetros: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest: 100%|██████████| 30/30 [11:35<00:00, 23.19s/it, Mejor_Acc=0.6232, Trial=29]

Trial 29                | Actual Acc: 0.5977 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6232 | Parámetros: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

=== MEJOR COMBINACIÓN ENCONTRADA (RandomForest) ===
{'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced'}
Mejor Accuracy: 0.6232

In [485]:
clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
clf_anomalias_opt.fit(X_train, Y_train_encoded)

RandomForestClassifier(class_weight='balanced', max_features=0.5,
                       min_samples_split=5, n_estimators=200, n_jobs=-1,
                       random_state=100)

In [486]:

model_name=f'{nombre_algoritmo} ({DATOS})(todas las features)'
paquete_modelo={}

paquete_modelo['model_name']         = model_name
paquete_modelo['model']              = clf_anomalias_opt
paquete_modelo['parametros']         = mejores_params
paquete_modelo['lista_features']     = lista_features
paquete_modelo['N_features']         = len(paquete_modelo['lista_features'] )
paquete_modelo['N_features_unicas']  = len(get_lista_feature_sin_lag(paquete_modelo['lista_features'] ))
paquete_modelo['datos']              = DATOS
paquete_modelo['algoritmo']          = nombre_algoritmo

resultado,reporte_dict,Y_pred_probabilidades = evaluar_modelo(paquete_modelo,lista_features,X_test,Y_test_etiquetas,encoder_etiquetas)
print(f"=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===\n{model_name}")
print(paquete_modelo['classification_report_str'])

joblib.dump(paquete_modelo, f'{FOLDER_SALIDA}/models/{model_name}.joblib')

=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===
RandomForest (metricas_logs 3 puntos)(todas las features)
                                               precision    recall  f1-score   support

           access_token_auth_header_error_401       1.00      0.97      0.98        65
          access_token_authorization_form_401       0.43      0.58      0.49        65
         access_token_client_id_not_found_404       0.98      0.94      0.96        65
         access_token_client_secret_wrong_401       0.98      0.97      0.98        65
             access_token_form_urlencoded_400       0.61      0.57      0.59        65
          access_token_illegal_grant_type_400       0.97      0.98      0.98        65
access_token_missing_authorization_header_400       0.49      0.43      0.46        65
     authorization_code_client_id_missing_400       0.57      0.71      0.63        65
     authorization_code_invalid_client_id_404       0.63      0.65      0.64        65
      authorization_code_invalid_password_401       0.90      0.86      0.88        65
 authorization_code_missing_response_type_400       0.55      0.49      0.52        65
     authorization_code_response_not_code_400       0.71      0.54      0.61        65
       code_challenge_invalid_format_pkce_400       0.54      0.43      0.48        65
             code_challenge_too_long_pkce_400       0.58      0.48      0.53        65
            code_challenge_too_short_pkce_400       0.29      0.29      0.29        65
               code_verifier_missing_pkce_400       0.69      0.65      0.67        65
              code_verifier_too_long_pkce_400       0.18      0.11      0.13        65
             code_verifier_too_short_pkce_400       0.15      0.11      0.13        65
                  delete_client_404_no_client       1.00      1.00      1.00        65
                delete_service_404_no_service       0.65      0.74      0.69        65
                             delete_token_404       0.33      0.32      0.33        65
                      delete_user_404_no_user       0.14      0.12      0.13        65
                     get_client_404_no_client       0.96      1.00      0.98        65
                  get_client_page_400_no_page       1.00      1.00      1.00        65
                   get_service_404_no_service       0.33      0.46      0.38        65
                 get_service_page_400_no_page       0.58      0.74      0.65        65
                                get_token_404       0.35      0.34      0.35        65
                   get_token_page_400_no_page       0.55      0.65      0.59        65
                         get_user_404_no_user       0.42      0.43      0.42        65
                    get_user_page_400_no_page       0.38      0.54      0.45        65
       invalid_code_challenge_method_pkce_400       0.73      0.49      0.59        65
        invalid_code_verifier_format_PKCE_400       0.41      0.26      0.32        65
            register_client_400_clientProfile       0.98      0.98      0.98        65
               register_client_400_clientType       1.00      0.98      0.99        65
                  register_client_404_no_user       0.79      0.85      0.81        65
              register_service_400_service_id       0.93      0.78      0.85        65
            register_service_400_service_type       0.76      0.83      0.79        65
                 register_service_404_no_user       0.44      0.55      0.49        65
               register_user_400_email_exists       0.50      0.43      0.46        65
                register_user_400_no_password       0.46      0.55      0.50        65
          register_user_400_password_no_match       0.67      0.57      0.62        65
                register_user_400_user_exists       0.68      0.63      0.66        65
              update_client_400_clientProfile       1.00      0.98      0.99        65
                 update_client_400_clientType       1.00      1.00      1.00        65
                   update_client_404_clientId       0.37      0.65      0.47        65
                    update_client_404_ownerId       0.84      0.74      0.79        65
                update_password_400_not_match       0.60      0.74      0.66        65
           update_password_401_wrong_password       0.26      0.31      0.28        65
           update_password_404_user_not_found       0.23      0.14      0.17        65
                update_service_404_service_id       0.82      0.71      0.76        65
                   update_service_404_user_id       0.75      0.82      0.78        65
                      update_user_404_no_user       0.53      0.68      0.59        65
                 verification_failed_pkce_400       0.45      0.26      0.33        65

                                     accuracy                           0.62      3445
                                    macro avg       0.63      0.62      0.62      3445
                                 weighted avg       0.63      0.62      0.62      3445

['result/models/RandomForest (metricas_logs 3 puntos)(todas las features).joblib']

In [495]:
df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
print(f"Características con importancia cero: {num_cero}")

Características con importancia cero: 35

(10282, 993)

In [555]:
n_min = 62
n_max = len(importancias) - num_cero
lista_result = []

# --- VARIABLES PARA EL EARLY STOPPING ---
paciencia = 15
iteraciones_sin_mejora = 0
mejor_score_global = -1.0
mejor_paquete_modelo = None

for N_feat in range(n_min, n_max + 1):
    model_name = f'{nombre_algoritmo} ({DATOS})   N_feat={N_feat}'
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:N_feat]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(feature)

    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
    # accuracy        = resultado['accuracy']
    # macro_f1        = resultado['f1']
    # macro_precision = resultado['precision']
    # macro_recall    = resultado['recall']
    
    # paquete_modelo['metrics'] = {
    #     'accuracy': accuracy,
    #     'macro_f1': macro_f1,
    #     'macro_precision': macro_precision,
    #     'macro_recall': macro_recall
    # }
    
    lista_result.append(paquete_modelo)

    # --- LÓGICA DE EARLY STOPPING ---
    score_actual = macro_f1 
    
    if score_actual > mejor_score_global:
        mejor_score_global = score_actual
        mejor_paquete_modelo = paquete_modelo.copy()
        iteraciones_sin_mejora = 0  # Reiniciamos contador si mejora
    else:
        iteraciones_sin_mejora += 1

    # --- IMPRESIÓN EN UNA SOLA LÍNEA ---
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Mejor Macro F1 = {mejor_score_global:.4f} | Iteraciones_sin_mejora = {iteraciones_sin_mejora}")

    # Comprobación de parada
    if iteraciones_sin_mejora >= paciencia:
        print(f"\n[!] Early Stopping activado: No ha habido mejoras en {paciencia} iteraciones consecutivas.")
        print(f"Deteniendo búsqueda. El mejor modelo se logró con {mejor_paquete_modelo['N_features_unicas']} características base.")
        break

ValueError: Found array with 0 feature(s) (shape=(3445, 0)) while a minimum of 1 is required by RandomForestClassifier.

In [546]:
# 1. Partimos del modelo en el que nos hemos parado (llevaba ya le numero de iteraciones paciencia sin mejorar)
paquete_modelo_back = lista_result[-1].copy()

In [547]:
paquete_modelo = mejor_paquete_modelo.copy()

In [550]:
lista_features_sel

[]

In [553]:
len(paquete_modelo['lista_features'])

43

In [548]:

paquete_modelo = mejor_paquete_modelo.copy()

mejor_macro_f1_global    = paquete_modelo['resultado']['f1']
mejor_features_global    = paquete_modelo['lista_features'].copy()
pasos_sin_mejora         = 0
limite_puntos_sin_mejora = paciencia + 5

print(f"Iniciando eliminación recursiva desde {paquete_modelo['N_features_unicas']} características.\n")

while paquete_modelo['N_features_unicas'] > 1 and pasos_sin_mejora < limite_puntos_sin_mejora:
    N_feat = paquete_modelo['N_features_unicas']
    
    # Extraer importancias y características actuales
    importancias_raw = paquete_modelo['model'].feature_importances_
    features_raw = paquete_modelo['lista_features']
    
    df_importancias_agrupada, _, num_cero = obtener_importancias_agrupadas(importancias_raw, features_raw)

    # Seleccionar características para el siguiente paso
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:(N_feat-1)]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(f'{feature}')
    
    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    model_name = f'{nombre_algoritmo} (metricas_log) N_feat={N_feat-1}'
    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
   
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    

    
    if macro_f1 >= mejor_macro_f1_global:
        mejor_macro_f1_global = macro_f1
        mejor_features_global = paquete_modelo['lista_features'].copy()
        pasos_sin_mejora = 0  
        mejor_paquete_modelo = paquete_modelo.copy()
    else:
        pasos_sin_mejora += 1  
        
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Sin mejora: {pasos_sin_mejora}")
    del X_train_sub, X_test_sub, importancias_raw, df_importancias_agrupada
    gc.collect()

print(f"\n¡Proceso finalizado!")
print(f"Mejor Macro F1 alcanzado: {mejor_macro_f1_global:.4f}")
print(f"Número óptimo de características base: {len(mejor_features_global)}")

Iniciando eliminación recursiva desde 43 características.

ValueError: Found array with 0 feature(s) (shape=(10282, 0)) while a minimum of 1 is required by RandomForestClassifier.

In [501]:
mejor_paquete_modelo['model_name']

'RandomForest (metricas_logs 3 puntos)   N_feat=63'

In [502]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

['result/models/RandomForest (metricas_logs 3 puntos)   N_feat=63.joblib']

### <span style="color:#2ca02c">4.1.2 Clasificador Random Forest (1 punto de 3 intervalos) con metricas_logs</span>

In [45]:
N_puntos = 1
DATOS    = 'metricas_logs 1 punto suma'

In [46]:
lista_features = lista_feature_names_1punto_sum

X_train = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_train,lista_feature_sel=lista_features)
print(X_train.shape)
X_test  = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_features)
print(X_test.shape)
X_val   = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_val ,lista_feature_sel=lista_features)
print(X_val.shape)

(10282, 331)
(3445, 331)
(3445, 331)

In [47]:
len(lista_features)

331

In [48]:
params_grid = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 10, 20, 30, 40],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2', 0.5],
    'class_weight': [None, 'balanced', 'balanced_subsample']
}

In [49]:
optuna.logging.set_verbosity(optuna.logging.WARNING)
N_trials = 30

# Barra de progreso global
pbar = tqdm(total=N_trials, desc=f"Optimizando {nombre_algoritmo}")

# Crear el estudio

study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=SEED) 
)

# Enlazamos DIRECTAMENTE 'objective_universal' en el partial (evita usar alias antiguos)
objective_func = partial(
    objective_universal, 
    config=params_grid,
    clasificador_cls=ALGORITMO_CLASIFICADOR,
    X_train=X_train,
    X_test=X_test,
    Y_train_encoded=Y_train_encoded,
    Y_test_encoded=Y_test_encoded
)

# Ejecutar la optimización
print(f"=== INICIANDO OPTIMIZACIÓN DE {nombre_algoritmo} CON OPTUNA ===")
try:
    study.optimize(objective_func, n_trials=N_trials, callbacks=[print_callback], n_jobs=1)
finally:
    pbar.close()

# Resultados finales
print(f"\n=== MEJOR COMBINACIÓN ENCONTRADA ({nombre_algoritmo}) ===")
print(study.best_params)
print(f"Mejor Accuracy: {study.best_value:.4f}")

# Reconstruir el modelo final con los mejores parámetros óptimos
mejores_params = study.best_params.copy()
mejores_params['random_state'] = SEED
if 'n_jobs' in ALGORITMO_CLASIFICADOR().get_params():
    mejores_params['n_jobs'] = -1

Optimizando RandomForest:   0%|          | 0/30 [00:00<?, ?it/s]

=== INICIANDO OPTIMIZACIÓN DE RandomForest CON OPTUNA ===

Optimizando RandomForest:   3%|▎         | 1/30 [00:04<01:58,  4.07s/it, Mejor_Acc=0.6000, Trial=0]

Trial  0                | Actual Acc: 0.6000 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6000 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:   7%|▋         | 2/30 [00:05<01:04,  2.31s/it, Mejor_Acc=0.6000, Trial=1]

Trial  1                | Actual Acc: 0.5782 | Parámetros: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6000 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  10%|█         | 3/30 [00:13<02:19,  5.15s/it, Mejor_Acc=0.6000, Trial=2]

Trial  2                | Actual Acc: 0.5916 | Parámetros: {'n_estimators': 100, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6000 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  13%|█▎        | 4/30 [00:35<05:03, 11.67s/it, Mejor_Acc=0.6044, Trial=3]

Trial  3                | Actual Acc: 0.6044 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6044 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  17%|█▋        | 5/30 [00:42<04:11, 10.08s/it, Mejor_Acc=0.6044, Trial=4]

Trial  4                | Actual Acc: 0.4357 | Parámetros: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6044 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  20%|██        | 6/30 [00:43<02:50,  7.11s/it, Mejor_Acc=0.6044, Trial=5]

Trial  5                | Actual Acc: 0.5579 | Parámetros: {'n_estimators': 300, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'log2', 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6044 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  23%|██▎       | 7/30 [00:45<02:04,  5.40s/it, Mejor_Acc=0.6044, Trial=6]

Trial  6                | Actual Acc: 0.5852 | Parámetros: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6044 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  27%|██▋       | 8/30 [00:46<01:23,  3.82s/it, Mejor_Acc=0.6044, Trial=7]

Trial  7                | Actual Acc: 0.5118 | Parámetros: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'log2', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6044 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  30%|███       | 9/30 [00:55<01:53,  5.40s/it, Mejor_Acc=0.6044, Trial=8]

Trial  8                | Actual Acc: 0.5573 | Parámetros: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6044 | Parámetros: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  33%|███▎      | 10/30 [00:58<01:35,  4.79s/it, Mejor_Acc=0.6058, Trial=9]

Trial  9                | Actual Acc: 0.6058 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6058 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  37%|███▋      | 11/30 [01:02<01:25,  4.53s/it, Mejor_Acc=0.6070, Trial=10]

Trial 10                | Actual Acc: 0.6070 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6070 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  40%|████      | 12/30 [01:06<01:17,  4.31s/it, Mejor_Acc=0.6070, Trial=11]

Trial 11                | Actual Acc: 0.6070 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6070 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  43%|████▎     | 13/30 [01:10<01:11,  4.18s/it, Mejor_Acc=0.6070, Trial=12]

Trial 12                | Actual Acc: 0.6070 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6070 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  47%|████▋     | 14/30 [01:13<01:04,  4.06s/it, Mejor_Acc=0.6070, Trial=13]

Trial 13                | Actual Acc: 0.6070 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': None}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6070 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': None}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  50%|█████     | 15/30 [01:17<00:59,  3.98s/it, Mejor_Acc=0.6102, Trial=14]

Trial 14                | Actual Acc: 0.6102 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6102 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  53%|█████▎    | 16/30 [01:18<00:42,  3.03s/it, Mejor_Acc=0.6102, Trial=15]

Trial 15                | Actual Acc: 0.5451 | Parámetros: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6102 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  57%|█████▋    | 17/30 [01:20<00:36,  2.77s/it, Mejor_Acc=0.6102, Trial=16]

Trial 16                | Actual Acc: 0.5800 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6102 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  60%|██████    | 18/30 [01:24<00:37,  3.12s/it, Mejor_Acc=0.6102, Trial=17]

Trial 17                | Actual Acc: 0.6102 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6102 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  63%|██████▎   | 19/30 [01:28<00:37,  3.40s/it, Mejor_Acc=0.6102, Trial=18]

Trial 18                | Actual Acc: 0.6087 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6102 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  67%|██████▋   | 20/30 [01:29<00:25,  2.56s/it, Mejor_Acc=0.6102, Trial=19]

Trial 19                | Actual Acc: 0.5158 | Parámetros: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6102 | Parámetros: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  70%|███████   | 21/30 [01:33<00:26,  2.96s/it, Mejor_Acc=0.6136, Trial=20]

Trial 20                | Actual Acc: 0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  73%|███████▎  | 22/30 [01:36<00:25,  3.20s/it, Mejor_Acc=0.6136, Trial=21]

Trial 21                | Actual Acc: 0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  77%|███████▋  | 23/30 [01:40<00:24,  3.43s/it, Mejor_Acc=0.6136, Trial=22]

Trial 22                | Actual Acc: 0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  80%|████████  | 24/30 [01:44<00:21,  3.54s/it, Mejor_Acc=0.6136, Trial=23]

Trial 23                | Actual Acc: 0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  83%|████████▎ | 25/30 [01:48<00:18,  3.65s/it, Mejor_Acc=0.6136, Trial=24]

Trial 24                | Actual Acc: 0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  87%|████████▋ | 26/30 [01:52<00:14,  3.70s/it, Mejor_Acc=0.6136, Trial=25]

Trial 25                | Actual Acc: 0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  90%|█████████ | 27/30 [01:56<00:11,  3.75s/it, Mejor_Acc=0.6136, Trial=26]

Trial 26                | Actual Acc: 0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  93%|█████████▎| 28/30 [01:57<00:06,  3.12s/it, Mejor_Acc=0.6136, Trial=27]

Trial 27                | Actual Acc: 0.5988 | Parámetros: {'n_estimators': 200, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest:  97%|█████████▋| 29/30 [02:04<00:04,  4.17s/it, Mejor_Acc=0.6136, Trial=28]

Trial 28                | Actual Acc: 0.5919 | Parámetros: {'n_estimators': 100, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

Optimizando RandomForest: 100%|██████████| 30/30 [02:06<00:00,  4.23s/it, Mejor_Acc=0.6136, Trial=29]

Trial 29                | Actual Acc: 0.5736 | Parámetros: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6136 | Parámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
----------------------------------------------------------------------------------------------------

=== MEJOR COMBINACIÓN ENCONTRADA (RandomForest) ===
{'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced'}
Mejor Accuracy: 0.6136

In [100]:
clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
clf_anomalias_opt.fit(X_train, Y_train_encoded)

RandomForestClassifier(class_weight='balanced', max_depth=40,
                       min_samples_split=10, n_estimators=500, n_jobs=-1,
                       random_state=100)

In [101]:
model_name=f'{nombre_algoritmo} ({DATOS})(todas las features)'
paquete_modelo={}

paquete_modelo['model_name']         = model_name
paquete_modelo['model']              = clf_anomalias_opt
paquete_modelo['parametros']         = mejores_params
paquete_modelo['lista_features']     = lista_features
paquete_modelo['N_features']         = len(paquete_modelo['lista_features'] )
paquete_modelo['N_features_unicas']  = len(get_lista_feature_sin_lag(paquete_modelo['lista_features'] ))
paquete_modelo['datos']              = DATOS
paquete_modelo['algoritmo']          = nombre_algoritmo

resultado,reporte_dict,Y_pred_probabilidades = evaluar_modelo(paquete_modelo,lista_features,X_test,Y_test_etiquetas,encoder_etiquetas)
print(f"=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===\n{model_name}")
print(paquete_modelo['classification_report_str'])

joblib.dump(paquete_modelo, f'{FOLDER_SALIDA}/models/{model_name}.joblib')

=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===
RandomForest (metricas_logs 1 punto suma)(todas las features)
                                               precision    recall  f1-score   support

           access_token_auth_header_error_401       0.87      0.92      0.90        65
          access_token_authorization_form_401       0.44      0.83      0.57        65
         access_token_client_id_not_found_404       0.97      1.00      0.98        65
         access_token_client_secret_wrong_401       0.93      0.95      0.94        65
             access_token_form_urlencoded_400       0.68      0.66      0.67        65
          access_token_illegal_grant_type_400       1.00      1.00      1.00        65
access_token_missing_authorization_header_400       0.43      0.28      0.34        65
     authorization_code_client_id_missing_400       0.70      0.71      0.70        65
     authorization_code_invalid_client_id_404       0.60      0.66      0.63        65
      authorization_code_invalid_password_401       0.86      0.77      0.81        65
 authorization_code_missing_response_type_400       0.72      0.65      0.68        65
     authorization_code_response_not_code_400       0.74      0.66      0.70        65
       code_challenge_invalid_format_pkce_400       0.57      0.65      0.60        65
             code_challenge_too_long_pkce_400       0.55      0.45      0.49        65
            code_challenge_too_short_pkce_400       0.28      0.29      0.29        65
               code_verifier_missing_pkce_400       0.56      0.68      0.61        65
              code_verifier_too_long_pkce_400       0.23      0.17      0.20        65
             code_verifier_too_short_pkce_400       0.30      0.18      0.23        65
                  delete_client_404_no_client       1.00      1.00      1.00        65
                delete_service_404_no_service       0.68      0.72      0.70        65
                             delete_token_404       0.47      0.65      0.54        65
                      delete_user_404_no_user       0.12      0.05      0.07        65
                     get_client_404_no_client       1.00      1.00      1.00        65
                  get_client_page_400_no_page       1.00      1.00      1.00        65
                   get_service_404_no_service       0.31      0.31      0.31        65
                 get_service_page_400_no_page       0.60      0.82      0.69        65
                                get_token_404       0.36      0.12      0.18        65
                   get_token_page_400_no_page       0.47      0.62      0.53        65
                         get_user_404_no_user       0.23      0.23      0.23        65
                    get_user_page_400_no_page       0.29      0.43      0.35        65
       invalid_code_challenge_method_pkce_400       0.52      0.48      0.50        65
        invalid_code_verifier_format_PKCE_400       0.18      0.05      0.07        65
            register_client_400_clientProfile       0.84      0.91      0.87        65
               register_client_400_clientType       0.92      0.83      0.87        65
                  register_client_404_no_user       0.93      0.82      0.87        65
              register_service_400_service_id       0.96      0.71      0.81        65
            register_service_400_service_type       0.68      0.80      0.73        65
                 register_service_404_no_user       0.43      0.77      0.56        65
               register_user_400_email_exists       0.62      0.55      0.59        65
                register_user_400_no_password       0.55      0.72      0.63        65
          register_user_400_password_no_match       0.69      0.51      0.58        65
                register_user_400_user_exists       0.63      0.63      0.63        65
              update_client_400_clientProfile       1.00      0.98      0.99        65
                 update_client_400_clientType       1.00      1.00      1.00        65
                   update_client_404_clientId       0.33      0.51      0.40        65
                    update_client_404_ownerId       0.93      0.60      0.73        65
                update_password_400_not_match       0.39      0.62      0.48        65
           update_password_401_wrong_password       0.22      0.22      0.22        65
           update_password_404_user_not_found       0.20      0.12      0.15        65
                update_service_404_service_id       0.76      0.68      0.72        65
                   update_service_404_user_id       0.72      0.85      0.78        65
                      update_user_404_no_user       0.54      0.65      0.59        65
                 verification_failed_pkce_400       0.22      0.09      0.13        65

                                     accuracy                           0.61      3445
                                    macro avg       0.61      0.61      0.60      3445
                                 weighted avg       0.61      0.61      0.60      3445

['result/models/RandomForest (metricas_logs 1 punto suma)(todas las features).joblib']

In [102]:
df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
print(f"Características con importancia cero: {num_cero}")

Características con importancia cero: 30

In [103]:
df_importancias_agrupada

                            caracteristica  importancia
0       light-oauth2-oauth2-user-1(0)(sum)     0.033865
1    light-oauth2-oauth2-service-1(0)(sum)     0.028705
2       light-oauth2-oauth2-code-1(0)(sum)     0.022908
3    light-oauth2-oauth2-client-1(20)(sum)     0.020397
4    light-oauth2-oauth2-client-1(14)(sum)     0.020376
..                                     ...          ...
326  light-oauth2-oauth2-client-1(74)(sum)     0.000000
327  light-oauth2-oauth2-client-1(69)(sum)     0.000000
328  light-oauth2-oauth2-client-1(68)(sum)     0.000000
329   light-oauth2-oauth2-token-1(99)(sum)     0.000000
330  light-oauth2-oauth2-client-1(71)(sum)     0.000000

[331 rows x 2 columns]

In [104]:
n_min = 78
n_max = len(importancias) - num_cero
lista_result = []

# --- VARIABLES PARA EL EARLY STOPPING ---
paciencia = 10
iteraciones_sin_mejora = 0
mejor_score_global = -1.0
mejor_paquete_modelo = None

for N_feat in range(n_min, n_max + 1):
    model_name = f'{nombre_algoritmo} ({DATOS})   N_feat={N_feat}'
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:N_feat]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(feature)

    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
    # accuracy        = resultado['accuracy']
    # macro_f1        = resultado['f1']
    # macro_precision = resultado['precision']
    # macro_recall    = resultado['recall']
    
    # paquete_modelo['resultado'] = {
    #     'accuracy': accuracy,
    #     'macro_f1': macro_f1,
    #     'macro_precision': macro_precision,
    #     'macro_recall': macro_recall
    # }
    
    #lista_result.append(paquete_modelo)

    # --- LÓGICA DE EARLY STOPPING ---
    score_actual = macro_f1 
    
    if score_actual > mejor_score_global:
        mejor_score_global = score_actual
        mejor_paquete_modelo = paquete_modelo.copy()
        iteraciones_sin_mejora = 0  # Reiniciamos contador si mejora
    else:
        iteraciones_sin_mejora += 1

    # --- IMPRESIÓN EN UNA SOLA LÍNEA ---
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Mejor Macro F1 = {mejor_score_global:.4f} | Iteraciones_sin_mejora = {iteraciones_sin_mejora}")
    del X_train_sub, X_test_sub
    gc.collect()
    
    # Comprobación de parada
    if iteraciones_sin_mejora >= paciencia:
        print(f"\n[!] Early Stopping activado: No ha habido mejoras en {paciencia} iteraciones consecutivas.")
        print(f"Deteniendo búsqueda. El mejor modelo se logró con {mejor_paquete_modelo['N_features_unicas']} características base.")
        break

Model = RandomForest (metricas_logs 1 punto suma)   N_feat=78 Accuracy = 0.6276 | Macro F1 = 0.6197 | Macro Precision = 0.6283 | Macro Recall = 0.6276 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 0
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=79 Accuracy = 0.6186 | Macro F1 = 0.6105 | Macro Precision = 0.6183 | Macro Recall = 0.6186 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 1
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=80 Accuracy = 0.6197 | Macro F1 = 0.6114 | Macro Precision = 0.6195 | Macro Recall = 0.6197 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 2
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=81 Accuracy = 0.6183 | Macro F1 = 0.6111 | Macro Precision = 0.6198 | Macro Recall = 0.6183 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 3
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=82 Accuracy = 0.6221 | Macro F1 = 0.6139 | Macro Precision = 0.6240 | Macro Recall = 0.6221 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 4
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=83 Accuracy = 0.6209 | Macro F1 = 0.6134 | Macro Precision = 0.6230 | Macro Recall = 0.6209 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 5
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=84 Accuracy = 0.6154 | Macro F1 = 0.6078 | Macro Precision = 0.6185 | Macro Recall = 0.6154 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 6
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=85 Accuracy = 0.6215 | Macro F1 = 0.6124 | Macro Precision = 0.6200 | Macro Recall = 0.6215 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 7
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=86 Accuracy = 0.6235 | Macro F1 = 0.6153 | Macro Precision = 0.6248 | Macro Recall = 0.6235 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 8
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=87 Accuracy = 0.6226 | Macro F1 = 0.6144 | Macro Precision = 0.6227 | Macro Recall = 0.6226 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 9
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=88 Accuracy = 0.6247 | Macro F1 = 0.6167 | Macro Precision = 0.6273 | Macro Recall = 0.6247 | Mejor Macro F1 = 0.6197 | Iteraciones_sin_mejora = 10

[!] Early Stopping activado: No ha habido mejoras en 10 iteraciones consecutivas.
Deteniendo búsqueda. El mejor modelo se logró con 78 características base.

In [105]:
xxx=mejor_paquete_modelo.copy()

In [106]:
df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
print(f"Características con importancia cero: {num_cero}")

Características con importancia cero: 0

In [107]:
df_importancias_agrupada

                            caracteristica  importancia
0      light-oauth2-oauth2-code-1(27)(sum)     0.044427
1   light-oauth2-oauth2-service-1(10)(sum)     0.037410
2     light-oauth2-oauth2-token-1(41)(sum)     0.028990
3       light-oauth2-oauth2-user-1(6)(sum)     0.024863
4    light-oauth2-oauth2-client-1(14)(sum)     0.023616
..                                     ...          ...
83   light-oauth2-oauth2-client-1(11)(sum)     0.006002
84     light-oauth2-oauth2-code-1(22)(sum)     0.005994
85      light-oauth2-oauth2-user-1(7)(sum)     0.005748
86   light-oauth2-oauth2-client-1(15)(sum)     0.005483
87      light-oauth2-oauth2-user-1(1)(sum)     0.004757

[88 rows x 2 columns]

In [116]:

paquete_modelo = mejor_paquete_modelo.copy()


# features_actuales = df_importancias_agrupada['caracteristica'].to_list()[:N_inicio]

mejor_macro_f1_global    = paquete_modelo['resultado']['macro_f1']
mejor_features_global    = paquete_modelo['lista_features'].copy()
pasos_sin_mejora         = 0
limite_puntos_sin_mejora = paciencia + 5

print(f"Iniciando eliminación recursiva desde {paquete_modelo['N_features_unicas']} características.\n")

while paquete_modelo['N_features_unicas'] > 1 and pasos_sin_mejora < limite_puntos_sin_mejora:

    df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
 
    lista_features_sel=[]
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:(N_feat-1)]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(f'{feature}')

    
    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)
    
    N_feat = len(lista_features_sel)
    model_name = f'{nombre_algoritmo} ({DATOS})   N_feat={N_feat}'

    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    

    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo,lista_feature_names1_sum,X_test_sum,Y_test_etiquetas,encoder_etiquetas)

    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    


    
    if macro_f1 >= mejor_macro_f1_global:
        mejor_macro_f1_global = macro_f1
        mejor_features_global = paquete_modelo['lista_features'].copy()
        pasos_sin_mejora = 0  # ¡Se reinicia porque hemos batido o empatado el récord global!
        mejor_paquete_modelo=paquete_modelo.copy()
    else:
        pasos_sin_mejora += 1  # Si es peor que el récord histórico, sumamos 1
        
    # Imprimir con el formato solicitado (mostrando ya el contador de "Sin mejora" actualizado)
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Sin mejora: {pasos_sin_mejora}")
        

print(f"\n¡Proceso finalizado!")
print(f"Mejor Macro F1 alcanzado: {mejor_macro_f1_global:.4f}")
print(f"Número óptimo de características base: {len(mejor_features_global)}")

Iniciando eliminación recursiva desde 78 características.

Model = RandomForest (metricas_logs 1 punto suma)   N_feat=72 Accuracy = 0.6093 | Macro F1 = 0.6001 | Macro Precision = 0.6090 | Macro Recall = 0.6093 | Sin mejora: 1
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=71 Accuracy = 0.6055 | Macro F1 = 0.5986 | Macro Precision = 0.6087 | Macro Recall = 0.6055 | Sin mejora: 2
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=70 Accuracy = 0.6035 | Macro F1 = 0.5960 | Macro Precision = 0.6033 | Macro Recall = 0.6035 | Sin mejora: 3
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=69 Accuracy = 0.6032 | Macro F1 = 0.5941 | Macro Precision = 0.6017 | Macro Recall = 0.6032 | Sin mejora: 4
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=68 Accuracy = 0.5579 | Macro F1 = 0.5460 | Macro Precision = 0.5544 | Macro Recall = 0.5579 | Sin mejora: 5
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=67 Accuracy = 0.5417 | Macro F1 = 0.5305 | Macro Precision = 0.5391 | Macro Recall = 0.5417 | Sin mejora: 6
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=66 Accuracy = 0.5367 | Macro F1 = 0.5256 | Macro Precision = 0.5347 | Macro Recall = 0.5367 | Sin mejora: 7
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=65 Accuracy = 0.5300 | Macro F1 = 0.5193 | Macro Precision = 0.5263 | Macro Recall = 0.5300 | Sin mejora: 8
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=64 Accuracy = 0.5306 | Macro F1 = 0.5195 | Macro Precision = 0.5279 | Macro Recall = 0.5306 | Sin mejora: 9
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=63 Accuracy = 0.5347 | Macro F1 = 0.5227 | Macro Precision = 0.5299 | Macro Recall = 0.5347 | Sin mejora: 10
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=62 Accuracy = 0.5358 | Macro F1 = 0.5248 | Macro Precision = 0.5317 | Macro Recall = 0.5358 | Sin mejora: 11
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=61 Accuracy = 0.5344 | Macro F1 = 0.5222 | Macro Precision = 0.5298 | Macro Recall = 0.5344 | Sin mejora: 12
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=60 Accuracy = 0.5327 | Macro F1 = 0.5215 | Macro Precision = 0.5290 | Macro Recall = 0.5327 | Sin mejora: 13
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=59 Accuracy = 0.5358 | Macro F1 = 0.5240 | Macro Precision = 0.5327 | Macro Recall = 0.5358 | Sin mejora: 14
Model = RandomForest (metricas_logs 1 punto suma)   N_feat=58 Accuracy = 0.5327 | Macro F1 = 0.5213 | Macro Precision = 0.5275 | Macro Recall = 0.5327 | Sin mejora: 15

¡Proceso finalizado!
Mejor Macro F1 alcanzado: 0.6197
Número óptimo de características base: 78

In [109]:
mejor_paquete_modelo['model_name']

'RandomForest (metricas_logs 1 punto suma)   N_feat=78'

In [110]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

['result/models/RandomForest (metricas_logs 1 punto suma)   N_feat=78.joblib']

In [117]:
mejor_paquete_modelo['resultado']

{'accuracy': 0.6275761973875181,
 'macro_f1': 0.6197418658287879,
 'macro_precision': 0.6283339292003264,
 'macro_recall': 0.6275761973875182}

## <span style="color:#2ca02c">4.2. Clasificador XGBoost con metricas_logs</span>

In [34]:
ALGORITMO_CLASIFICADOR = XGBClassifier
nombre_algoritmo       ='XGBoost'

## <span style="color:#2ca02c">4.2.1. Clasificador XGBoost (3 puntos)con metricas_logs</span>

In [35]:
N_puntos = 3
DATOS    = 'metricas_logs 3 puntos'

In [43]:
#hacemos esto para preparar los datos en las mismas variables todos los algoritmos

lista_features = lista_features_names_3puntos

X_train = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_train,lista_feature_sel=lista_features)
print(X_train.shape)
X_test  = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_features)
print(X_test.shape)
X_val   = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_val ,lista_feature_sel=lista_features)
print(X_val.shape)

(427, 993)
(143, 993)
(143, 993)

In [44]:
#la funcion objetivo y el conjunto de parametros es especifico del algoritmo por eso los dejamos en una celda aparte

params_grid = {
    'n_estimators': [200, 300, 400],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [6, 8, 10],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 2, 3],
    'gamma': [0.0, 0.1, 0.2]
}

In [91]:
optuna.logging.set_verbosity(optuna.logging.WARNING)
N_trials = 30

# Barra de progreso global
pbar = tqdm(total=N_trials, desc=f"Optimizando {nombre_algoritmo}")

# Crear el estudio

study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=SEED) 
)

# Enlazamos DIRECTAMENTE 'objective_universal' en el partial (evita usar alias antiguos)
objective_func = partial(
    objective_universal, 
    config=params_grid,
    clasificador_cls=ALGORITMO_CLASIFICADOR,
    X_train=X_train,
    X_test=X_test,
    Y_train_encoded=Y_train_encoded,
    Y_test_encoded=Y_test_encoded
)

# Ejecutar la optimización
print(f"=== INICIANDO OPTIMIZACIÓN DE {nombre_algoritmo} CON OPTUNA ===")
try:
    study.optimize(objective_func, n_trials=N_trials, callbacks=[print_callback], n_jobs=1)
finally:
    pbar.close()

# Resultados finales
print(f"\n=== MEJOR COMBINACIÓN ENCONTRADA ({nombre_algoritmo}) ===")
print(study.best_params)
print(f"Mejor Accuracy: {study.best_value:.4f}")

# Reconstruir el modelo final con los mejores parámetros óptimos
mejores_params = study.best_params.copy()
mejores_params['random_state'] = SEED
if 'n_jobs' in ALGORITMO_CLASIFICADOR().get_params():
    mejores_params['n_jobs'] = -1

Optimizando XGBoost:   0%|          | 0/30 [00:00<?, ?it/s]

=== INICIANDO OPTIMIZACIÓN DE XGBoost CON OPTUNA ===

Optimizando XGBoost:   3%|▎         | 1/30 [02:43<1:19:07, 163.71s/it, Mejor_Acc=0.6578, Trial=0]

Trial  0                | Actual Acc: 0.6578 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6578 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:   7%|▋         | 2/30 [05:00<1:09:06, 148.07s/it, Mejor_Acc=0.6763, Trial=1]

Trial  1                | Actual Acc: 0.6763 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6763 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  10%|█         | 3/30 [07:41<1:09:15, 153.92s/it, Mejor_Acc=0.6763, Trial=2]

Trial  2                | Actual Acc: 0.6763 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6763 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  13%|█▎        | 4/30 [11:44<1:21:57, 189.14s/it, Mejor_Acc=0.6804, Trial=3]

Trial  3                | Actual Acc: 0.6804 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6804 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  17%|█▋        | 5/30 [17:18<1:40:32, 241.28s/it, Mejor_Acc=0.6804, Trial=4]

Trial  4                | Actual Acc: 0.6702 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.01, 'max_depth': 10, 'subsample': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6804 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  20%|██        | 6/30 [20:07<1:26:37, 216.57s/it, Mejor_Acc=0.6804, Trial=5]

Trial  5                | Actual Acc: 0.6801 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6804 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  23%|██▎       | 7/30 [24:32<1:29:04, 232.35s/it, Mejor_Acc=0.6804, Trial=6]

Trial  6                | Actual Acc: 0.6682 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 10, 'subsample': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6804 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  27%|██▋       | 8/30 [29:33<1:33:17, 254.44s/it, Mejor_Acc=0.6827, Trial=7]

Trial  7                | Actual Acc: 0.6827 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6827 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  30%|███       | 9/30 [33:36<1:27:44, 250.67s/it, Mejor_Acc=0.6827, Trial=8]

Trial  8                | Actual Acc: 0.6804 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6827 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  33%|███▎      | 10/30 [35:46<1:11:12, 213.62s/it, Mejor_Acc=0.6827, Trial=9]

Trial  9                | Actual Acc: 0.6560 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 6, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 2, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6827 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  37%|███▋      | 11/30 [39:47<1:10:18, 222.02s/it, Mejor_Acc=0.6827, Trial=10]

Trial 10                | Actual Acc: 0.6755 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6827 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  40%|████      | 12/30 [43:56<1:09:04, 230.26s/it, Mejor_Acc=0.6827, Trial=11]

Trial 11                | Actual Acc: 0.6804 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6827 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  43%|████▎     | 13/30 [48:59<1:11:26, 252.14s/it, Mejor_Acc=0.6845, Trial=12]

Trial 12                | Actual Acc: 0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  47%|████▋     | 14/30 [53:58<1:10:59, 266.19s/it, Mejor_Acc=0.6845, Trial=13]

Trial 13                | Actual Acc: 0.6830 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  50%|█████     | 15/30 [58:55<1:08:54, 275.65s/it, Mejor_Acc=0.6845, Trial=14]

Trial 14                | Actual Acc: 0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  53%|█████▎    | 16/30 [1:02:33<1:00:14, 258.19s/it, Mejor_Acc=0.6845, Trial=15]

Trial 15                | Actual Acc: 0.6816 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  57%|█████▋    | 17/30 [1:06:22<54:02, 249.43s/it, Mejor_Acc=0.6845, Trial=16]

Trial 16                | Actual Acc: 0.6833 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  60%|██████    | 18/30 [1:11:43<54:12, 271.01s/it, Mejor_Acc=0.6845, Trial=17]

Trial 17                | Actual Acc: 0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6845 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.0}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  63%|██████▎   | 19/30 [1:15:08<46:03, 251.24s/it, Mejor_Acc=0.6856, Trial=18]

Trial 18                | Actual Acc: 0.6856 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6856 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  67%|██████▋   | 20/30 [1:17:15<35:39, 213.97s/it, Mejor_Acc=0.6856, Trial=19]

Trial 19                | Actual Acc: 0.6714 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6856 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  70%|███████   | 21/30 [1:19:28<28:25, 189.46s/it, Mejor_Acc=0.6882, Trial=20]

Trial 20                | Actual Acc: 0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  73%|███████▎  | 22/30 [1:21:40<22:58, 172.27s/it, Mejor_Acc=0.6882, Trial=21]

Trial 21                | Actual Acc: 0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  77%|███████▋  | 23/30 [1:23:52<18:40, 160.13s/it, Mejor_Acc=0.6882, Trial=22]

Trial 22                | Actual Acc: 0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  80%|████████  | 24/30 [1:26:03<15:09, 151.51s/it, Mejor_Acc=0.6882, Trial=23]

Trial 23                | Actual Acc: 0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  83%|████████▎ | 25/30 [1:28:25<12:23, 148.60s/it, Mejor_Acc=0.6882, Trial=24]

Trial 24                | Actual Acc: 0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  87%|████████▋ | 26/30 [1:30:41<09:39, 144.78s/it, Mejor_Acc=0.6882, Trial=25]

Trial 25                | Actual Acc: 0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  90%|█████████ | 27/30 [1:32:52<07:02, 140.81s/it, Mejor_Acc=0.6882, Trial=26]

Trial 26                | Actual Acc: 0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  93%|█████████▎| 28/30 [1:35:03<04:35, 137.86s/it, Mejor_Acc=0.6882, Trial=27]

Trial 27                | Actual Acc: 0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  97%|█████████▋| 29/30 [1:37:06<02:13, 133.37s/it, Mejor_Acc=0.6882, Trial=28]

Trial 28                | Actual Acc: 0.6557 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost: 100%|██████████| 30/30 [1:39:09<00:00, 198.32s/it, Mejor_Acc=0.6882, Trial=29]

Trial 29                | Actual Acc: 0.6795 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6882 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
----------------------------------------------------------------------------------------------------

=== MEJOR COMBINACIÓN ENCONTRADA (XGBoost) ===
{'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2}
Mejor Accuracy: 0.6882

In [145]:
#mejores_params = {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.2,'random_state': 100,
 'n_jobs': -1}

In [146]:
clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
clf_anomalias_opt.fit(X_train, Y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=1.0, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=0.2, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=3, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=-1, num_parallel_tree=None, ...)

In [147]:

model_name=f'{nombre_algoritmo} ({DATOS})(todas las features)'
paquete_modelo={}

paquete_modelo['model_name']         = model_name
paquete_modelo['model']              = clf_anomalias_opt
paquete_modelo['parametros']         = mejores_params
paquete_modelo['lista_features']     = lista_features
paquete_modelo['N_features']         = len(paquete_modelo['lista_features'] )
paquete_modelo['N_features_unicas']  = len(get_lista_feature_sin_lag(paquete_modelo['lista_features'] ))
paquete_modelo['datos']              = DATOS
paquete_modelo['algoritmo']          = nombre_algoritmo

resultado,reporte_dict,Y_pred_probabilidades = evaluar_modelo(paquete_modelo,lista_features,X_test,Y_test_etiquetas,encoder_etiquetas)
print(f"=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===\n{model_name}")
print(paquete_modelo['classification_report_str'])

joblib.dump(paquete_modelo, f'{FOLDER_SALIDA}/models/{model_name}.joblib')

=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===
XGBoost (metricas_logs 3 puntos)(todas las features)
                                               precision    recall  f1-score   support

           access_token_auth_header_error_401       1.00      0.98      0.99        65
          access_token_authorization_form_401       0.48      0.60      0.53        65
         access_token_client_id_not_found_404       0.98      1.00      0.99        65
         access_token_client_secret_wrong_401       0.98      0.97      0.98        65
             access_token_form_urlencoded_400       0.65      0.60      0.62        65
          access_token_illegal_grant_type_400       1.00      1.00      1.00        65
access_token_missing_authorization_header_400       0.54      0.54      0.54        65
     authorization_code_client_id_missing_400       0.81      0.77      0.79        65
     authorization_code_invalid_client_id_404       0.79      0.85      0.81        65
      authorization_code_invalid_password_401       0.89      0.89      0.89        65
 authorization_code_missing_response_type_400       0.63      0.66      0.65        65
     authorization_code_response_not_code_400       0.66      0.63      0.65        65
       code_challenge_invalid_format_pkce_400       0.63      0.65      0.64        65
             code_challenge_too_long_pkce_400       0.66      0.63      0.65        65
            code_challenge_too_short_pkce_400       0.37      0.40      0.39        65
               code_verifier_missing_pkce_400       0.67      0.75      0.71        65
              code_verifier_too_long_pkce_400       0.30      0.31      0.30        65
             code_verifier_too_short_pkce_400       0.27      0.25      0.26        65
                  delete_client_404_no_client       1.00      1.00      1.00        65
                delete_service_404_no_service       0.81      0.78      0.80        65
                             delete_token_404       0.46      0.43      0.44        65
                      delete_user_404_no_user       0.13      0.14      0.13        65
                     get_client_404_no_client       1.00      1.00      1.00        65
                  get_client_page_400_no_page       1.00      1.00      1.00        65
                   get_service_404_no_service       0.49      0.57      0.52        65
                 get_service_page_400_no_page       0.81      0.86      0.84        65
                                get_token_404       0.52      0.57      0.54        65
                   get_token_page_400_no_page       0.59      0.71      0.64        65
                         get_user_404_no_user       0.50      0.54      0.52        65
                    get_user_page_400_no_page       0.56      0.65      0.60        65
       invalid_code_challenge_method_pkce_400       0.84      0.75      0.80        65
        invalid_code_verifier_format_PKCE_400       0.47      0.28      0.35        65
            register_client_400_clientProfile       1.00      0.98      0.99        65
               register_client_400_clientType       1.00      1.00      1.00        65
                  register_client_404_no_user       0.94      0.91      0.92        65
              register_service_400_service_id       0.94      0.78      0.86        65
            register_service_400_service_type       0.82      0.86      0.84        65
                 register_service_404_no_user       0.72      0.60      0.66        65
               register_user_400_email_exists       0.47      0.45      0.46        65
                register_user_400_no_password       0.52      0.63      0.57        65
          register_user_400_password_no_match       0.62      0.62      0.62        65
                register_user_400_user_exists       0.70      0.69      0.70        65
              update_client_400_clientProfile       1.00      0.98      0.99        65
                 update_client_400_clientType       1.00      0.98      0.99        65
                   update_client_404_clientId       0.53      0.62      0.57        65
                    update_client_404_ownerId       0.88      0.69      0.78        65
                update_password_400_not_match       0.77      0.85      0.81        65
           update_password_401_wrong_password       0.31      0.29      0.30        65
           update_password_404_user_not_found       0.21      0.18      0.20        65
                update_service_404_service_id       0.86      0.85      0.85        65
                   update_service_404_user_id       0.85      0.86      0.85        65
                      update_user_404_no_user       0.55      0.51      0.53        65
                 verification_failed_pkce_400       0.42      0.38      0.40        65

                                     accuracy                           0.69      3445
                                    macro avg       0.69      0.69      0.69      3445
                                 weighted avg       0.69      0.69      0.69      3445

['result/models/XGBoost (metricas_logs 3 puntos)(todas las features).joblib']

In [148]:
df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
print(f"Características con importancia cero: {num_cero}")

Características con importancia cero: 77

In [165]:
n_min = 54
n_max = len(importancias) - num_cero

lista_result = []

# --- VARIABLES PARA EL EARLY STOPPING ---
paciencia = 20
iteraciones_sin_mejora = 0
mejor_score_global = -1.0
mejor_paquete_modelo = None

for N_feat in range(n_min, n_max + 1):
    model_name = f'{nombre_algoritmo} ({DATOS})   N_feat={N_feat}'
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:N_feat]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(feature)

    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    
    # paquete_modelo['metrics'] = {
    #     'accuracy': accuracy,
    #     'macro_f1': macro_f1,
    #     'macro_precision': macro_precision,
    #     'macro_recall': macro_recall
    # }
    
    lista_result.append(paquete_modelo)

    # --- LÓGICA DE EARLY STOPPING ---
    score_actual = macro_f1 
    
    if score_actual > mejor_score_global:
        mejor_score_global = score_actual
        mejor_paquete_modelo = paquete_modelo.copy()
        iteraciones_sin_mejora = 0  # Reiniciamos contador si mejora
    else:
        iteraciones_sin_mejora += 1

    # --- IMPRESIÓN EN UNA SOLA LÍNEA ---
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Mejor Macro F1 = {mejor_score_global:.4f} | Iteraciones_sin_mejora = {iteraciones_sin_mejora}")

    # Comprobación de parada
    if iteraciones_sin_mejora >= paciencia:
        print(f"\n[!] Early Stopping activado: No ha habido mejoras en {paciencia} iteraciones consecutivas.")
        print(f"Deteniendo búsqueda. El mejor modelo se logró con {mejor_paquete_modelo['N_features_unicas']} características base.")
        break

Model = XGBoost (metricas_logs 3 puntos)   N_feat=54 Accuracy = 0.6888 | Macro F1 = 0.6878 | Macro Precision = 0.6901 | Macro Recall = 0.6888 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 3 puntos)   N_feat=55 Accuracy = 0.6891 | Macro F1 = 0.6878 | Macro Precision = 0.6906 | Macro Recall = 0.6891 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 3 puntos)   N_feat=56 Accuracy = 0.6894 | Macro F1 = 0.6876 | Macro Precision = 0.6913 | Macro Recall = 0.6894 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 3 puntos)   N_feat=57 Accuracy = 0.6871 | Macro F1 = 0.6852 | Macro Precision = 0.6892 | Macro Recall = 0.6871 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 3
Model = XGBoost (metricas_logs 3 puntos)   N_feat=58 Accuracy = 0.6833 | Macro F1 = 0.6818 | Macro Precision = 0.6847 | Macro Recall = 0.6833 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 4
Model = XGBoost (metricas_logs 3 puntos)   N_feat=59 Accuracy = 0.6862 | Macro F1 = 0.6849 | Macro Precision = 0.6878 | Macro Recall = 0.6862 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 5
Model = XGBoost (metricas_logs 3 puntos)   N_feat=60 Accuracy = 0.6868 | Macro F1 = 0.6856 | Macro Precision = 0.6885 | Macro Recall = 0.6868 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 6
Model = XGBoost (metricas_logs 3 puntos)   N_feat=61 Accuracy = 0.6877 | Macro F1 = 0.6868 | Macro Precision = 0.6905 | Macro Recall = 0.6877 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 7
Model = XGBoost (metricas_logs 3 puntos)   N_feat=62 Accuracy = 0.6868 | Macro F1 = 0.6861 | Macro Precision = 0.6897 | Macro Recall = 0.6868 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 8
Model = XGBoost (metricas_logs 3 puntos)   N_feat=63 Accuracy = 0.6880 | Macro F1 = 0.6864 | Macro Precision = 0.6890 | Macro Recall = 0.6880 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 9
Model = XGBoost (metricas_logs 3 puntos)   N_feat=64 Accuracy = 0.6851 | Macro F1 = 0.6839 | Macro Precision = 0.6869 | Macro Recall = 0.6851 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 10
Model = XGBoost (metricas_logs 3 puntos)   N_feat=65 Accuracy = 0.6859 | Macro F1 = 0.6853 | Macro Precision = 0.6888 | Macro Recall = 0.6859 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 11
Model = XGBoost (metricas_logs 3 puntos)   N_feat=66 Accuracy = 0.6848 | Macro F1 = 0.6837 | Macro Precision = 0.6864 | Macro Recall = 0.6848 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 12
Model = XGBoost (metricas_logs 3 puntos)   N_feat=67 Accuracy = 0.6862 | Macro F1 = 0.6859 | Macro Precision = 0.6897 | Macro Recall = 0.6862 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 13
Model = XGBoost (metricas_logs 3 puntos)   N_feat=68 Accuracy = 0.6862 | Macro F1 = 0.6852 | Macro Precision = 0.6876 | Macro Recall = 0.6862 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 14
Model = XGBoost (metricas_logs 3 puntos)   N_feat=69 Accuracy = 0.6839 | Macro F1 = 0.6831 | Macro Precision = 0.6865 | Macro Recall = 0.6839 | Mejor Macro F1 = 0.6878 | Iteraciones_sin_mejora = 15
Model = XGBoost (metricas_logs 3 puntos)   N_feat=70 Accuracy = 0.6894 | Macro F1 = 0.6890 | Macro Precision = 0.6921 | Macro Recall = 0.6894 | Mejor Macro F1 = 0.6890 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 3 puntos)   N_feat=71 Accuracy = 0.6856 | Macro F1 = 0.6854 | Macro Precision = 0.6889 | Macro Recall = 0.6856 | Mejor Macro F1 = 0.6890 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 3 puntos)   N_feat=72 Accuracy = 0.6885 | Macro F1 = 0.6877 | Macro Precision = 0.6904 | Macro Recall = 0.6885 | Mejor Macro F1 = 0.6890 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 3 puntos)   N_feat=73 Accuracy = 0.6900 | Macro F1 = 0.6891 | Macro Precision = 0.6918 | Macro Recall = 0.6900 | Mejor Macro F1 = 0.6891 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 3 puntos)   N_feat=74 Accuracy = 0.6865 | Macro F1 = 0.6855 | Macro Precision = 0.6885 | Macro Recall = 0.6865 | Mejor Macro F1 = 0.6891 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 3 puntos)   N_feat=75 Accuracy = 0.6920 | Macro F1 = 0.6912 | Macro Precision = 0.6937 | Macro Recall = 0.6920 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 3 puntos)   N_feat=76 Accuracy = 0.6877 | Macro F1 = 0.6867 | Macro Precision = 0.6899 | Macro Recall = 0.6877 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 3 puntos)   N_feat=77 Accuracy = 0.6897 | Macro F1 = 0.6892 | Macro Precision = 0.6929 | Macro Recall = 0.6897 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 3 puntos)   N_feat=78 Accuracy = 0.6894 | Macro F1 = 0.6885 | Macro Precision = 0.6916 | Macro Recall = 0.6894 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 3
Model = XGBoost (metricas_logs 3 puntos)   N_feat=79 Accuracy = 0.6880 | Macro F1 = 0.6881 | Macro Precision = 0.6926 | Macro Recall = 0.6880 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 4
Model = XGBoost (metricas_logs 3 puntos)   N_feat=80 Accuracy = 0.6882 | Macro F1 = 0.6876 | Macro Precision = 0.6913 | Macro Recall = 0.6882 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 5
Model = XGBoost (metricas_logs 3 puntos)   N_feat=81 Accuracy = 0.6868 | Macro F1 = 0.6860 | Macro Precision = 0.6900 | Macro Recall = 0.6868 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 6
Model = XGBoost (metricas_logs 3 puntos)   N_feat=82 Accuracy = 0.6903 | Macro F1 = 0.6898 | Macro Precision = 0.6942 | Macro Recall = 0.6903 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 7
Model = XGBoost (metricas_logs 3 puntos)   N_feat=83 Accuracy = 0.6911 | Macro F1 = 0.6900 | Macro Precision = 0.6935 | Macro Recall = 0.6911 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 8
Model = XGBoost (metricas_logs 3 puntos)   N_feat=84 Accuracy = 0.6900 | Macro F1 = 0.6898 | Macro Precision = 0.6935 | Macro Recall = 0.6900 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 9
Model = XGBoost (metricas_logs 3 puntos)   N_feat=85 Accuracy = 0.6885 | Macro F1 = 0.6882 | Macro Precision = 0.6916 | Macro Recall = 0.6885 | Mejor Macro F1 = 0.6912 | Iteraciones_sin_mejora = 10
Model = XGBoost (metricas_logs 3 puntos)   N_feat=86 Accuracy = 0.6917 | Macro F1 = 0.6914 | Macro Precision = 0.6952 | Macro Recall = 0.6917 | Mejor Macro F1 = 0.6914 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 3 puntos)   N_feat=87 Accuracy = 0.6903 | Macro F1 = 0.6902 | Macro Precision = 0.6943 | Macro Recall = 0.6903 | Mejor Macro F1 = 0.6914 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 3 puntos)   N_feat=88 Accuracy = 0.6917 | Macro F1 = 0.6916 | Macro Precision = 0.6955 | Macro Recall = 0.6917 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 3 puntos)   N_feat=89 Accuracy = 0.6911 | Macro F1 = 0.6910 | Macro Precision = 0.6957 | Macro Recall = 0.6911 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 3 puntos)   N_feat=90 Accuracy = 0.6914 | Macro F1 = 0.6911 | Macro Precision = 0.6949 | Macro Recall = 0.6914 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 3 puntos)   N_feat=91 Accuracy = 0.6874 | Macro F1 = 0.6873 | Macro Precision = 0.6915 | Macro Recall = 0.6874 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 3
Model = XGBoost (metricas_logs 3 puntos)   N_feat=92 Accuracy = 0.6917 | Macro F1 = 0.6905 | Macro Precision = 0.6934 | Macro Recall = 0.6917 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 4
Model = XGBoost (metricas_logs 3 puntos)   N_feat=93 Accuracy = 0.6885 | Macro F1 = 0.6879 | Macro Precision = 0.6919 | Macro Recall = 0.6885 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 5
Model = XGBoost (metricas_logs 3 puntos)   N_feat=94 Accuracy = 0.6926 | Macro F1 = 0.6910 | Macro Precision = 0.6935 | Macro Recall = 0.6926 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 6
Model = XGBoost (metricas_logs 3 puntos)   N_feat=95 Accuracy = 0.6929 | Macro F1 = 0.6913 | Macro Precision = 0.6943 | Macro Recall = 0.6929 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 7
Model = XGBoost (metricas_logs 3 puntos)   N_feat=96 Accuracy = 0.6911 | Macro F1 = 0.6901 | Macro Precision = 0.6931 | Macro Recall = 0.6911 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 8
Model = XGBoost (metricas_logs 3 puntos)   N_feat=97 Accuracy = 0.6877 | Macro F1 = 0.6863 | Macro Precision = 0.6902 | Macro Recall = 0.6877 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 9
Model = XGBoost (metricas_logs 3 puntos)   N_feat=98 Accuracy = 0.6932 | Macro F1 = 0.6914 | Macro Precision = 0.6942 | Macro Recall = 0.6932 | Mejor Macro F1 = 0.6916 | Iteraciones_sin_mejora = 10
Model = XGBoost (metricas_logs 3 puntos)   N_feat=99 Accuracy = 0.6952 | Macro F1 = 0.6945 | Macro Precision = 0.6981 | Macro Recall = 0.6952 | Mejor Macro F1 = 0.6945 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 3 puntos)   N_feat=100 Accuracy = 0.6911 | Macro F1 = 0.6904 | Macro Precision = 0.6943 | Macro Recall = 0.6911 | Mejor Macro F1 = 0.6945 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 3 puntos)   N_feat=101 Accuracy = 0.6926 | Macro F1 = 0.6910 | Macro Precision = 0.6932 | Macro Recall = 0.6926 | Mejor Macro F1 = 0.6945 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 3 puntos)   N_feat=102 Accuracy = 0.6978 | Macro F1 = 0.6969 | Macro Precision = 0.6999 | Macro Recall = 0.6978 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 3 puntos)   N_feat=103 Accuracy = 0.6946 | Macro F1 = 0.6940 | Macro Precision = 0.6970 | Macro Recall = 0.6946 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 3 puntos)   N_feat=104 Accuracy = 0.6932 | Macro F1 = 0.6918 | Macro Precision = 0.6948 | Macro Recall = 0.6932 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 3 puntos)   N_feat=105 Accuracy = 0.6914 | Macro F1 = 0.6904 | Macro Precision = 0.6934 | Macro Recall = 0.6914 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 3
Model = XGBoost (metricas_logs 3 puntos)   N_feat=106 Accuracy = 0.6923 | Macro F1 = 0.6914 | Macro Precision = 0.6943 | Macro Recall = 0.6923 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 4
Model = XGBoost (metricas_logs 3 puntos)   N_feat=107 Accuracy = 0.6946 | Macro F1 = 0.6931 | Macro Precision = 0.6960 | Macro Recall = 0.6946 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 5
Model = XGBoost (metricas_logs 3 puntos)   N_feat=108 Accuracy = 0.6903 | Macro F1 = 0.6890 | Macro Precision = 0.6919 | Macro Recall = 0.6903 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 6
Model = XGBoost (metricas_logs 3 puntos)   N_feat=109 Accuracy = 0.6900 | Macro F1 = 0.6892 | Macro Precision = 0.6931 | Macro Recall = 0.6900 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 7
Model = XGBoost (metricas_logs 3 puntos)   N_feat=110 Accuracy = 0.6929 | Macro F1 = 0.6915 | Macro Precision = 0.6944 | Macro Recall = 0.6929 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 8
Model = XGBoost (metricas_logs 3 puntos)   N_feat=111 Accuracy = 0.6923 | Macro F1 = 0.6916 | Macro Precision = 0.6955 | Macro Recall = 0.6923 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 9
Model = XGBoost (metricas_logs 3 puntos)   N_feat=112 Accuracy = 0.6894 | Macro F1 = 0.6879 | Macro Precision = 0.6905 | Macro Recall = 0.6894 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 10
Model = XGBoost (metricas_logs 3 puntos)   N_feat=113 Accuracy = 0.6868 | Macro F1 = 0.6852 | Macro Precision = 0.6876 | Macro Recall = 0.6868 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 11
Model = XGBoost (metricas_logs 3 puntos)   N_feat=114 Accuracy = 0.6903 | Macro F1 = 0.6884 | Macro Precision = 0.6902 | Macro Recall = 0.6903 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 12
Model = XGBoost (metricas_logs 3 puntos)   N_feat=115 Accuracy = 0.6891 | Macro F1 = 0.6878 | Macro Precision = 0.6909 | Macro Recall = 0.6891 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 13
Model = XGBoost (metricas_logs 3 puntos)   N_feat=116 Accuracy = 0.6900 | Macro F1 = 0.6887 | Macro Precision = 0.6918 | Macro Recall = 0.6900 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 14
Model = XGBoost (metricas_logs 3 puntos)   N_feat=117 Accuracy = 0.6888 | Macro F1 = 0.6872 | Macro Precision = 0.6895 | Macro Recall = 0.6888 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 15
Model = XGBoost (metricas_logs 3 puntos)   N_feat=118 Accuracy = 0.6900 | Macro F1 = 0.6883 | Macro Precision = 0.6906 | Macro Recall = 0.6900 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 16
Model = XGBoost (metricas_logs 3 puntos)   N_feat=119 Accuracy = 0.6880 | Macro F1 = 0.6871 | Macro Precision = 0.6920 | Macro Recall = 0.6880 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 17
Model = XGBoost (metricas_logs 3 puntos)   N_feat=120 Accuracy = 0.6906 | Macro F1 = 0.6893 | Macro Precision = 0.6923 | Macro Recall = 0.6906 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 18
Model = XGBoost (metricas_logs 3 puntos)   N_feat=121 Accuracy = 0.6845 | Macro F1 = 0.6831 | Macro Precision = 0.6858 | Macro Recall = 0.6845 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 19
Model = XGBoost (metricas_logs 3 puntos)   N_feat=122 Accuracy = 0.6880 | Macro F1 = 0.6863 | Macro Precision = 0.6885 | Macro Recall = 0.6880 | Mejor Macro F1 = 0.6969 | Iteraciones_sin_mejora = 20

[!] Early Stopping activado: No ha habido mejoras en 20 iteraciones consecutivas.
Deteniendo búsqueda. El mejor modelo se logró con 102 características base.

In [166]:
mejor_paquete_modelo['model_name']

'XGBoost (metricas_logs 3 puntos)   N_feat=102'

In [167]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

['result/models/XGBoost (metricas_logs 3 puntos)   N_feat=102.joblib']

In [168]:
paquete_modelo = mejor_paquete_modelo.copy()

mejor_macro_f1_global    = paquete_modelo['resultado']['f1']
mejor_features_global    = paquete_modelo['lista_features'].copy()
pasos_sin_mejora         = 0
limite_puntos_sin_mejora = paciencia + 5

print(f"Iniciando eliminación recursiva desde {paquete_modelo['N_features_unicas']} características.\n")

while paquete_modelo['N_features_unicas'] > 1 and pasos_sin_mejora < limite_puntos_sin_mejora:
    N_feat = paquete_modelo['N_features_unicas']
    
    # Extraer importancias y características actuales
    importancias_raw = paquete_modelo['model'].feature_importances_
    features_raw = paquete_modelo['lista_features']
    
    df_importancias_agrupada, _, num_cero = obtener_importancias_agrupadas(importancias_raw, features_raw)

    # Seleccionar características para el siguiente paso
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:(N_feat-1)]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(f'{feature}')
            
    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    model_name = f'{nombre_algoritmo} (metricas_log) N_feat={N_feat-1}'
    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
   
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    

    
    if macro_f1 >= mejor_macro_f1_global:
        mejor_macro_f1_global = macro_f1
        mejor_features_global = paquete_modelo['lista_features'].copy()
        pasos_sin_mejora = 0  
        mejor_paquete_modelo = paquete_modelo.copy()
    else:
        pasos_sin_mejora += 1  
        
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Sin mejora: {pasos_sin_mejora}")
    del X_train_sub, X_test_sub, importancias_raw, df_importancias_agrupada
    gc.collect()

print(f"\n¡Proceso finalizado!")
print(f"Mejor Macro F1 alcanzado: {mejor_macro_f1_global:.4f}")
print(f"Número óptimo de características base: {len(mejor_features_global)}")

Iniciando eliminación recursiva desde 102 características.

Model = XGBoost (metricas_log) N_feat=101        Accuracy = 0.6888 | Macro F1 = 0.6875 | Macro Precision = 0.6893 | Macro Recall = 0.6888 | Sin mejora: 1
Model = XGBoost (metricas_log) N_feat=100        Accuracy = 0.6348 | Macro F1 = 0.6316 | Macro Precision = 0.6329 | Macro Recall = 0.6348 | Sin mejora: 2
Model = XGBoost (metricas_log) N_feat=99         Accuracy = 0.6377 | Macro F1 = 0.6346 | Macro Precision = 0.6367 | Macro Recall = 0.6377 | Sin mejora: 3
Model = XGBoost (metricas_log) N_feat=98         Accuracy = 0.6313 | Macro F1 = 0.6273 | Macro Precision = 0.6281 | Macro Recall = 0.6313 | Sin mejora: 4
Model = XGBoost (metricas_log) N_feat=97         Accuracy = 0.6343 | Macro F1 = 0.6310 | Macro Precision = 0.6324 | Macro Recall = 0.6343 | Sin mejora: 5
Model = XGBoost (metricas_log) N_feat=96         Accuracy = 0.6308 | Macro F1 = 0.6266 | Macro Precision = 0.6270 | Macro Recall = 0.6308 | Sin mejora: 6
Model = XGBoost (metricas_log) N_feat=95         Accuracy = 0.6354 | Macro F1 = 0.6315 | Macro Precision = 0.6319 | Macro Recall = 0.6354 | Sin mejora: 7
Model = XGBoost (metricas_log) N_feat=94         Accuracy = 0.6305 | Macro F1 = 0.6266 | Macro Precision = 0.6277 | Macro Recall = 0.6305 | Sin mejora: 8
Model = XGBoost (metricas_log) N_feat=93         Accuracy = 0.6258 | Macro F1 = 0.6220 | Macro Precision = 0.6230 | Macro Recall = 0.6258 | Sin mejora: 9
Model = XGBoost (metricas_log) N_feat=92         Accuracy = 0.6215 | Macro F1 = 0.6175 | Macro Precision = 0.6187 | Macro Recall = 0.6215 | Sin mejora: 10
Model = XGBoost (metricas_log) N_feat=91         Accuracy = 0.6212 | Macro F1 = 0.6176 | Macro Precision = 0.6197 | Macro Recall = 0.6212 | Sin mejora: 11
Model = XGBoost (metricas_log) N_feat=90         Accuracy = 0.6212 | Macro F1 = 0.6176 | Macro Precision = 0.6185 | Macro Recall = 0.6212 | Sin mejora: 12
Model = XGBoost (metricas_log) N_feat=89         Accuracy = 0.6209 | Macro F1 = 0.6175 | Macro Precision = 0.6194 | Macro Recall = 0.6209 | Sin mejora: 13
Model = XGBoost (metricas_log) N_feat=88         Accuracy = 0.6267 | Macro F1 = 0.6231 | Macro Precision = 0.6254 | Macro Recall = 0.6267 | Sin mejora: 14
Model = XGBoost (metricas_log) N_feat=87         Accuracy = 0.5983 | Macro F1 = 0.5940 | Macro Precision = 0.5941 | Macro Recall = 0.5983 | Sin mejora: 15
Model = XGBoost (metricas_log) N_feat=86         Accuracy = 0.5977 | Macro F1 = 0.5933 | Macro Precision = 0.5939 | Macro Recall = 0.5977 | Sin mejora: 16
Model = XGBoost (metricas_log) N_feat=85         Accuracy = 0.5951 | Macro F1 = 0.5906 | Macro Precision = 0.5912 | Macro Recall = 0.5951 | Sin mejora: 17
Model = XGBoost (metricas_log) N_feat=84         Accuracy = 0.6029 | Macro F1 = 0.5976 | Macro Precision = 0.5967 | Macro Recall = 0.6029 | Sin mejora: 18
Model = XGBoost (metricas_log) N_feat=83         Accuracy = 0.5936 | Macro F1 = 0.5889 | Macro Precision = 0.5887 | Macro Recall = 0.5936 | Sin mejora: 19
Model = XGBoost (metricas_log) N_feat=82         Accuracy = 0.5797 | Macro F1 = 0.5733 | Macro Precision = 0.5720 | Macro Recall = 0.5797 | Sin mejora: 20
Model = XGBoost (metricas_log) N_feat=81         Accuracy = 0.5791 | Macro F1 = 0.5725 | Macro Precision = 0.5718 | Macro Recall = 0.5791 | Sin mejora: 21
Model = XGBoost (metricas_log) N_feat=80         Accuracy = 0.5800 | Macro F1 = 0.5742 | Macro Precision = 0.5733 | Macro Recall = 0.5800 | Sin mejora: 22
Model = XGBoost (metricas_log) N_feat=79         Accuracy = 0.5794 | Macro F1 = 0.5741 | Macro Precision = 0.5740 | Macro Recall = 0.5794 | Sin mejora: 23
Model = XGBoost (metricas_log) N_feat=78         Accuracy = 0.5806 | Macro F1 = 0.5752 | Macro Precision = 0.5749 | Macro Recall = 0.5806 | Sin mejora: 24
Model = XGBoost (metricas_log) N_feat=77         Accuracy = 0.5814 | Macro F1 = 0.5760 | Macro Precision = 0.5761 | Macro Recall = 0.5814 | Sin mejora: 25

¡Proceso finalizado!
Mejor Macro F1 alcanzado: 0.6969
Número óptimo de características base: 306

In [169]:
mejor_paquete_modelo['model_name']

'XGBoost (metricas_logs 3 puntos)   N_feat=102'

In [170]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

['result/models/XGBoost (metricas_logs 3 puntos)   N_feat=102.joblib']

### <span style="color:#2ca02c">4.5.2. Clasificador XGBoost (1 punto de 3 intervalos) con metricas_logs</span>

In [171]:
N_puntos = 1
DATOS    = 'metricas_logs 1 punto suma'

In [172]:
lista_features = lista_feature_names_1punto_sum

X_train = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_train,lista_feature_sel=lista_features)
print(X_train.shape)
X_test  = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_features)
print(X_test.shape)
X_val   = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_val ,lista_feature_sel=lista_features)
print(X_val.shape)

(10282, 331)
(3445, 331)
(3445, 331)

In [173]:
params_grid= {
    'n_estimators': [ 200, 300, 400],
    'learning_rate': [0.05, 0.01, 0.05],
    'max_depth': [6, 8, 10],
    'subsample': [0.7, 0.8,0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 2,  3],
    'gamma': [0.0, 0.1, 0.2]
}

In [174]:
optuna.logging.set_verbosity(optuna.logging.WARNING)
N_trials = 30

# Barra de progreso global
pbar = tqdm(total=N_trials, desc=f"Optimizando {nombre_algoritmo}")

# Crear el estudio

study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=SEED) 
)

# Enlazamos DIRECTAMENTE 'objective_universal' en el partial (evita usar alias antiguos)
objective_func = partial(
    objective_universal, 
    config=params_grid,
    clasificador_cls=ALGORITMO_CLASIFICADOR,
    X_train=X_train,
    X_test=X_test,
    Y_train_encoded=Y_train_encoded,
    Y_test_encoded=Y_test_encoded
)

# Ejecutar la optimización
print(f"=== INICIANDO OPTIMIZACIÓN DE {nombre_algoritmo} CON OPTUNA ===")
try:
    study.optimize(objective_func, n_trials=N_trials, callbacks=[print_callback], n_jobs=1)
finally:
    pbar.close()

# Resultados finales
print(f"\n=== MEJOR COMBINACIÓN ENCONTRADA ({nombre_algoritmo}) ===")
print(study.best_params)
print(f"Mejor Accuracy: {study.best_value:.4f}")

# Reconstruir el modelo final con los mejores parámetros óptimos
mejores_params = study.best_params.copy()
mejores_params['random_state'] = SEED
if 'n_jobs' in ALGORITMO_CLASIFICADOR().get_params():
    mejores_params['n_jobs'] = -1

Optimizando XGBoost:   0%|          | 0/30 [00:00<?, ?it/s]

=== INICIANDO OPTIMIZACIÓN DE XGBoost CON OPTUNA ===

Optimizando XGBoost:   3%|▎         | 1/30 [00:45<21:46, 45.04s/it, Mejor_Acc=0.6589, Trial=0]

Trial  0                | Actual Acc: 0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:   7%|▋         | 2/30 [01:44<24:53, 53.34s/it, Mejor_Acc=0.6589, Trial=1]

Trial  1                | Actual Acc: 0.6517 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  10%|█         | 3/30 [02:23<21:02, 46.76s/it, Mejor_Acc=0.6589, Trial=2]

Trial  2                | Actual Acc: 0.6372 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 8, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  13%|█▎        | 4/30 [03:30<23:44, 54.77s/it, Mejor_Acc=0.6589, Trial=3]

Trial  3                | Actual Acc: 0.6392 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  17%|█▋        | 5/30 [04:35<24:27, 58.72s/it, Mejor_Acc=0.6589, Trial=4]

Trial  4                | Actual Acc: 0.6569 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  20%|██        | 6/30 [05:26<22:26, 56.09s/it, Mejor_Acc=0.6589, Trial=5]

Trial  5                | Actual Acc: 0.6453 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  23%|██▎       | 7/30 [06:26<21:55, 57.19s/it, Mejor_Acc=0.6589, Trial=6]

Trial  6                | Actual Acc: 0.6589 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  27%|██▋       | 8/30 [07:58<25:02, 68.29s/it, Mejor_Acc=0.6589, Trial=7]

Trial  7                | Actual Acc: 0.6418 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.01, 'max_depth': 10, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  30%|███       | 9/30 [08:59<23:09, 66.17s/it, Mejor_Acc=0.6589, Trial=8]

Trial  8                | Actual Acc: 0.6430 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 10, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  33%|███▎      | 10/30 [09:34<18:47, 56.39s/it, Mejor_Acc=0.6589, Trial=9]

Trial  9                | Actual Acc: 0.6531 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 2, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  37%|███▋      | 11/30 [10:22<17:02, 53.80s/it, Mejor_Acc=0.6589, Trial=10]

Trial 10                | Actual Acc: 0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  40%|████      | 12/30 [11:20<16:31, 55.06s/it, Mejor_Acc=0.6589, Trial=11]

Trial 11                | Actual Acc: 0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  43%|████▎     | 13/30 [12:38<17:36, 62.15s/it, Mejor_Acc=0.6589, Trial=12]

Trial 12                | Actual Acc: 0.6540 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  47%|████▋     | 14/30 [13:37<16:16, 61.02s/it, Mejor_Acc=0.6589, Trial=13]

Trial 13                | Actual Acc: 0.6525 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.0}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6589 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  50%|█████     | 15/30 [14:45<15:48, 63.20s/it, Mejor_Acc=0.6610, Trial=14]

Trial 14                | Actual Acc: 0.6610 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6610 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  53%|█████▎    | 16/30 [15:36<13:55, 59.69s/it, Mejor_Acc=0.6612, Trial=15]

Trial 15                | Actual Acc: 0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  57%|█████▋    | 17/30 [16:27<12:21, 57.06s/it, Mejor_Acc=0.6612, Trial=16]

Trial 16                | Actual Acc: 0.6546 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  60%|██████    | 18/30 [17:18<11:01, 55.17s/it, Mejor_Acc=0.6612, Trial=17]

Trial 17                | Actual Acc: 0.6557 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  63%|██████▎   | 19/30 [18:09<09:52, 53.87s/it, Mejor_Acc=0.6612, Trial=18]

Trial 18                | Actual Acc: 0.6610 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  67%|██████▋   | 20/30 [19:00<08:50, 53.08s/it, Mejor_Acc=0.6612, Trial=19]

Trial 19                | Actual Acc: 0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  70%|███████   | 21/30 [19:51<07:50, 52.33s/it, Mejor_Acc=0.6612, Trial=20]

Trial 20                | Actual Acc: 0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  73%|███████▎  | 22/30 [20:41<06:52, 51.57s/it, Mejor_Acc=0.6612, Trial=21]

Trial 21                | Actual Acc: 0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  77%|███████▋  | 23/30 [21:31<05:59, 51.32s/it, Mejor_Acc=0.6612, Trial=22]

Trial 22                | Actual Acc: 0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  80%|████████  | 24/30 [22:22<05:06, 51.09s/it, Mejor_Acc=0.6612, Trial=23]

Trial 23                | Actual Acc: 0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  83%|████████▎ | 25/30 [23:12<04:14, 50.89s/it, Mejor_Acc=0.6612, Trial=24]

Trial 24                | Actual Acc: 0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  87%|████████▋ | 26/30 [24:25<03:49, 57.35s/it, Mejor_Acc=0.6612, Trial=25]

Trial 25                | Actual Acc: 0.6583 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.2}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6612 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 2, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  90%|█████████ | 27/30 [25:34<03:02, 60.83s/it, Mejor_Acc=0.6639, Trial=26]

Trial 26                | Actual Acc: 0.6639 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6639 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  93%|█████████▎| 28/30 [26:41<02:05, 62.87s/it, Mejor_Acc=0.6639, Trial=27]

Trial 27                | Actual Acc: 0.6639 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6639 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost:  97%|█████████▋| 29/30 [27:33<00:59, 59.50s/it, Mejor_Acc=0.6639, Trial=28]

Trial 28                | Actual Acc: 0.6639 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6639 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

Optimizando XGBoost: 100%|██████████| 30/30 [28:39<00:00, 57.30s/it, Mejor_Acc=0.6662, Trial=29]

Trial 29                | Actual Acc: 0.6662 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6662 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
----------------------------------------------------------------------------------------------------

=== MEJOR COMBINACIÓN ENCONTRADA (XGBoost) ===
{'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'gamma': 0.1}
Mejor Accuracy: 0.6662

In [175]:
clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
clf_anomalias_opt.fit(X_train, Y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=1.0, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=0.1, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=3, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=400,
              n_jobs=-1, num_parallel_tree=None, ...)

In [176]:
model_name=f'{nombre_algoritmo} ({DATOS})(todas las features)'
paquete_modelo={}

paquete_modelo['model_name']         = model_name
paquete_modelo['model']              = clf_anomalias_opt
paquete_modelo['parametros']         = mejores_params
paquete_modelo['lista_features']     = lista_features
paquete_modelo['N_features']         = len(paquete_modelo['lista_features'] )
paquete_modelo['N_features_unicas']  = len(get_lista_feature_sin_lag(paquete_modelo['lista_features'] ))
paquete_modelo['datos']              = DATOS
paquete_modelo['algoritmo']          = nombre_algoritmo

resultado,reporte_dict,Y_pred_probabilidades = evaluar_modelo(paquete_modelo,lista_features,X_test,Y_test_etiquetas,encoder_etiquetas)
print(f"=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===\n{model_name}")
print(paquete_modelo['classification_report_str'])

joblib.dump(paquete_modelo, f'{FOLDER_SALIDA}/models/{model_name}.joblib')

=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===
XGBoost (metricas_logs 1 punto suma)(todas las features)
                                               precision    recall  f1-score   support

           access_token_auth_header_error_401       0.94      0.97      0.95        65
          access_token_authorization_form_401       0.47      0.54      0.50        65
         access_token_client_id_not_found_404       0.98      1.00      0.99        65
         access_token_client_secret_wrong_401       0.98      0.97      0.98        65
             access_token_form_urlencoded_400       0.70      0.66      0.68        65
          access_token_illegal_grant_type_400       1.00      1.00      1.00        65
access_token_missing_authorization_header_400       0.49      0.54      0.51        65
     authorization_code_client_id_missing_400       0.86      0.83      0.84        65
     authorization_code_invalid_client_id_404       0.69      0.77      0.73        65
      authorization_code_invalid_password_401       0.95      0.80      0.87        65
 authorization_code_missing_response_type_400       0.64      0.72      0.68        65
     authorization_code_response_not_code_400       0.73      0.72      0.73        65
       code_challenge_invalid_format_pkce_400       0.62      0.68      0.65        65
             code_challenge_too_long_pkce_400       0.57      0.51      0.54        65
            code_challenge_too_short_pkce_400       0.41      0.43      0.42        65
               code_verifier_missing_pkce_400       0.54      0.65      0.59        65
              code_verifier_too_long_pkce_400       0.18      0.17      0.18        65
             code_verifier_too_short_pkce_400       0.26      0.18      0.22        65
                  delete_client_404_no_client       1.00      1.00      1.00        65
                delete_service_404_no_service       0.80      0.85      0.82        65
                             delete_token_404       0.47      0.51      0.49        65
                      delete_user_404_no_user       0.24      0.20      0.22        65
                     get_client_404_no_client       1.00      0.98      0.99        65
                  get_client_page_400_no_page       1.00      1.00      1.00        65
                   get_service_404_no_service       0.37      0.54      0.44        65
                 get_service_page_400_no_page       0.91      0.91      0.91        65
                                get_token_404       0.33      0.23      0.27        65
                   get_token_page_400_no_page       0.54      0.69      0.60        65
                         get_user_404_no_user       0.30      0.26      0.28        65
                    get_user_page_400_no_page       0.51      0.62      0.56        65
       invalid_code_challenge_method_pkce_400       0.82      0.85      0.83        65
        invalid_code_verifier_format_PKCE_400       0.26      0.18      0.22        65
            register_client_400_clientProfile       0.91      0.91      0.91        65
               register_client_400_clientType       0.90      0.88      0.89        65
                  register_client_404_no_user       0.86      0.86      0.86        65
              register_service_400_service_id       0.95      0.82      0.88        65
            register_service_400_service_type       0.77      0.89      0.83        65
                 register_service_404_no_user       0.70      0.80      0.75        65
               register_user_400_email_exists       0.69      0.57      0.62        65
                register_user_400_no_password       0.55      0.71      0.62        65
          register_user_400_password_no_match       0.72      0.60      0.66        65
                register_user_400_user_exists       0.60      0.69      0.64        65
              update_client_400_clientProfile       1.00      0.97      0.98        65
                 update_client_400_clientType       0.98      1.00      0.99        65
                   update_client_404_clientId       0.38      0.49      0.43        65
                    update_client_404_ownerId       0.93      0.63      0.75        65
                update_password_400_not_match       0.66      0.68      0.67        65
           update_password_401_wrong_password       0.30      0.28      0.29        65
           update_password_404_user_not_found       0.29      0.20      0.24        65
                update_service_404_service_id       0.87      0.72      0.79        65
                   update_service_404_user_id       0.79      0.82      0.80        65
                      update_user_404_no_user       0.57      0.60      0.58        65
                 verification_failed_pkce_400       0.26      0.25      0.25        65

                                     accuracy                           0.67      3445
                                    macro avg       0.67      0.67      0.66      3445
                                 weighted avg       0.67      0.67      0.66      3445

['result/models/XGBoost (metricas_logs 1 punto suma)(todas las features).joblib']

In [177]:
df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
print(f"Características con importancia cero: {num_cero}")

Características con importancia cero: 69

In [180]:
n_min = 149
n_max = len(importancias) - num_cero


# --- VARIABLES PARA EL EARLY STOPPING ---
paciencia = 15
iteraciones_sin_mejora = 0
mejor_score_global = -1.0
mejor_paquete_modelo = None

for N_feat in range(n_min, n_max + 1):
    model_name = f'{nombre_algoritmo} ({DATOS})   N_feat={N_feat}'
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:N_feat]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(feature)

    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    


    # --- LÓGICA DE EARLY STOPPING ---
    score_actual = macro_f1 
    
    if score_actual > mejor_score_global:
        mejor_score_global = score_actual
        mejor_paquete_modelo = paquete_modelo.copy()
        iteraciones_sin_mejora = 0  # Reiniciamos contador si mejora
    else:
        iteraciones_sin_mejora += 1

    # --- IMPRESIÓN EN UNA SOLA LÍNEA ---
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Mejor Macro F1 = {mejor_score_global:.4f} | Iteraciones_sin_mejora = {iteraciones_sin_mejora}")
    del X_train_sub, X_test_sub
    gc.collect()
    
    # Comprobación de parada
    if iteraciones_sin_mejora >= paciencia:
        print(f"\n[!] Early Stopping activado: No ha habido mejoras en {paciencia} iteraciones consecutivas.")
        print(f"Deteniendo búsqueda. El mejor modelo se logró con {mejor_paquete_modelo['N_features_unicas']} características base.")
        break

Model = XGBoost (metricas_logs 1 punto suma)   N_feat=149 Accuracy = 0.6543 | Macro F1 = 0.6509 | Macro Precision = 0.6530 | Macro Recall = 0.6543 | Mejor Macro F1 = 0.6509 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=150 Accuracy = 0.6615 | Macro F1 = 0.6586 | Macro Precision = 0.6613 | Macro Recall = 0.6615 | Mejor Macro F1 = 0.6586 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=151 Accuracy = 0.6604 | Macro F1 = 0.6571 | Macro Precision = 0.6594 | Macro Recall = 0.6604 | Mejor Macro F1 = 0.6586 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=152 Accuracy = 0.6601 | Macro F1 = 0.6567 | Macro Precision = 0.6592 | Macro Recall = 0.6601 | Mejor Macro F1 = 0.6586 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=153 Accuracy = 0.6592 | Macro F1 = 0.6562 | Macro Precision = 0.6586 | Macro Recall = 0.6592 | Mejor Macro F1 = 0.6586 | Iteraciones_sin_mejora = 3
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=154 Accuracy = 0.6621 | Macro F1 = 0.6588 | Macro Precision = 0.6612 | Macro Recall = 0.6621 | Mejor Macro F1 = 0.6588 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=155 Accuracy = 0.6604 | Macro F1 = 0.6576 | Macro Precision = 0.6604 | Macro Recall = 0.6604 | Mejor Macro F1 = 0.6588 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=156 Accuracy = 0.6607 | Macro F1 = 0.6576 | Macro Precision = 0.6600 | Macro Recall = 0.6607 | Mejor Macro F1 = 0.6588 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=157 Accuracy = 0.6610 | Macro F1 = 0.6575 | Macro Precision = 0.6597 | Macro Recall = 0.6610 | Mejor Macro F1 = 0.6588 | Iteraciones_sin_mejora = 3
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=158 Accuracy = 0.6644 | Macro F1 = 0.6608 | Macro Precision = 0.6631 | Macro Recall = 0.6644 | Mejor Macro F1 = 0.6608 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=159 Accuracy = 0.6618 | Macro F1 = 0.6586 | Macro Precision = 0.6613 | Macro Recall = 0.6618 | Mejor Macro F1 = 0.6608 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=160 Accuracy = 0.6653 | Macro F1 = 0.6624 | Macro Precision = 0.6646 | Macro Recall = 0.6653 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 0
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=161 Accuracy = 0.6642 | Macro F1 = 0.6607 | Macro Precision = 0.6626 | Macro Recall = 0.6642 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 1
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=162 Accuracy = 0.6601 | Macro F1 = 0.6561 | Macro Precision = 0.6580 | Macro Recall = 0.6601 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 2
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=163 Accuracy = 0.6578 | Macro F1 = 0.6543 | Macro Precision = 0.6571 | Macro Recall = 0.6578 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 3
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=164 Accuracy = 0.6595 | Macro F1 = 0.6561 | Macro Precision = 0.6587 | Macro Recall = 0.6595 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 4
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=165 Accuracy = 0.6607 | Macro F1 = 0.6575 | Macro Precision = 0.6600 | Macro Recall = 0.6607 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 5
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=166 Accuracy = 0.6604 | Macro F1 = 0.6571 | Macro Precision = 0.6593 | Macro Recall = 0.6604 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 6
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=167 Accuracy = 0.6644 | Macro F1 = 0.6605 | Macro Precision = 0.6629 | Macro Recall = 0.6644 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 7
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=168 Accuracy = 0.6618 | Macro F1 = 0.6575 | Macro Precision = 0.6594 | Macro Recall = 0.6618 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 8
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=169 Accuracy = 0.6653 | Macro F1 = 0.6621 | Macro Precision = 0.6643 | Macro Recall = 0.6653 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 9
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=170 Accuracy = 0.6618 | Macro F1 = 0.6594 | Macro Precision = 0.6624 | Macro Recall = 0.6618 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 10
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=171 Accuracy = 0.6615 | Macro F1 = 0.6582 | Macro Precision = 0.6600 | Macro Recall = 0.6615 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 11
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=172 Accuracy = 0.6618 | Macro F1 = 0.6585 | Macro Precision = 0.6607 | Macro Recall = 0.6618 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 12
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=173 Accuracy = 0.6604 | Macro F1 = 0.6572 | Macro Precision = 0.6603 | Macro Recall = 0.6604 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 13
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=174 Accuracy = 0.6575 | Macro F1 = 0.6538 | Macro Precision = 0.6554 | Macro Recall = 0.6575 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 14
Model = XGBoost (metricas_logs 1 punto suma)   N_feat=175 Accuracy = 0.6615 | Macro F1 = 0.6584 | Macro Precision = 0.6607 | Macro Recall = 0.6615 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 15

[!] Early Stopping activado: No ha habido mejoras en 15 iteraciones consecutivas.
Deteniendo búsqueda. El mejor modelo se logró con 160 características base.

In [181]:
mejor_paquete_modelo['model_name']

'XGBoost (metricas_logs 1 punto suma)   N_feat=160'

In [182]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

['result/models/XGBoost (metricas_logs 1 punto suma)   N_feat=160.joblib']

In [102]:
mejor_paquete_modelo = joblib.load('result/models/LightGBM (metricas_logs 1 punto suma)   N_feat=202.joblib')

In [103]:
paquete_modelo = mejor_paquete_modelo.copy()


# features_actuales = df_importancias_agrupada['caracteristica'].to_list()[:N_inicio]

mejor_macro_f1_global    = paquete_modelo['resultado']['f1']
mejor_features_global    = paquete_modelo['lista_features'].copy()
pasos_sin_mejora         = 0
limite_puntos_sin_mejora = 20

print(f"Iniciando eliminación recursiva desde {paquete_modelo['N_features_unicas']} características.\n")

while paquete_modelo['N_features_unicas'] > 1 and pasos_sin_mejora < limite_puntos_sin_mejora:

    df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
 
    lista_features_sel=[]
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:(N_feat-1)]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(f'{feature}')
    
    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)
    
    N_feat = len(lista_features_sel)
    model_name = f'{nombre_algoritmo} ({DATOS})   N_feat={N_feat}'

    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    

    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo,lista_feature_names1_sum,X_test_sum,Y_test_etiquetas,encoder_etiquetas)

    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    


    
    if macro_f1 >= mejor_macro_f1_global:
        mejor_macro_f1_global = macro_f1
        mejor_features_global = paquete_modelo['lista_features'].copy()
        pasos_sin_mejora = 0  # ¡Se reinicia porque hemos batido o empatado el récord global!
        mejor_paquete_modelo=paquete_modelo.copy()
    else:
        pasos_sin_mejora += 1  # Si es peor que el récord histórico, sumamos 1
        
    # Imprimir con el formato solicitado (mostrando ya el contador de "Sin mejora" actualizado)
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Sin mejora: {pasos_sin_mejora}")
        

print(f"\n¡Proceso finalizado!")
print(f"Mejor Macro F1 alcanzado: {mejor_macro_f1_global:.4f}")
print(f"Número óptimo de características base: {len(mejor_features_global)}")

Iniciando eliminación recursiva desde 202 características.

Model = LightGBM (metricas_logs 1 punto suma)   N_feat=182 Accuracy = 0.6493 | Macro F1 = 0.6469 | Macro Precision = 0.6497 | Macro Recall = 0.6493 | Sin mejora: 1
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=181 Accuracy = 0.6488 | Macro F1 = 0.6451 | Macro Precision = 0.6478 | Macro Recall = 0.6488 | Sin mejora: 2

KeyboardInterrupt:

In [187]:
mejor_paquete_modelo['model_name']

'XGBoost (metricas_logs 1 punto suma)   N_feat=160'

In [ ]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

In [59]:
paquete_modelo = mejor_paquete_modelo.copy()

mejor_macro_f1_global    = paquete_modelo['resultado']['f1']
mejor_features_global    = paquete_modelo['lista_features'].copy()
pasos_sin_mejora         = 0
limite_puntos_sin_mejora = paciencia + 5

print(f"Iniciando eliminación recursiva desde {paquete_modelo['N_features_unicas']} características.\n")

while paquete_modelo['N_features_unicas'] > 1 and pasos_sin_mejora < limite_puntos_sin_mejora:
    N_feat = paquete_modelo['N_features_unicas']
    
    # Extraer importancias y características actuales
    importancias_raw = paquete_modelo['model'].feature_importances_
    features_raw = paquete_modelo['lista_features']
    
    df_importancias_agrupada, _, num_cero = obtener_importancias_agrupadas(importancias_raw, features_raw)

    # Seleccionar características para el siguiente paso
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:(N_feat-1)]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(f'{feature}')
    
    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    model_name = f'{nombre_algoritmo} (metricas_log) N_feat={N_feat-1}'
    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
   
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    

    
    if macro_f1 >= mejor_macro_f1_global:
        mejor_macro_f1_global = macro_f1
        mejor_features_global = paquete_modelo['lista_features'].copy()
        pasos_sin_mejora = 0  
        mejor_paquete_modelo = paquete_modelo.copy()
    else:
        pasos_sin_mejora += 1  
        
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Sin mejora: {pasos_sin_mejora}")
    del X_train_sub, X_test_sub, importancias_raw, df_importancias_agrupada
    gc.collect()

print(f"\n¡Proceso finalizado!")
print(f"Mejor Macro F1 alcanzado: {mejor_macro_f1_global:.4f}")
print(f"Número óptimo de características base: {len(mejor_features_global)}")

Iniciando eliminación recursiva desde 147 características.

Model = LightGBM (metricas_log) N_feat=146       Accuracy = 0.6958 | Macro F1 = 0.6950 | Macro Precision = 0.6972 | Macro Recall = 0.6958 | Sin mejora: 1
Model = LightGBM (metricas_log) N_feat=145       Accuracy = 0.6958 | Macro F1 = 0.6934 | Macro Precision = 0.6940 | Macro Recall = 0.6958 | Sin mejora: 2
Model = LightGBM (metricas_log) N_feat=144       Accuracy = 0.6926 | Macro F1 = 0.6919 | Macro Precision = 0.6943 | Macro Recall = 0.6926 | Sin mejora: 3
Model = LightGBM (metricas_log) N_feat=143       Accuracy = 0.6958 | Macro F1 = 0.6944 | Macro Precision = 0.6964 | Macro Recall = 0.6958 | Sin mejora: 4
Model = LightGBM (metricas_log) N_feat=142       Accuracy = 0.6993 | Macro F1 = 0.6980 | Macro Precision = 0.6993 | Macro Recall = 0.6993 | Sin mejora: 5
Model = LightGBM (metricas_log) N_feat=141       Accuracy = 0.6978 | Macro F1 = 0.6970 | Macro Precision = 0.6987 | Macro Recall = 0.6978 | Sin mejora: 6
Model = LightGBM (metricas_log) N_feat=140       Accuracy = 0.6978 | Macro F1 = 0.6971 | Macro Precision = 0.6997 | Macro Recall = 0.6978 | Sin mejora: 7
Model = LightGBM (metricas_log) N_feat=139       Accuracy = 0.6958 | Macro F1 = 0.6942 | Macro Precision = 0.6963 | Macro Recall = 0.6958 | Sin mejora: 8
Model = LightGBM (metricas_log) N_feat=138       Accuracy = 0.6926 | Macro F1 = 0.6911 | Macro Precision = 0.6931 | Macro Recall = 0.6926 | Sin mejora: 9
Model = LightGBM (metricas_log) N_feat=137       Accuracy = 0.6917 | Macro F1 = 0.6898 | Macro Precision = 0.6911 | Macro Recall = 0.6917 | Sin mejora: 10
Model = LightGBM (metricas_log) N_feat=136       Accuracy = 0.6909 | Macro F1 = 0.6897 | Macro Precision = 0.6915 | Macro Recall = 0.6909 | Sin mejora: 11
Model = LightGBM (metricas_log) N_feat=135       Accuracy = 0.6897 | Macro F1 = 0.6892 | Macro Precision = 0.6921 | Macro Recall = 0.6897 | Sin mejora: 12
Model = LightGBM (metricas_log) N_feat=134       Accuracy = 0.6970 | Macro F1 = 0.6967 | Macro Precision = 0.6991 | Macro Recall = 0.6970 | Sin mejora: 13
Model = LightGBM (metricas_log) N_feat=133       Accuracy = 0.6932 | Macro F1 = 0.6919 | Macro Precision = 0.6938 | Macro Recall = 0.6932 | Sin mejora: 14
Model = LightGBM (metricas_log) N_feat=132       Accuracy = 0.6830 | Macro F1 = 0.6821 | Macro Precision = 0.6841 | Macro Recall = 0.6830 | Sin mejora: 15
Model = LightGBM (metricas_log) N_feat=131       Accuracy = 0.6824 | Macro F1 = 0.6815 | Macro Precision = 0.6842 | Macro Recall = 0.6824 | Sin mejora: 16
Model = LightGBM (metricas_log) N_feat=130       Accuracy = 0.6824 | Macro F1 = 0.6824 | Macro Precision = 0.6853 | Macro Recall = 0.6824 | Sin mejora: 17
Model = LightGBM (metricas_log) N_feat=129       Accuracy = 0.6827 | Macro F1 = 0.6820 | Macro Precision = 0.6847 | Macro Recall = 0.6827 | Sin mejora: 18
Model = LightGBM (metricas_log) N_feat=128       Accuracy = 0.6839 | Macro F1 = 0.6834 | Macro Precision = 0.6860 | Macro Recall = 0.6839 | Sin mejora: 19
Model = LightGBM (metricas_log) N_feat=127       Accuracy = 0.6769 | Macro F1 = 0.6760 | Macro Precision = 0.6781 | Macro Recall = 0.6769 | Sin mejora: 20

¡Proceso finalizado!
Mejor Macro F1 alcanzado: 0.7011
Número óptimo de características base: 441

## <span style="color:#2ca02c">4.6. Clasificador LightGBM con métricas logs</span>

In [54]:
ALGORITMO_CLASIFICADOR = LGBMClassifier
nombre_algoritmo       ='LightGBM'

### <span style="color:#2ca02c"> 4.6.1. Clasificador LightGBM con métricas logs (3 puntos)</span>

In [48]:
N_puntos = 3
DATOS    = 'metricas_logs 3 puntos'

In [49]:

#hacemos esto para preparar los datos en las mismas variables todos los algoritmos

lista_features = lista_features_names_3puntos

X_train = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_train,lista_feature_sel=lista_features)
print(X_train.shape)
X_test  = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_features)
print(X_test.shape)
X_val   = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_val ,lista_feature_sel=lista_features)
print(X_val.shape)

(10282, 993)
(3445, 993)
(3445, 993)

In [50]:
params_grid = {
    'n_estimators': [200, 300, 400],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [-1, 6, 8, 10],
    'num_leaves': [31, 50, 63],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_samples': [20, 30, 50],
    'reg_alpha': [0.0, 0.1, 0.5],
    'reg_lambda': [0.0, 0.1, 0.5],
    'verbosity': [-1]
    
}

In [51]:
warnings.filterwarnings('ignore', category=UserWarning)

In [52]:
optuna.logging.set_verbosity(optuna.logging.WARNING)
N_trials = 30

# Barra de progreso global
pbar = tqdm(total=N_trials, desc=f"Optimizando {nombre_algoritmo}")

# Crear el estudio

study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=SEED) 
)

# Enlazamos DIRECTAMENTE 'objective_universal' en el partial (evita usar alias antiguos)
objective_func = partial(
    objective_universal, 
    config=params_grid,
    clasificador_cls=ALGORITMO_CLASIFICADOR,
    X_train=X_train,
    X_test=X_test,
    Y_train_encoded=Y_train_encoded,
    Y_test_encoded=Y_test_encoded
)

# Ejecutar la optimización
print(f"=== INICIANDO OPTIMIZACIÓN DE {nombre_algoritmo} CON OPTUNA ===")
try:
    study.optimize(objective_func, n_trials=N_trials, callbacks=[print_callback], n_jobs=1)
finally:
    pbar.close()

# Resultados finales
print(f"\n=== MEJOR COMBINACIÓN ENCONTRADA ({nombre_algoritmo}) ===")
print(study.best_params)
print(f"Mejor Accuracy: {study.best_value:.4f}")

# Reconstruir el modelo final con los mejores parámetros óptimos
mejores_params = study.best_params.copy()
mejores_params['random_state'] = SEED
if 'n_jobs' in ALGORITMO_CLASIFICADOR().get_params():
    mejores_params['n_jobs'] = -1

Optimizando LightGBM:   0%|          | 0/30 [00:00<?, ?it/s]

=== INICIANDO OPTIMIZACIÓN DE LightGBM CON OPTUNA ===

Optimizando LightGBM:   3%|▎         | 1/30 [00:23<11:27, 23.70s/it, Mejor_Acc=0.6679, Trial=0]

Trial  0                | Actual Acc: 0.6679 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 6, 'num_leaves': 31, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_samples': 20, 'reg_alpha': 0.1, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6679 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 6, 'num_leaves': 31, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_samples': 20, 'reg_alpha': 0.1, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:   7%|▋         | 2/30 [01:08<16:50, 36.10s/it, Mejor_Acc=0.6792, Trial=1]

Trial  1                | Actual Acc: 0.6792 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6792 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  10%|█         | 3/30 [01:26<12:33, 27.90s/it, Mejor_Acc=0.6792, Trial=2]

Trial  2                | Actual Acc: 0.6557 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.5, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6792 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  13%|█▎        | 4/30 [01:47<10:49, 24.98s/it, Mejor_Acc=0.6792, Trial=3]

Trial  3                | Actual Acc: 0.6639 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.1, 'max_depth': 10, 'num_leaves': 50, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.5, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6792 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  17%|█▋        | 5/30 [02:02<08:58, 21.52s/it, Mejor_Acc=0.6792, Trial=4]

Trial  4                | Actual Acc: 0.6438 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 1.0, 'colsample_bytree': 0.9, 'min_child_samples': 20, 'reg_alpha': 0.5, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6792 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  20%|██        | 6/30 [03:22<16:34, 41.44s/it, Mejor_Acc=0.6801, Trial=5]

Trial  5                | Actual Acc: 0.6801 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.01, 'max_depth': -1, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.9, 'min_child_samples': 30, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6801 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.01, 'max_depth': -1, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.9, 'min_child_samples': 30, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  23%|██▎       | 7/30 [03:57<15:03, 39.28s/it, Mejor_Acc=0.6853, Trial=6]

Trial  6                | Actual Acc: 0.6853 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6853 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  27%|██▋       | 8/30 [04:34<14:12, 38.73s/it, Mejor_Acc=0.6853, Trial=7]

Trial  7                | Actual Acc: 0.6671 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': -1, 'num_leaves': 50, 'subsample': 0.9, 'colsample_bytree': 0.9, 'min_child_samples': 30, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6853 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  30%|███       | 9/30 [05:10<13:09, 37.60s/it, Mejor_Acc=0.6853, Trial=8]

Trial  8                | Actual Acc: 0.6761 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 6, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.8, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6853 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  33%|███▎      | 10/30 [05:53<13:06, 39.30s/it, Mejor_Acc=0.6853, Trial=9]

Trial  9                | Actual Acc: 0.6702 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 10, 'num_leaves': 31, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_samples': 30, 'reg_alpha': 0.1, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6853 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  37%|███▋      | 11/30 [06:40<13:13, 41.75s/it, Mejor_Acc=0.6859, Trial=10]

Trial 10                | Actual Acc: 0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  40%|████      | 12/30 [07:26<12:52, 42.93s/it, Mejor_Acc=0.6859, Trial=11]

Trial 11                | Actual Acc: 0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  43%|████▎     | 13/30 [08:21<13:14, 46.71s/it, Mejor_Acc=0.6859, Trial=12]

Trial 12                | Actual Acc: 0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  47%|████▋     | 14/30 [09:06<12:20, 46.27s/it, Mejor_Acc=0.6859, Trial=13]

Trial 13                | Actual Acc: 0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  50%|█████     | 15/30 [09:52<11:32, 46.18s/it, Mejor_Acc=0.6859, Trial=14]

Trial 14                | Actual Acc: 0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  53%|█████▎    | 16/30 [10:23<09:41, 41.53s/it, Mejor_Acc=0.6859, Trial=15]

Trial 15                | Actual Acc: 0.6804 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.1, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6859 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  57%|█████▋    | 17/30 [11:21<10:03, 46.43s/it, Mejor_Acc=0.6894, Trial=16]

Trial 16                | Actual Acc: 0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  60%|██████    | 18/30 [12:19<10:00, 50.08s/it, Mejor_Acc=0.6894, Trial=17]

Trial 17                | Actual Acc: 0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  63%|██████▎   | 19/30 [12:49<08:03, 43.98s/it, Mejor_Acc=0.6894, Trial=18]

Trial 18                | Actual Acc: 0.6708 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.5, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  67%|██████▋   | 20/30 [13:22<06:45, 40.52s/it, Mejor_Acc=0.6894, Trial=19]

Trial 19                | Actual Acc: 0.6790 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 30, 'reg_alpha': 0.1, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  70%|███████   | 21/30 [14:21<06:55, 46.11s/it, Mejor_Acc=0.6894, Trial=20]

Trial 20                | Actual Acc: 0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  73%|███████▎  | 22/30 [15:26<06:54, 51.79s/it, Mejor_Acc=0.6894, Trial=21]

Trial 21                | Actual Acc: 0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  77%|███████▋  | 23/30 [16:26<06:19, 54.18s/it, Mejor_Acc=0.6894, Trial=22]

Trial 22                | Actual Acc: 0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  80%|████████  | 24/30 [17:26<05:37, 56.19s/it, Mejor_Acc=0.6894, Trial=23]

Trial 23                | Actual Acc: 0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  83%|████████▎ | 25/30 [18:28<04:49, 57.84s/it, Mejor_Acc=0.6894, Trial=24]

Trial 24                | Actual Acc: 0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  87%|████████▋ | 26/30 [19:27<03:52, 58.21s/it, Mejor_Acc=0.6894, Trial=25]

Trial 25                | Actual Acc: 0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6894 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  90%|█████████ | 27/30 [21:03<03:28, 69.54s/it, Mejor_Acc=0.6926, Trial=26]

Trial 26                | Actual Acc: 0.6926 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6926 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  93%|█████████▎| 28/30 [22:44<02:37, 78.88s/it, Mejor_Acc=0.6940, Trial=27]

Trial 27                | Actual Acc: 0.6940 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6940 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  97%|█████████▋| 29/30 [23:47<01:14, 74.28s/it, Mejor_Acc=0.6940, Trial=28]

Trial 28                | Actual Acc: 0.6769 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 30, 'reg_alpha': 0.1, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6940 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM: 100%|██████████| 30/30 [24:39<00:00, 49.32s/it, Mejor_Acc=0.6940, Trial=29]

Trial 29                | Actual Acc: 0.6708 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.5, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6940 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

=== MEJOR COMBINACIÓN ENCONTRADA (LightGBM) ===
{'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
Mejor Accuracy: 0.6940

In [53]:
clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
clf_anomalias_opt.fit(X_train, Y_train_encoded)

LGBMClassifier(learning_rate=0.05, max_depth=6, min_child_samples=50,
               n_estimators=400, n_jobs=-1, num_leaves=50, random_state=100,
               reg_lambda=0.1, subsample=0.8, verbosity=-1)

In [54]:
model_name=f'{nombre_algoritmo} ({DATOS})(todas las features)'
paquete_modelo={}

paquete_modelo['model_name']         = model_name
paquete_modelo['model']              = clf_anomalias_opt
paquete_modelo['parametros']         = mejores_params
paquete_modelo['lista_features']     = lista_features
paquete_modelo['N_features']         = len(paquete_modelo['lista_features'] )
paquete_modelo['N_features_unicas']  = len(get_lista_feature_sin_lag(paquete_modelo['lista_features'] ))
paquete_modelo['datos']              = DATOS
paquete_modelo['algoritmo']          = nombre_algoritmo

resultado,reporte_dict,Y_pred_probabilidades = evaluar_modelo(paquete_modelo,lista_features,X_test,Y_test_etiquetas,encoder_etiquetas)
print(f"=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===\n{model_name}")
print(paquete_modelo['classification_report_str'])

joblib.dump(paquete_modelo, f'{FOLDER_SALIDA}/models/{model_name}.joblib')

=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===
LightGBM (metricas_logs 3 puntos)(todas las features)
                                               precision    recall  f1-score   support

           access_token_auth_header_error_401       1.00      0.98      0.99        65
          access_token_authorization_form_401       0.46      0.48      0.47        65
         access_token_client_id_not_found_404       1.00      1.00      1.00        65
         access_token_client_secret_wrong_401       1.00      0.98      0.99        65
             access_token_form_urlencoded_400       0.59      0.63      0.61        65
          access_token_illegal_grant_type_400       0.98      1.00      0.99        65
access_token_missing_authorization_header_400       0.54      0.55      0.55        65
     authorization_code_client_id_missing_400       0.90      0.82      0.85        65
     authorization_code_invalid_client_id_404       0.79      0.86      0.82        65
      authorization_code_invalid_password_401       0.91      0.94      0.92        65
 authorization_code_missing_response_type_400       0.67      0.71      0.69        65
     authorization_code_response_not_code_400       0.71      0.69      0.70        65
       code_challenge_invalid_format_pkce_400       0.62      0.62      0.62        65
             code_challenge_too_long_pkce_400       0.62      0.66      0.64        65
            code_challenge_too_short_pkce_400       0.39      0.38      0.39        65
               code_verifier_missing_pkce_400       0.72      0.77      0.75        65
              code_verifier_too_long_pkce_400       0.25      0.22      0.23        65
             code_verifier_too_short_pkce_400       0.26      0.23      0.24        65
                  delete_client_404_no_client       1.00      1.00      1.00        65
                delete_service_404_no_service       0.84      0.80      0.82        65
                             delete_token_404       0.48      0.46      0.47        65
                      delete_user_404_no_user       0.20      0.18      0.19        65
                     get_client_404_no_client       0.97      1.00      0.98        65
                  get_client_page_400_no_page       1.00      1.00      1.00        65
                   get_service_404_no_service       0.49      0.51      0.50        65
                 get_service_page_400_no_page       0.84      0.91      0.87        65
                                get_token_404       0.46      0.55      0.50        65
                   get_token_page_400_no_page       0.65      0.72      0.69        65
                         get_user_404_no_user       0.47      0.51      0.49        65
                    get_user_page_400_no_page       0.48      0.52      0.50        65
       invalid_code_challenge_method_pkce_400       0.84      0.82      0.83        65
        invalid_code_verifier_format_PKCE_400       0.40      0.29      0.34        65
            register_client_400_clientProfile       1.00      0.98      0.99        65
               register_client_400_clientType       1.00      1.00      1.00        65
                  register_client_404_no_user       0.95      0.92      0.94        65
              register_service_400_service_id       0.93      0.83      0.88        65
            register_service_400_service_type       0.84      0.91      0.87        65
                 register_service_404_no_user       0.70      0.58      0.64        65
               register_user_400_email_exists       0.54      0.45      0.49        65
                register_user_400_no_password       0.59      0.74      0.65        65
          register_user_400_password_no_match       0.74      0.71      0.72        65
                register_user_400_user_exists       0.68      0.66      0.67        65
              update_client_400_clientProfile       1.00      0.97      0.98        65
                 update_client_400_clientType       1.00      1.00      1.00        65
                   update_client_404_clientId       0.52      0.60      0.56        65
                    update_client_404_ownerId       0.92      0.69      0.79        65
                update_password_400_not_match       0.73      0.83      0.78        65
           update_password_401_wrong_password       0.23      0.26      0.24        65
           update_password_404_user_not_found       0.18      0.14      0.16        65
                update_service_404_service_id       0.85      0.85      0.85        65
                   update_service_404_user_id       0.86      0.86      0.86        65
                      update_user_404_no_user       0.58      0.58      0.58        65
                 verification_failed_pkce_400       0.39      0.42      0.40        65

                                     accuracy                           0.69      3445
                                    macro avg       0.69      0.69      0.69      3445
                                 weighted avg       0.69      0.69      0.69      3445

['result/models/LightGBM (metricas_logs 3 puntos)(todas las features).joblib']

In [55]:
df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
print(f"Características con importancia cero: {num_cero}")

Características con importancia cero: 56

In [58]:
n_min = 135
n_max = len(importancias) - num_cero


# --- VARIABLES PARA EL EARLY STOPPING ---
paciencia = 15
iteraciones_sin_mejora = 0
mejor_score_global = -1.0
mejor_paquete_modelo = None

for N_feat in range(n_min, n_max + 1):
    model_name = f'{nombre_algoritmo} ({DATOS})   N_feat={N_feat}'
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:N_feat]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(feature)

    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    


    # --- LÓGICA DE EARLY STOPPING ---
    score_actual = macro_f1 
    
    if score_actual > mejor_score_global:
        mejor_score_global = score_actual
        mejor_paquete_modelo = paquete_modelo.copy()
        iteraciones_sin_mejora = 0  # Reiniciamos contador si mejora
    else:
        iteraciones_sin_mejora += 1

    # --- IMPRESIÓN EN UNA SOLA LÍNEA ---
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Mejor Macro F1 = {mejor_score_global:.4f} | Iteraciones_sin_mejora = {iteraciones_sin_mejora}")
    del X_train_sub, X_test_sub
    gc.collect()
    
    # Comprobación de parada
    if iteraciones_sin_mejora >= paciencia:
        print(f"\n[!] Early Stopping activado: No ha habido mejoras en {paciencia} iteraciones consecutivas.")
        print(f"Deteniendo búsqueda. El mejor modelo se logró con {mejor_paquete_modelo['N_features_unicas']} características base.")
        break

Model = LightGBM (metricas_logs 3 puntos)   N_feat=135 Accuracy = 0.6807 | Macro F1 = 0.6779 | Macro Precision = 0.6786 | Macro Recall = 0.6807 | Mejor Macro F1 = 0.6779 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 3 puntos)   N_feat=136 Accuracy = 0.6827 | Macro F1 = 0.6812 | Macro Precision = 0.6837 | Macro Recall = 0.6827 | Mejor Macro F1 = 0.6812 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 3 puntos)   N_feat=137 Accuracy = 0.6790 | Macro F1 = 0.6779 | Macro Precision = 0.6798 | Macro Recall = 0.6790 | Mejor Macro F1 = 0.6812 | Iteraciones_sin_mejora = 1
Model = LightGBM (metricas_logs 3 puntos)   N_feat=138 Accuracy = 0.6821 | Macro F1 = 0.6810 | Macro Precision = 0.6832 | Macro Recall = 0.6821 | Mejor Macro F1 = 0.6812 | Iteraciones_sin_mejora = 2
Model = LightGBM (metricas_logs 3 puntos)   N_feat=139 Accuracy = 0.6784 | Macro F1 = 0.6777 | Macro Precision = 0.6806 | Macro Recall = 0.6784 | Mejor Macro F1 = 0.6812 | Iteraciones_sin_mejora = 3
Model = LightGBM (metricas_logs 3 puntos)   N_feat=140 Accuracy = 0.6781 | Macro F1 = 0.6770 | Macro Precision = 0.6798 | Macro Recall = 0.6781 | Mejor Macro F1 = 0.6812 | Iteraciones_sin_mejora = 4
Model = LightGBM (metricas_logs 3 puntos)   N_feat=141 Accuracy = 0.6801 | Macro F1 = 0.6779 | Macro Precision = 0.6791 | Macro Recall = 0.6801 | Mejor Macro F1 = 0.6812 | Iteraciones_sin_mejora = 5
Model = LightGBM (metricas_logs 3 puntos)   N_feat=142 Accuracy = 0.6853 | Macro F1 = 0.6841 | Macro Precision = 0.6857 | Macro Recall = 0.6853 | Mejor Macro F1 = 0.6841 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 3 puntos)   N_feat=143 Accuracy = 0.6952 | Macro F1 = 0.6947 | Macro Precision = 0.6973 | Macro Recall = 0.6952 | Mejor Macro F1 = 0.6947 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 3 puntos)   N_feat=144 Accuracy = 0.6949 | Macro F1 = 0.6939 | Macro Precision = 0.6959 | Macro Recall = 0.6949 | Mejor Macro F1 = 0.6947 | Iteraciones_sin_mejora = 1
Model = LightGBM (metricas_logs 3 puntos)   N_feat=145 Accuracy = 0.6984 | Macro F1 = 0.6968 | Macro Precision = 0.6981 | Macro Recall = 0.6984 | Mejor Macro F1 = 0.6968 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 3 puntos)   N_feat=146 Accuracy = 0.6996 | Macro F1 = 0.6975 | Macro Precision = 0.6983 | Macro Recall = 0.6996 | Mejor Macro F1 = 0.6975 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 3 puntos)   N_feat=147 Accuracy = 0.7022 | Macro F1 = 0.7011 | Macro Precision = 0.7040 | Macro Recall = 0.7022 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 3 puntos)   N_feat=148 Accuracy = 0.6932 | Macro F1 = 0.6928 | Macro Precision = 0.6958 | Macro Recall = 0.6932 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 1
Model = LightGBM (metricas_logs 3 puntos)   N_feat=149 Accuracy = 0.6955 | Macro F1 = 0.6945 | Macro Precision = 0.6966 | Macro Recall = 0.6955 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 2
Model = LightGBM (metricas_logs 3 puntos)   N_feat=150 Accuracy = 0.6975 | Macro F1 = 0.6960 | Macro Precision = 0.6982 | Macro Recall = 0.6975 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 3
Model = LightGBM (metricas_logs 3 puntos)   N_feat=151 Accuracy = 0.6981 | Macro F1 = 0.6969 | Macro Precision = 0.6990 | Macro Recall = 0.6981 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 4
Model = LightGBM (metricas_logs 3 puntos)   N_feat=152 Accuracy = 0.6946 | Macro F1 = 0.6937 | Macro Precision = 0.6955 | Macro Recall = 0.6946 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 5
Model = LightGBM (metricas_logs 3 puntos)   N_feat=153 Accuracy = 0.6975 | Macro F1 = 0.6959 | Macro Precision = 0.6971 | Macro Recall = 0.6975 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 6
Model = LightGBM (metricas_logs 3 puntos)   N_feat=154 Accuracy = 0.6938 | Macro F1 = 0.6931 | Macro Precision = 0.6955 | Macro Recall = 0.6938 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 7
Model = LightGBM (metricas_logs 3 puntos)   N_feat=155 Accuracy = 0.6972 | Macro F1 = 0.6959 | Macro Precision = 0.6973 | Macro Recall = 0.6972 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 8
Model = LightGBM (metricas_logs 3 puntos)   N_feat=156 Accuracy = 0.6993 | Macro F1 = 0.6987 | Macro Precision = 0.7008 | Macro Recall = 0.6993 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 9
Model = LightGBM (metricas_logs 3 puntos)   N_feat=157 Accuracy = 0.6926 | Macro F1 = 0.6911 | Macro Precision = 0.6927 | Macro Recall = 0.6926 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 10
Model = LightGBM (metricas_logs 3 puntos)   N_feat=158 Accuracy = 0.6970 | Macro F1 = 0.6962 | Macro Precision = 0.6990 | Macro Recall = 0.6970 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 11
Model = LightGBM (metricas_logs 3 puntos)   N_feat=159 Accuracy = 0.6932 | Macro F1 = 0.6929 | Macro Precision = 0.6955 | Macro Recall = 0.6932 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 12
Model = LightGBM (metricas_logs 3 puntos)   N_feat=160 Accuracy = 0.6946 | Macro F1 = 0.6940 | Macro Precision = 0.6963 | Macro Recall = 0.6946 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 13
Model = LightGBM (metricas_logs 3 puntos)   N_feat=161 Accuracy = 0.6972 | Macro F1 = 0.6964 | Macro Precision = 0.6985 | Macro Recall = 0.6972 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 14
Model = LightGBM (metricas_logs 3 puntos)   N_feat=162 Accuracy = 0.6975 | Macro F1 = 0.6951 | Macro Precision = 0.6957 | Macro Recall = 0.6975 | Mejor Macro F1 = 0.7011 | Iteraciones_sin_mejora = 15

[!] Early Stopping activado: No ha habido mejoras en 15 iteraciones consecutivas.
Deteniendo búsqueda. El mejor modelo se logró con 147 características base.

In [60]:
paquete_modelo = mejor_paquete_modelo.copy()

mejor_macro_f1_global    = paquete_modelo['resultado']['f1']
mejor_features_global    = paquete_modelo['lista_features'].copy()
pasos_sin_mejora         = 0
limite_puntos_sin_mejora = paciencia + 5

print(f"Iniciando eliminación recursiva desde {paquete_modelo['N_features_unicas']} características.\n")

while paquete_modelo['N_features_unicas'] > 1 and pasos_sin_mejora < limite_puntos_sin_mejora:
    N_feat = paquete_modelo['N_features_unicas']
    
    # Extraer importancias y características actuales
    importancias_raw = paquete_modelo['model'].feature_importances_
    features_raw = paquete_modelo['lista_features']
    
    df_importancias_agrupada, _, num_cero = obtener_importancias_agrupadas(importancias_raw, features_raw)

    # Seleccionar características para el siguiente paso
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:(N_feat-1)]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(f'{feature}')
    
    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    model_name = f'{nombre_algoritmo} (metricas_log) N_feat={N_feat-1}'
    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
   
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    

    
    if macro_f1 >= mejor_macro_f1_global:
        mejor_macro_f1_global = macro_f1
        mejor_features_global = paquete_modelo['lista_features'].copy()
        pasos_sin_mejora = 0  
        mejor_paquete_modelo = paquete_modelo.copy()
    else:
        pasos_sin_mejora += 1  
        
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Sin mejora: {pasos_sin_mejora}")
    del X_train_sub, X_test_sub, importancias_raw, df_importancias_agrupada
    gc.collect()

print(f"\n¡Proceso finalizado!")
print(f"Mejor Macro F1 alcanzado: {mejor_macro_f1_global:.4f}")
print(f"Número óptimo de características base: {len(mejor_features_global)}")

Iniciando eliminación recursiva desde 147 características.

Model = LightGBM (metricas_log) N_feat=146       Accuracy = 0.6958 | Macro F1 = 0.6950 | Macro Precision = 0.6972 | Macro Recall = 0.6958 | Sin mejora: 1
Model = LightGBM (metricas_log) N_feat=145       Accuracy = 0.6958 | Macro F1 = 0.6934 | Macro Precision = 0.6940 | Macro Recall = 0.6958 | Sin mejora: 2
Model = LightGBM (metricas_log) N_feat=144       Accuracy = 0.6926 | Macro F1 = 0.6919 | Macro Precision = 0.6943 | Macro Recall = 0.6926 | Sin mejora: 3
Model = LightGBM (metricas_log) N_feat=143       Accuracy = 0.6958 | Macro F1 = 0.6944 | Macro Precision = 0.6964 | Macro Recall = 0.6958 | Sin mejora: 4
Model = LightGBM (metricas_log) N_feat=142       Accuracy = 0.6993 | Macro F1 = 0.6980 | Macro Precision = 0.6993 | Macro Recall = 0.6993 | Sin mejora: 5
Model = LightGBM (metricas_log) N_feat=141       Accuracy = 0.6978 | Macro F1 = 0.6970 | Macro Precision = 0.6987 | Macro Recall = 0.6978 | Sin mejora: 6
Model = LightGBM (metricas_log) N_feat=140       Accuracy = 0.6978 | Macro F1 = 0.6971 | Macro Precision = 0.6997 | Macro Recall = 0.6978 | Sin mejora: 7
Model = LightGBM (metricas_log) N_feat=139       Accuracy = 0.6958 | Macro F1 = 0.6942 | Macro Precision = 0.6963 | Macro Recall = 0.6958 | Sin mejora: 8
Model = LightGBM (metricas_log) N_feat=138       Accuracy = 0.6926 | Macro F1 = 0.6911 | Macro Precision = 0.6931 | Macro Recall = 0.6926 | Sin mejora: 9
Model = LightGBM (metricas_log) N_feat=137       Accuracy = 0.6917 | Macro F1 = 0.6898 | Macro Precision = 0.6911 | Macro Recall = 0.6917 | Sin mejora: 10
Model = LightGBM (metricas_log) N_feat=136       Accuracy = 0.6909 | Macro F1 = 0.6897 | Macro Precision = 0.6915 | Macro Recall = 0.6909 | Sin mejora: 11
Model = LightGBM (metricas_log) N_feat=135       Accuracy = 0.6897 | Macro F1 = 0.6892 | Macro Precision = 0.6921 | Macro Recall = 0.6897 | Sin mejora: 12
Model = LightGBM (metricas_log) N_feat=134       Accuracy = 0.6970 | Macro F1 = 0.6967 | Macro Precision = 0.6991 | Macro Recall = 0.6970 | Sin mejora: 13
Model = LightGBM (metricas_log) N_feat=133       Accuracy = 0.6932 | Macro F1 = 0.6919 | Macro Precision = 0.6938 | Macro Recall = 0.6932 | Sin mejora: 14
Model = LightGBM (metricas_log) N_feat=132       Accuracy = 0.6830 | Macro F1 = 0.6821 | Macro Precision = 0.6841 | Macro Recall = 0.6830 | Sin mejora: 15
Model = LightGBM (metricas_log) N_feat=131       Accuracy = 0.6824 | Macro F1 = 0.6815 | Macro Precision = 0.6842 | Macro Recall = 0.6824 | Sin mejora: 16
Model = LightGBM (metricas_log) N_feat=130       Accuracy = 0.6824 | Macro F1 = 0.6824 | Macro Precision = 0.6853 | Macro Recall = 0.6824 | Sin mejora: 17
Model = LightGBM (metricas_log) N_feat=129       Accuracy = 0.6827 | Macro F1 = 0.6820 | Macro Precision = 0.6847 | Macro Recall = 0.6827 | Sin mejora: 18
Model = LightGBM (metricas_log) N_feat=128       Accuracy = 0.6839 | Macro F1 = 0.6834 | Macro Precision = 0.6860 | Macro Recall = 0.6839 | Sin mejora: 19
Model = LightGBM (metricas_log) N_feat=127       Accuracy = 0.6769 | Macro F1 = 0.6760 | Macro Precision = 0.6781 | Macro Recall = 0.6769 | Sin mejora: 20

¡Proceso finalizado!
Mejor Macro F1 alcanzado: 0.7011
Número óptimo de características base: 441

In [61]:
mejor_paquete_modelo['model_name']

'LightGBM (metricas_logs 3 puntos)   N_feat=147'

In [62]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

['result/models/LightGBM (metricas_logs 3 puntos)   N_feat=147.joblib']

### <span style="color:#2ca02c">4.5.2. Clasificador LightGBM (1 punto de 3 intervalos) con metricas_logs</span>

In [55]:
N_puntos = 1
DATOS    = 'metricas_logs 1 punto suma'

In [56]:
lista_features = lista_feature_names_1punto_sum

X_train = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_train,lista_feature_sel=lista_features)
print(X_train.shape)
X_test  = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_test ,lista_feature_sel=lista_features)
print(X_test.shape)
X_val   = X_matrix_sel_data(X_matrix,lista_feature_names,lista_idx_filas=idx_val ,lista_feature_sel=lista_features)
print(X_val.shape)

(10282, 331)
(3445, 331)
(3445, 331)

In [57]:
params_grid = {
    'n_estimators': [200, 300, 400],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [-1, 6, 8, 10],
    'num_leaves': [31, 50, 63],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_samples': [20, 30, 50],
    'reg_alpha': [0.0, 0.1, 0.5],
    'reg_lambda': [0.0, 0.1, 0.5],
    'verbosity': [-1]
    
}

In [53]:

optuna.logging.set_verbosity(optuna.logging.WARNING)
N_trials = 30

# Barra de progreso global
pbar = tqdm(total=N_trials, desc=f"Optimizando {nombre_algoritmo}")

# Crear el estudio

study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=SEED) 
)

# Enlazamos DIRECTAMENTE 'objective_universal' en el partial (evita usar alias antiguos)
objective_func = partial(
    objective_universal, 
    config=params_grid,
    clasificador_cls=ALGORITMO_CLASIFICADOR,
    X_train=X_train,
    X_test=X_test,
    Y_train_encoded=Y_train_encoded,
    Y_test_encoded=Y_test_encoded
)

# Ejecutar la optimización
print(f"=== INICIANDO OPTIMIZACIÓN DE {nombre_algoritmo} CON OPTUNA ===")
try:
    study.optimize(objective_func, n_trials=N_trials, callbacks=[print_callback], n_jobs=1)
finally:
    pbar.close()

# Resultados finales
print(f"\n=== MEJOR COMBINACIÓN ENCONTRADA ({nombre_algoritmo}) ===")
print(study.best_params)
print(f"Mejor Accuracy: {study.best_value:.4f}")

# Reconstruir el modelo final con los mejores parámetros óptimos
mejores_params = study.best_params.copy()
mejores_params['random_state'] = SEED
if 'n_jobs' in ALGORITMO_CLASIFICADOR().get_params():
    mejores_params['n_jobs'] = -1

Optimizando LightGBM:   0%|          | 0/30 [00:00<?, ?it/s]

=== INICIANDO OPTIMIZACIÓN DE LightGBM CON OPTUNA ===

Optimizando LightGBM:   3%|▎         | 1/30 [00:17<08:39, 17.92s/it, Mejor_Acc=0.6424, Trial=0]

Trial  0                | Actual Acc: 0.6424 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 6, 'num_leaves': 31, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_samples': 20, 'reg_alpha': 0.1, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6424 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 6, 'num_leaves': 31, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_samples': 20, 'reg_alpha': 0.1, 'reg_lambda': 0.1, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:   7%|▋         | 2/30 [00:51<12:43, 27.28s/it, Mejor_Acc=0.6496, Trial=1]

Trial  1                | Actual Acc: 0.6496 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6496 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  10%|█         | 3/30 [01:05<09:28, 21.05s/it, Mejor_Acc=0.6496, Trial=2]

Trial  2                | Actual Acc: 0.6360 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.5, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6496 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  13%|█▎        | 4/30 [01:16<07:22, 17.02s/it, Mejor_Acc=0.6496, Trial=3]

Trial  3                | Actual Acc: 0.6435 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.1, 'max_depth': 10, 'num_leaves': 50, 'subsample': 0.9, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.5, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6496 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  17%|█▋        | 5/30 [01:27<06:12, 14.92s/it, Mejor_Acc=0.6496, Trial=4]

Trial  4                | Actual Acc: 0.6232 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 1.0, 'colsample_bytree': 0.9, 'min_child_samples': 20, 'reg_alpha': 0.5, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6496 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': -1, 'num_leaves': 31, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  20%|██        | 6/30 [02:21<11:21, 28.38s/it, Mejor_Acc=0.6502, Trial=5]

Trial  5                | Actual Acc: 0.6502 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.01, 'max_depth': -1, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.9, 'min_child_samples': 30, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6502 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.01, 'max_depth': -1, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.9, 'min_child_samples': 30, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  23%|██▎       | 7/30 [02:46<10:22, 27.05s/it, Mejor_Acc=0.6592, Trial=6]

Trial  6                | Actual Acc: 0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  27%|██▋       | 8/30 [03:08<09:21, 25.52s/it, Mejor_Acc=0.6592, Trial=7]

Trial  7                | Actual Acc: 0.6435 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': -1, 'num_leaves': 50, 'subsample': 0.9, 'colsample_bytree': 0.9, 'min_child_samples': 30, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  30%|███       | 9/30 [03:28<08:20, 23.82s/it, Mejor_Acc=0.6592, Trial=8]

Trial  8                | Actual Acc: 0.6447 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.01, 'max_depth': 6, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.8, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.5, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  33%|███▎      | 10/30 [03:47<07:24, 22.21s/it, Mejor_Acc=0.6592, Trial=9]

Trial  9                | Actual Acc: 0.6403 | Parámetros: {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 10, 'num_leaves': 31, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_samples': 30, 'reg_alpha': 0.1, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  37%|███▋      | 11/30 [04:14<07:33, 23.87s/it, Mejor_Acc=0.6592, Trial=10]

Trial 10                | Actual Acc: 0.6586 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  40%|████      | 12/30 [04:44<07:41, 25.61s/it, Mejor_Acc=0.6592, Trial=11]

Trial 11                | Actual Acc: 0.6586 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  43%|████▎     | 13/30 [05:12<07:29, 26.43s/it, Mejor_Acc=0.6592, Trial=12]

Trial 12                | Actual Acc: 0.6586 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  47%|████▋     | 14/30 [05:42<07:18, 27.40s/it, Mejor_Acc=0.6592, Trial=13]

Trial 13                | Actual Acc: 0.6586 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  50%|█████     | 15/30 [06:15<07:16, 29.08s/it, Mejor_Acc=0.6592, Trial=14]

Trial 14                | Actual Acc: 0.6583 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  53%|█████▎    | 16/30 [06:27<05:35, 23.99s/it, Mejor_Acc=0.6592, Trial=15]

Trial 15                | Actual Acc: 0.6412 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.1, 'reg_lambda': 0.1, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6592 | Parámetros: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 8, 'num_leaves': 63, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  57%|█████▋    | 17/30 [07:03<06:00, 27.73s/it, Mejor_Acc=0.6604, Trial=16]

Trial 16                | Actual Acc: 0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  60%|██████    | 18/30 [07:41<06:07, 30.61s/it, Mejor_Acc=0.6604, Trial=17]

Trial 17                | Actual Acc: 0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  63%|██████▎   | 19/30 [07:57<04:49, 26.30s/it, Mejor_Acc=0.6604, Trial=18]

Trial 18                | Actual Acc: 0.6499 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 20, 'reg_alpha': 0.5, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  67%|██████▋   | 20/30 [08:18<04:05, 24.59s/it, Mejor_Acc=0.6604, Trial=19]

Trial 19                | Actual Acc: 0.6427 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 30, 'reg_alpha': 0.1, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  70%|███████   | 21/30 [08:58<04:23, 29.32s/it, Mejor_Acc=0.6604, Trial=20]

Trial 20                | Actual Acc: 0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  73%|███████▎  | 22/30 [09:43<04:33, 34.14s/it, Mejor_Acc=0.6604, Trial=21]

Trial 21                | Actual Acc: 0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  77%|███████▋  | 23/30 [10:22<04:09, 35.59s/it, Mejor_Acc=0.6604, Trial=22]

Trial 22                | Actual Acc: 0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  80%|████████  | 24/30 [11:00<03:37, 36.27s/it, Mejor_Acc=0.6604, Trial=23]

Trial 23                | Actual Acc: 0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  83%|████████▎ | 25/30 [11:37<03:02, 36.53s/it, Mejor_Acc=0.6604, Trial=24]

Trial 24                | Actual Acc: 0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  87%|████████▋ | 26/30 [12:15<02:27, 36.81s/it, Mejor_Acc=0.6604, Trial=25]

Trial 25                | Actual Acc: 0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6604 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  90%|█████████ | 27/30 [12:57<01:54, 38.30s/it, Mejor_Acc=0.6621, Trial=26]

Trial 26                | Actual Acc: 0.6621 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6621 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  93%|█████████▎| 28/30 [13:31<01:14, 37.22s/it, Mejor_Acc=0.6621, Trial=27]

Trial 27                | Actual Acc: 0.6517 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6621 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM:  97%|█████████▋| 29/30 [13:53<00:32, 32.57s/it, Mejor_Acc=0.6621, Trial=28]

Trial 28                | Actual Acc: 0.6491 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 10, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 30, 'reg_alpha': 0.1, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6621 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

Optimizando LightGBM: 100%|██████████| 30/30 [14:10<00:00, 28.36s/it, Mejor_Acc=0.6621, Trial=29]

Trial 29                | Actual Acc: 0.6438 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 6, 'num_leaves': 50, 'subsample': 1.0, 'colsample_bytree': 0.8, 'min_child_samples': 20, 'reg_alpha': 0.5, 'reg_lambda': 0.0, 'verbosity': -1}
   -> MEJOR HASTA AHORA | Mejor Acc:  0.6621 | Parámetros: {'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
----------------------------------------------------------------------------------------------------

=== MEJOR COMBINACIÓN ENCONTRADA (LightGBM) ===
{'n_estimators': 400, 'learning_rate': 0.05, 'max_depth': 8, 'num_leaves': 50, 'subsample': 0.7, 'colsample_bytree': 1.0, 'min_child_samples': 50, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'verbosity': -1}
Mejor Accuracy: 0.6621

In [47]:
clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
clf_anomalias_opt.fit(X_train, Y_train_encoded)

NameError: name 'ALGORITMO_CLASIFICADOR' is not defined

In [68]:
model_name=f'{nombre_algoritmo} ({DATOS})(todas las features)'
paquete_modelo={}

paquete_modelo['model_name']         = model_name
paquete_modelo['model']              = clf_anomalias_opt
paquete_modelo['parametros']         = mejores_params
paquete_modelo['lista_features']     = lista_features
paquete_modelo['N_features']         = len(paquete_modelo['lista_features'] )
paquete_modelo['N_features_unicas']  = len(get_lista_feature_sin_lag(paquete_modelo['lista_features'] ))
paquete_modelo['datos']              = DATOS
paquete_modelo['algoritmo']          = nombre_algoritmo

resultado,reporte_dict,Y_pred_probabilidades = evaluar_modelo(paquete_modelo,lista_features,X_test,Y_test_etiquetas,encoder_etiquetas)
print(f"=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===\n{model_name}")
print(paquete_modelo['classification_report_str'])

joblib.dump(paquete_modelo, f'{FOLDER_SALIDA}/models/{model_name}.joblib')

=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA ===
LightGBM (metricas_logs 1 punto suma)(todas las features)
                                               precision    recall  f1-score   support

           access_token_auth_header_error_401       0.94      0.98      0.96        65
          access_token_authorization_form_401       0.49      0.62      0.54        65
         access_token_client_id_not_found_404       1.00      0.98      0.99        65
         access_token_client_secret_wrong_401       0.98      0.98      0.98        65
             access_token_form_urlencoded_400       0.70      0.66      0.68        65
          access_token_illegal_grant_type_400       0.98      1.00      0.99        65
access_token_missing_authorization_header_400       0.50      0.46      0.48        65
     authorization_code_client_id_missing_400       0.84      0.83      0.84        65
     authorization_code_invalid_client_id_404       0.79      0.80      0.79        65
      authorization_code_invalid_password_401       0.98      0.85      0.91        65
 authorization_code_missing_response_type_400       0.68      0.74      0.71        65
     authorization_code_response_not_code_400       0.77      0.75      0.76        65
       code_challenge_invalid_format_pkce_400       0.60      0.69      0.64        65
             code_challenge_too_long_pkce_400       0.61      0.52      0.56        65
            code_challenge_too_short_pkce_400       0.35      0.32      0.34        65
               code_verifier_missing_pkce_400       0.59      0.65      0.62        65
              code_verifier_too_long_pkce_400       0.14      0.12      0.13        65
             code_verifier_too_short_pkce_400       0.21      0.18      0.20        65
                  delete_client_404_no_client       1.00      1.00      1.00        65
                delete_service_404_no_service       0.75      0.80      0.78        65
                             delete_token_404       0.51      0.62      0.56        65
                      delete_user_404_no_user       0.20      0.17      0.18        65
                     get_client_404_no_client       0.94      1.00      0.97        65
                  get_client_page_400_no_page       1.00      1.00      1.00        65
                   get_service_404_no_service       0.32      0.46      0.38        65
                 get_service_page_400_no_page       0.87      0.89      0.88        65
                                get_token_404       0.33      0.29      0.31        65
                   get_token_page_400_no_page       0.56      0.60      0.58        65
                         get_user_404_no_user       0.31      0.20      0.24        65
                    get_user_page_400_no_page       0.43      0.62      0.51        65
       invalid_code_challenge_method_pkce_400       0.78      0.80      0.79        65
        invalid_code_verifier_format_PKCE_400       0.21      0.15      0.18        65
            register_client_400_clientProfile       0.92      0.92      0.92        65
               register_client_400_clientType       0.92      0.89      0.91        65
                  register_client_404_no_user       0.93      0.83      0.88        65
              register_service_400_service_id       0.91      0.82      0.86        65
            register_service_400_service_type       0.80      0.92      0.86        65
                 register_service_404_no_user       0.69      0.80      0.74        65
               register_user_400_email_exists       0.71      0.68      0.69        65
                register_user_400_no_password       0.54      0.66      0.60        65
          register_user_400_password_no_match       0.82      0.62      0.70        65
                register_user_400_user_exists       0.58      0.69      0.63        65
              update_client_400_clientProfile       1.00      0.97      0.98        65
                 update_client_400_clientType       0.98      1.00      0.99        65
                   update_client_404_clientId       0.32      0.37      0.34        65
                    update_client_404_ownerId       0.95      0.63      0.76        65
                update_password_400_not_match       0.64      0.63      0.64        65
           update_password_401_wrong_password       0.33      0.31      0.32        65
           update_password_404_user_not_found       0.21      0.17      0.19        65
                update_service_404_service_id       0.83      0.77      0.80        65
                   update_service_404_user_id       0.82      0.78      0.80        65
                      update_user_404_no_user       0.60      0.65      0.62        65
                 verification_failed_pkce_400       0.23      0.23      0.23        65

                                     accuracy                           0.66      3445
                                    macro avg       0.66      0.66      0.66      3445
                                 weighted avg       0.66      0.66      0.66      3445

['result/models/LightGBM (metricas_logs 1 punto suma)(todas las features).joblib']

In [69]:
df_importancias_agrupada, importancias, num_cero = obtener_importancias_agrupadas(paquete_modelo['model'].feature_importances_, paquete_modelo['lista_features'])
print(f"Características con importancia cero: {num_cero}")

Características con importancia cero: 53

In [72]:
n_min = 172
n_max = len(importancias) - num_cero


# --- VARIABLES PARA EL EARLY STOPPING ---
paciencia = 15
iteraciones_sin_mejora = 0
mejor_score_global = -1.0
mejor_paquete_modelo = None

for N_feat in range(n_min, n_max + 1):
    model_name = f'{nombre_algoritmo} ({DATOS})   N_feat={N_feat}'
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:N_feat]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(feature)

    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    


    # --- LÓGICA DE EARLY STOPPING ---
    score_actual = macro_f1 
    
    if score_actual > mejor_score_global:
        mejor_score_global = score_actual
        mejor_paquete_modelo = paquete_modelo.copy()
        iteraciones_sin_mejora = 0  # Reiniciamos contador si mejora
    else:
        iteraciones_sin_mejora += 1

    # --- IMPRESIÓN EN UNA SOLA LÍNEA ---
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Mejor Macro F1 = {mejor_score_global:.4f} | Iteraciones_sin_mejora = {iteraciones_sin_mejora}")
    del X_train_sub, X_test_sub
    gc.collect()
    
    # Comprobación de parada
    if iteraciones_sin_mejora >= paciencia:
        print(f"\n[!] Early Stopping activado: No ha habido mejoras en {paciencia} iteraciones consecutivas.")
        print(f"Deteniendo búsqueda. El mejor modelo se logró con {mejor_paquete_modelo['N_features_unicas']} características base.")
        break

Model = LightGBM (metricas_logs 1 punto suma)   N_feat=172 Accuracy = 0.6543 | Macro F1 = 0.6525 | Macro Precision = 0.6575 | Macro Recall = 0.6543 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=173 Accuracy = 0.6528 | Macro F1 = 0.6505 | Macro Precision = 0.6545 | Macro Recall = 0.6528 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 1
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=174 Accuracy = 0.6537 | Macro F1 = 0.6512 | Macro Precision = 0.6547 | Macro Recall = 0.6537 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 2
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=175 Accuracy = 0.6499 | Macro F1 = 0.6481 | Macro Precision = 0.6519 | Macro Recall = 0.6499 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 3
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=176 Accuracy = 0.6522 | Macro F1 = 0.6498 | Macro Precision = 0.6526 | Macro Recall = 0.6522 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 4
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=177 Accuracy = 0.6514 | Macro F1 = 0.6483 | Macro Precision = 0.6515 | Macro Recall = 0.6514 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 5
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=178 Accuracy = 0.6499 | Macro F1 = 0.6473 | Macro Precision = 0.6500 | Macro Recall = 0.6499 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 6
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=179 Accuracy = 0.6502 | Macro F1 = 0.6482 | Macro Precision = 0.6514 | Macro Recall = 0.6502 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 7
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=180 Accuracy = 0.6502 | Macro F1 = 0.6480 | Macro Precision = 0.6509 | Macro Recall = 0.6502 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 8
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=181 Accuracy = 0.6476 | Macro F1 = 0.6460 | Macro Precision = 0.6505 | Macro Recall = 0.6476 | Mejor Macro F1 = 0.6525 | Iteraciones_sin_mejora = 9
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=182 Accuracy = 0.6586 | Macro F1 = 0.6567 | Macro Precision = 0.6598 | Macro Recall = 0.6586 | Mejor Macro F1 = 0.6567 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=183 Accuracy = 0.6604 | Macro F1 = 0.6585 | Macro Precision = 0.6614 | Macro Recall = 0.6604 | Mejor Macro F1 = 0.6585 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=184 Accuracy = 0.6627 | Macro F1 = 0.6608 | Macro Precision = 0.6646 | Macro Recall = 0.6627 | Mejor Macro F1 = 0.6608 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=185 Accuracy = 0.6575 | Macro F1 = 0.6546 | Macro Precision = 0.6570 | Macro Recall = 0.6575 | Mejor Macro F1 = 0.6608 | Iteraciones_sin_mejora = 1
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=186 Accuracy = 0.6627 | Macro F1 = 0.6603 | Macro Precision = 0.6634 | Macro Recall = 0.6627 | Mejor Macro F1 = 0.6608 | Iteraciones_sin_mejora = 2
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=187 Accuracy = 0.6642 | Macro F1 = 0.6617 | Macro Precision = 0.6639 | Macro Recall = 0.6642 | Mejor Macro F1 = 0.6617 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=188 Accuracy = 0.6607 | Macro F1 = 0.6581 | Macro Precision = 0.6604 | Macro Recall = 0.6607 | Mejor Macro F1 = 0.6617 | Iteraciones_sin_mejora = 1
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=189 Accuracy = 0.6633 | Macro F1 = 0.6607 | Macro Precision = 0.6638 | Macro Recall = 0.6633 | Mejor Macro F1 = 0.6617 | Iteraciones_sin_mejora = 2
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=190 Accuracy = 0.6633 | Macro F1 = 0.6604 | Macro Precision = 0.6633 | Macro Recall = 0.6633 | Mejor Macro F1 = 0.6617 | Iteraciones_sin_mejora = 3
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=191 Accuracy = 0.6627 | Macro F1 = 0.6601 | Macro Precision = 0.6625 | Macro Recall = 0.6627 | Mejor Macro F1 = 0.6617 | Iteraciones_sin_mejora = 4
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=192 Accuracy = 0.6557 | Macro F1 = 0.6535 | Macro Precision = 0.6568 | Macro Recall = 0.6557 | Mejor Macro F1 = 0.6617 | Iteraciones_sin_mejora = 5
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=193 Accuracy = 0.6656 | Macro F1 = 0.6624 | Macro Precision = 0.6650 | Macro Recall = 0.6656 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=194 Accuracy = 0.6612 | Macro F1 = 0.6592 | Macro Precision = 0.6621 | Macro Recall = 0.6612 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 1
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=195 Accuracy = 0.6639 | Macro F1 = 0.6607 | Macro Precision = 0.6629 | Macro Recall = 0.6639 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 2
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=196 Accuracy = 0.6566 | Macro F1 = 0.6544 | Macro Precision = 0.6571 | Macro Recall = 0.6566 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 3
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=197 Accuracy = 0.6636 | Macro F1 = 0.6602 | Macro Precision = 0.6629 | Macro Recall = 0.6636 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 4
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=198 Accuracy = 0.6636 | Macro F1 = 0.6614 | Macro Precision = 0.6644 | Macro Recall = 0.6636 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 5
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=199 Accuracy = 0.6653 | Macro F1 = 0.6623 | Macro Precision = 0.6644 | Macro Recall = 0.6653 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 6
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=200 Accuracy = 0.6644 | Macro F1 = 0.6624 | Macro Precision = 0.6658 | Macro Recall = 0.6644 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 7
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=201 Accuracy = 0.6644 | Macro F1 = 0.6612 | Macro Precision = 0.6641 | Macro Recall = 0.6644 | Mejor Macro F1 = 0.6624 | Iteraciones_sin_mejora = 8
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=202 Accuracy = 0.6676 | Macro F1 = 0.6648 | Macro Precision = 0.6669 | Macro Recall = 0.6676 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 0
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=203 Accuracy = 0.6612 | Macro F1 = 0.6588 | Macro Precision = 0.6609 | Macro Recall = 0.6612 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 1
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=204 Accuracy = 0.6656 | Macro F1 = 0.6633 | Macro Precision = 0.6664 | Macro Recall = 0.6656 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 2
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=205 Accuracy = 0.6627 | Macro F1 = 0.6600 | Macro Precision = 0.6627 | Macro Recall = 0.6627 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 3
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=206 Accuracy = 0.6583 | Macro F1 = 0.6556 | Macro Precision = 0.6584 | Macro Recall = 0.6583 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 4
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=207 Accuracy = 0.6642 | Macro F1 = 0.6619 | Macro Precision = 0.6641 | Macro Recall = 0.6642 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 5
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=208 Accuracy = 0.6673 | Macro F1 = 0.6646 | Macro Precision = 0.6672 | Macro Recall = 0.6673 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 6
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=209 Accuracy = 0.6586 | Macro F1 = 0.6564 | Macro Precision = 0.6591 | Macro Recall = 0.6586 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 7
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=210 Accuracy = 0.6589 | Macro F1 = 0.6572 | Macro Precision = 0.6603 | Macro Recall = 0.6589 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 8
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=211 Accuracy = 0.6621 | Macro F1 = 0.6599 | Macro Precision = 0.6627 | Macro Recall = 0.6621 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 9
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=212 Accuracy = 0.6633 | Macro F1 = 0.6614 | Macro Precision = 0.6652 | Macro Recall = 0.6633 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 10
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=213 Accuracy = 0.6636 | Macro F1 = 0.6602 | Macro Precision = 0.6624 | Macro Recall = 0.6636 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 11
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=214 Accuracy = 0.6665 | Macro F1 = 0.6634 | Macro Precision = 0.6662 | Macro Recall = 0.6665 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 12
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=215 Accuracy = 0.6583 | Macro F1 = 0.6560 | Macro Precision = 0.6589 | Macro Recall = 0.6583 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 13
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=216 Accuracy = 0.6598 | Macro F1 = 0.6570 | Macro Precision = 0.6602 | Macro Recall = 0.6598 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 14
Model = LightGBM (metricas_logs 1 punto suma)   N_feat=217 Accuracy = 0.6630 | Macro F1 = 0.6602 | Macro Precision = 0.6629 | Macro Recall = 0.6630 | Mejor Macro F1 = 0.6648 | Iteraciones_sin_mejora = 15

[!] Early Stopping activado: No ha habido mejoras en 15 iteraciones consecutivas.
Deteniendo búsqueda. El mejor modelo se logró con 202 características base.

In [73]:
mejor_paquete_modelo['model_name']

'LightGBM (metricas_logs 1 punto suma)   N_feat=202'

In [74]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

['result/models/LightGBM (metricas_logs 1 punto suma)   N_feat=202.joblib']

In [81]:
paquete_modelo = mejor_paquete_modelo.copy()

mejor_macro_f1_global    = paquete_modelo['resultado']['f1']
mejor_features_global    = paquete_modelo['lista_features'].copy()
pasos_sin_mejora         = 0
limite_puntos_sin_mejora = paciencia + 5

print(f"Iniciando eliminación recursiva desde {paquete_modelo['N_features_unicas']} características.\n")

while paquete_modelo['N_features_unicas'] > 1 and pasos_sin_mejora < limite_puntos_sin_mejora:
    N_feat = paquete_modelo['N_features_unicas']
    
    # Extraer importancias y características actuales
    importancias_raw = paquete_modelo['model'].feature_importances_
    features_raw = paquete_modelo['lista_features']
    
    df_importancias_agrupada, _, num_cero = obtener_importancias_agrupadas(importancias_raw, features_raw)

    # Seleccionar características para el siguiente paso
    lista_features_sel = []
    for feature in df_importancias_agrupada['caracteristica'].to_list()[:(N_feat-1)]:
        if N_puntos>1:
            for lag in range(0, N_puntos):
                lista_features_sel.append(f'{feature}(lag_{lag})')
        else:
            lista_features_sel.append(f'{feature}')

        
    X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
    X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
   
    clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
    clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

    model_name = f'{nombre_algoritmo} (metricas_log) N_feat={N_feat-1}'
    paquete_modelo = {}
    paquete_modelo['model_name']          = model_name
    paquete_modelo['model']               = clf_anomalias_opt
    paquete_modelo['parametros']          = mejores_params
    paquete_modelo['lista_features']      = lista_features_sel
    paquete_modelo['N_features']          = len(paquete_modelo['lista_features'])
    paquete_modelo['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_modelo['lista_features']))
    paquete_modelo['datos']               = 'metricas_log_lags'
    paquete_modelo['algoritmo']           = nombre_algoritmo
    
    resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_modelo, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
   
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    

    
    if macro_f1 >= mejor_macro_f1_global:
        mejor_macro_f1_global = macro_f1
        mejor_features_global = paquete_modelo['lista_features'].copy()
        pasos_sin_mejora = 0  
        mejor_paquete_modelo = paquete_modelo.copy()
    else:
        pasos_sin_mejora += 1  
        
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f} | Sin mejora: {pasos_sin_mejora}")
    del X_train_sub, X_test_sub, importancias_raw, df_importancias_agrupada
    gc.collect()

print(f"\n¡Proceso finalizado!")
print(f"Mejor Macro F1 alcanzado: {mejor_macro_f1_global:.4f}")
print(f"Número óptimo de características base: {len(mejor_features_global)}")

Iniciando eliminación recursiva desde 202 características.

Model = LightGBM (metricas_log) N_feat=201       Accuracy = 0.6612 | Macro F1 = 0.6584 | Macro Precision = 0.6617 | Macro Recall = 0.6612 | Sin mejora: 1
Model = LightGBM (metricas_log) N_feat=200       Accuracy = 0.6621 | Macro F1 = 0.6597 | Macro Precision = 0.6621 | Macro Recall = 0.6621 | Sin mejora: 2
Model = LightGBM (metricas_log) N_feat=199       Accuracy = 0.6650 | Macro F1 = 0.6623 | Macro Precision = 0.6646 | Macro Recall = 0.6650 | Sin mejora: 3
Model = LightGBM (metricas_log) N_feat=198       Accuracy = 0.6615 | Macro F1 = 0.6590 | Macro Precision = 0.6616 | Macro Recall = 0.6615 | Sin mejora: 4
Model = LightGBM (metricas_log) N_feat=197       Accuracy = 0.6610 | Macro F1 = 0.6589 | Macro Precision = 0.6629 | Macro Recall = 0.6610 | Sin mejora: 5
Model = LightGBM (metricas_log) N_feat=196       Accuracy = 0.6578 | Macro F1 = 0.6553 | Macro Precision = 0.6575 | Macro Recall = 0.6578 | Sin mejora: 6
Model = LightGBM (metricas_log) N_feat=195       Accuracy = 0.6496 | Macro F1 = 0.6480 | Macro Precision = 0.6530 | Macro Recall = 0.6496 | Sin mejora: 7
Model = LightGBM (metricas_log) N_feat=194       Accuracy = 0.6430 | Macro F1 = 0.6403 | Macro Precision = 0.6433 | Macro Recall = 0.6430 | Sin mejora: 8
Model = LightGBM (metricas_log) N_feat=193       Accuracy = 0.6511 | Macro F1 = 0.6481 | Macro Precision = 0.6512 | Macro Recall = 0.6511 | Sin mejora: 9
Model = LightGBM (metricas_log) N_feat=192       Accuracy = 0.6482 | Macro F1 = 0.6460 | Macro Precision = 0.6499 | Macro Recall = 0.6482 | Sin mejora: 10
Model = LightGBM (metricas_log) N_feat=191       Accuracy = 0.6511 | Macro F1 = 0.6483 | Macro Precision = 0.6512 | Macro Recall = 0.6511 | Sin mejora: 11
Model = LightGBM (metricas_log) N_feat=190       Accuracy = 0.6502 | Macro F1 = 0.6483 | Macro Precision = 0.6521 | Macro Recall = 0.6502 | Sin mejora: 12
Model = LightGBM (metricas_log) N_feat=189       Accuracy = 0.6282 | Macro F1 = 0.6252 | Macro Precision = 0.6279 | Macro Recall = 0.6282 | Sin mejora: 13
Model = LightGBM (metricas_log) N_feat=188       Accuracy = 0.6241 | Macro F1 = 0.6218 | Macro Precision = 0.6250 | Macro Recall = 0.6241 | Sin mejora: 14
Model = LightGBM (metricas_log) N_feat=187       Accuracy = 0.6253 | Macro F1 = 0.6230 | Macro Precision = 0.6278 | Macro Recall = 0.6253 | Sin mejora: 15
Model = LightGBM (metricas_log) N_feat=186       Accuracy = 0.6258 | Macro F1 = 0.6238 | Macro Precision = 0.6277 | Macro Recall = 0.6258 | Sin mejora: 16
Model = LightGBM (metricas_log) N_feat=185       Accuracy = 0.6284 | Macro F1 = 0.6266 | Macro Precision = 0.6305 | Macro Recall = 0.6284 | Sin mejora: 17
Model = LightGBM (metricas_log) N_feat=184       Accuracy = 0.6273 | Macro F1 = 0.6253 | Macro Precision = 0.6291 | Macro Recall = 0.6273 | Sin mejora: 18
Model = LightGBM (metricas_log) N_feat=183       Accuracy = 0.6267 | Macro F1 = 0.6242 | Macro Precision = 0.6277 | Macro Recall = 0.6267 | Sin mejora: 19
Model = LightGBM (metricas_log) N_feat=182       Accuracy = 0.6232 | Macro F1 = 0.6225 | Macro Precision = 0.6273 | Macro Recall = 0.6232 | Sin mejora: 20

¡Proceso finalizado!
Mejor Macro F1 alcanzado: 0.6648
Número óptimo de características base: 202

In [62]:
mejor_paquete_modelo = joblib.load('result/models/LightGBM (metricas_logs 1 punto suma) N_feat=192.joblib')
mejores_params=mejor_paquete_modelo['parametros']
paquete_modelo = mejor_paquete_modelo.copy()
print('Resultado del mejor modelo de partida:')
print(mejor_paquete_modelo['resultado'])
print(f'N_features = {mejor_paquete_modelo["N_features"]}')
mejor_macro_f1_global=paquete_modelo['resultado']['f1']


paquete_modelo = mejor_paquete_modelo.copy()
mejor_features_global    = paquete_modelo['lista_features'].copy()

pasos_sin_mejora         = 0
limite_puntos_sin_mejora = 20
ratio_prueba             = 0.1

print(f"Iniciando eliminación recursiva inteligente (10% peor) desde {paquete_modelo['N_features_unicas']} características.\n")

while paquete_modelo['N_features_unicas'] > 1 and pasos_sin_mejora < limite_puntos_sin_mejora:
    N_feat_actual = paquete_modelo['N_features_unicas']
    
    # 1. Extraer importancias y ordenarlas de mayor a menor
    importancias_raw = paquete_modelo['model'].feature_importances_
    features_raw = paquete_modelo['lista_features']
    df_importancias_agrupada, _, num_cero = obtener_importancias_agrupadas(importancias_raw, features_raw)
    
    lista_features_base_ordenada = df_importancias_agrupada['caracteristica'].to_list()
    
    # Definir cuántas candidatas por la cola vamos a probar (el 10%, mínimo 1, máximo las disponibles)
    num_candidatas_quitar = max(1, int(N_feat_actual * ratio_prueba))
    # Nos aseguramos de no intentar quitar más de las que hay
    num_candidatas_quitar = min(num_candidatas_quitar, N_feat_actual - 1)
    
    print(f"\n--- Evaluando reducción desde {N_feat_actual} features. Probando las {num_candidatas_quitar} peores candidatas ---")
    
    mejor_paquete_iteracion = None
    mejor_f1_iteracion = -1.0
    
    # 2. Probar a quitar una a una las peores candidatas (las que están al final de la lista)
    mejor_intento = 0
    for i in range(num_candidatas_quitar):
        intento_num = i + 1
        print(f"  [Intento {intento_num:3d}/{num_candidatas_quitar:3d}] Probando modelo de {N_feat_actual - 1} features...", end=" ")
        
        # Creamos la lista de características base quitando la candidata de la posición desde el final
        # i=0 quita la peores de todas, i=1 quita la penúltima peor, etc.
        indice_a_excluir = len(lista_features_base_ordenada) - 1 - i
        features_base_prueba = [f for idx, f in enumerate(lista_features_base_ordenada) if idx != indice_a_excluir]
        
        # Generar lista de features con sus lags
        lista_features_sel = []
        for feature in features_base_prueba:
            if N_puntos > 1:
                for lag in range(0, N_puntos):
                    lista_features_sel.append(f'{feature}(lag_{lag})')
            else:
                lista_features_sel.append(f'{feature}')
                
        # Entrenar modelo de prueba
        X_train_sub = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_train, lista_feature_sel=lista_features_sel)
        X_test_sub  = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test,  lista_feature_sel=lista_features_sel)
       
        clf_anomalias_opt = ALGORITMO_CLASIFICADOR(**mejores_params)
        clf_anomalias_opt.fit(X_train_sub, Y_train_encoded)

        model_name = f'{nombre_algoritmo} ({DATOS}) N_feat={N_feat_actual - 1}'
        paquete_prueba = {}
        paquete_prueba['model_name']          = model_name
        paquete_prueba['model']               = clf_anomalias_opt
        paquete_prueba['parametros']          = mejores_params
        paquete_prueba['lista_features']      = lista_features_sel
        paquete_prueba['N_features']          = len(paquete_prueba['lista_features'])
        paquete_prueba['N_features_unicas']   = len(get_lista_feature_sin_lag(paquete_prueba['lista_features']))
        paquete_prueba['datos']               = 'metricas_log_lags'
        paquete_prueba['algoritmo']           = nombre_algoritmo
        
        resultado, reporte_dict, Y_pred_probabilidades = evaluar_modelo(paquete_prueba, lista_features, X_test, Y_test_etiquetas, encoder_etiquetas)
        
        acc_p   = resultado['accuracy']
        f1_p    = resultado['f1']
        prec_p  = resultado['precision']
        rec_p   = resultado['recall']
        
        paquete_prueba['resultado'] = resultado
        
        print(f"F1 = {f1_p:.4f} (Acc = {acc_p:.4f})")
        
        del X_train_sub, X_test_sub
        gc.collect()
        
        # Guardar si es el mejor de este subgrupo de pruebas
        if f1_p > mejor_f1_iteracion:
            mejor_intento = intento_num
            mejor_f1_iteracion = f1_p
            mejor_paquete_iteracion = paquete_prueba.copy()
            if mejor_f1_iteracion >= mejor_macro_f1_global:
                break
            


    
    print(f'Mejor intento = {mejor_intento}')
    # 3. Comprobar si el mejor de los modelos reducidos mejora o iguala al global actual
    if mejor_f1_iteracion >= mejor_macro_f1_global:
        mejor_macro_f1_global = mejor_f1_iteracion
        mejor_features_global = mejor_paquete_iteracion['lista_features'].copy()
        pasos_sin_mejora = 0  
        paquete_modelo = mejor_paquete_iteracion.copy()
        mejor_paquete_modelo = paquete_modelo.copy()
        print(f"-> ¡Mejora encontrada! Nuevo mejor Macro F1 global: {mejor_macro_f1_global:.4f} con {paquete_modelo['N_features_unicas']} features.")
    else:
        # Si ninguno del 10% mejoró al padre, aumentamos el contador de pasos sin mejora pero avanzamos con el mejor intento o paramos
        pasos_sin_mejora += 1
        # Opcional: penalizamos avanzando al mejor de los probados para no estancarnos en bucle infinito
        paquete_modelo = mejor_paquete_iteracion.copy()
        print(f"-> Sin mejora global en este ciclo. Pasos sin mejora: {pasos_sin_mejora}")
        
    resultado = paquete_modelo['resultado']
    accuracy        = resultado['accuracy']
    macro_f1        = resultado['f1']
    macro_precision = resultado['precision']
    macro_recall    = resultado['recall']
    print(f"Model = {model_name:40s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f}")

print(f"\n¡Proceso finalizado!")
print(f"Mejor Macro F1 alcanzado: {mejor_macro_f1_global:.4f}")
print(f"Número óptimo de características base: {len(mejor_features_global)}")

Resultado del mejor modelo de partida:
{'accuracy': 0.6679245283018868, 'precision': 0.6682365199654308, 'recall': 0.6679245283018868, 'f1': 0.6654290065318454}
N_features = 192
Iniciando eliminación recursiva inteligente (10% peor) desde 192 características.


--- Evaluando reducción desde 192 features. Probando las 19 peores candidatas ---
  [Intento   1/ 19] Probando modelo de 191 features... F1 = 0.6585 (Acc = 0.6615)
  [Intento   2/ 19] Probando modelo de 191 features... F1 = 0.6597 (Acc = 0.6624)
  [Intento   3/ 19] Probando modelo de 191 features... F1 = 0.6610 (Acc = 0.6642)
  [Intento   4/ 19] Probando modelo de 191 features... F1 = 0.6626 (Acc = 0.6644)
  [Intento   5/ 19] Probando modelo de 191 features... F1 = 0.6585 (Acc = 0.6610)
  [Intento   6/ 19] Probando modelo de 191 features... F1 = 0.6611 (Acc = 0.6630)
  [Intento   7/ 19] Probando modelo de 191 features... F1 = 0.6575 (Acc = 0.6610)
  [Intento   8/ 19] Probando modelo de 191 features... F1 = 0.6601 (Acc = 0.6633)
  [Intento   9/ 19] Probando modelo de 191 features... F1 = 0.6543 (Acc = 0.6566)
  [Intento  10/ 19] Probando modelo de 191 features... F1 = 0.6604 (Acc = 0.6633)
  [Intento  11/ 19] Probando modelo de 191 features... F1 = 0.6584 (Acc = 0.6615)
  [Intento  12/ 19] Probando modelo de 191 features... F1 = 0.6630 (Acc = 0.6653)
  [Intento  13/ 19] Probando modelo de 191 features... F1 = 0.6047 (Acc = 0.6073)
  [Intento  14/ 19] Probando modelo de 191 features... F1 = 0.6564 (Acc = 0.6598)
  [Intento  15/ 19] Probando modelo de 191 features... F1 = 0.6649 (Acc = 0.6665)
  [Intento  16/ 19] Probando modelo de 191 features... F1 = 0.6570 (Acc = 0.6595)
  [Intento  17/ 19] Probando modelo de 191 features... F1 = 0.6594 (Acc = 0.6621)
  [Intento  18/ 19] Probando modelo de 191 features... F1 = 0.6620 (Acc = 0.6653)
  [Intento  19/ 19] Probando modelo de 191 features... F1 = 0.6544 (Acc = 0.6566)
Mejor intento = 15
-> Sin mejora global en este ciclo. Pasos sin mejora: 1
Model = LightGBM (metricas_logs 1 punto suma) N_feat=191 Accuracy = 0.6665 | Macro F1 = 0.6649 | Macro Precision = 0.6681 | Macro Recall = 0.6665

--- Evaluando reducción desde 191 features. Probando las 19 peores candidatas ---
  [Intento   1/ 19] Probando modelo de 190 features... F1 = 0.6619 (Acc = 0.6639)
  [Intento   2/ 19] Probando modelo de 190 features... F1 = 0.6602 (Acc = 0.6636)
  [Intento   3/ 19] Probando modelo de 190 features... F1 = 0.6636 (Acc = 0.6656)
  [Intento   4/ 19] Probando modelo de 190 features... F1 = 0.6539 (Acc = 0.6552)
  [Intento   5/ 19] Probando modelo de 190 features... F1 = 0.6592 (Acc = 0.6612)
  [Intento   6/ 19] Probando modelo de 190 features... F1 = 0.6561 (Acc = 0.6583)
  [Intento   7/ 19] Probando modelo de 190 features... F1 = 0.6617 (Acc = 0.6644)
  [Intento   8/ 19] Probando modelo de 190 features... F1 = 0.6584 (Acc = 0.6607)
  [Intento   9/ 19] Probando modelo de 190 features... F1 = 0.6618 (Acc = 0.6647)
  [Intento  10/ 19] Probando modelo de 190 features... F1 = 0.6028 (Acc = 0.6064)
  [Intento  11/ 19] Probando modelo de 190 features... F1 = 0.6625 (Acc = 0.6650)
  [Intento  12/ 19] Probando modelo de 190 features... F1 = 0.6594 (Acc = 0.6618)
  [Intento  13/ 19] Probando modelo de 190 features... F1 = 0.6615 (Acc = 0.6650)
  [Intento  14/ 19] Probando modelo de 190 features... F1 = 0.6616 (Acc = 0.6642)
  [Intento  15/ 19] Probando modelo de 190 features... F1 = 0.6609 (Acc = 0.6633)
  [Intento  16/ 19] Probando modelo de 190 features... F1 = 0.6596 (Acc = 0.6615)
  [Intento  17/ 19] Probando modelo de 190 features... F1 = 0.6563 (Acc = 0.6583)
  [Intento  18/ 19] Probando modelo de 190 features... F1 = 0.6627 (Acc = 0.6647)
  [Intento  19/ 19] Probando modelo de 190 features... F1 = 0.6622 (Acc = 0.6650)
Mejor intento = 3
-> Sin mejora global en este ciclo. Pasos sin mejora: 2
Model = LightGBM (metricas_logs 1 punto suma) N_feat=190 Accuracy = 0.6656 | Macro F1 = 0.6636 | Macro Precision = 0.6668 | Macro Recall = 0.6656

--- Evaluando reducción desde 190 features. Probando las 19 peores candidatas ---
  [Intento   1/ 19] Probando modelo de 189 features... F1 = 0.6601 (Acc = 0.6624)
  [Intento   2/ 19] Probando modelo de 189 features... F1 = 0.6604 (Acc = 0.6630)
  [Intento   3/ 19] Probando modelo de 189 features... F1 = 0.6658 (Acc = 0.6682)
Mejor intento = 3
-> ¡Mejora encontrada! Nuevo mejor Macro F1 global: 0.6658 con 189 features.
Model = LightGBM (metricas_logs 1 punto suma) N_feat=189 Accuracy = 0.6682 | Macro F1 = 0.6658 | Macro Precision = 0.6695 | Macro Recall = 0.6682

--- Evaluando reducción desde 189 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 188 features... F1 = 0.6546 (Acc = 0.6566)
  [Intento   2/ 18] Probando modelo de 188 features... F1 = 0.6625 (Acc = 0.6644)
  [Intento   3/ 18] Probando modelo de 188 features... F1 = 0.6593 (Acc = 0.6627)
  [Intento   4/ 18] Probando modelo de 188 features... F1 = 0.6360 (Acc = 0.6377)
  [Intento   5/ 18] Probando modelo de 188 features... F1 = 0.6604 (Acc = 0.6627)
  [Intento   6/ 18] Probando modelo de 188 features... F1 = 0.6608 (Acc = 0.6636)
  [Intento   7/ 18] Probando modelo de 188 features... F1 = 0.6593 (Acc = 0.6621)
  [Intento   8/ 18] Probando modelo de 188 features... F1 = 0.6623 (Acc = 0.6644)
  [Intento   9/ 18] Probando modelo de 188 features... F1 = 0.6581 (Acc = 0.6601)
  [Intento  10/ 18] Probando modelo de 188 features... F1 = 0.6652 (Acc = 0.6679)
  [Intento  11/ 18] Probando modelo de 188 features... F1 = 0.6586 (Acc = 0.6607)
  [Intento  12/ 18] Probando modelo de 188 features... F1 = 0.6653 (Acc = 0.6673)
  [Intento  13/ 18] Probando modelo de 188 features... F1 = 0.6619 (Acc = 0.6639)
  [Intento  14/ 18] Probando modelo de 188 features... F1 = 0.6574 (Acc = 0.6601)
  [Intento  15/ 18] Probando modelo de 188 features... F1 = 0.6589 (Acc = 0.6601)
  [Intento  16/ 18] Probando modelo de 188 features... F1 = 0.6628 (Acc = 0.6644)
  [Intento  17/ 18] Probando modelo de 188 features... F1 = 0.6545 (Acc = 0.6566)
  [Intento  18/ 18] Probando modelo de 188 features... F1 = 0.6534 (Acc = 0.6560)
Mejor intento = 12
-> Sin mejora global en este ciclo. Pasos sin mejora: 1
Model = LightGBM (metricas_logs 1 punto suma) N_feat=188 Accuracy = 0.6673 | Macro F1 = 0.6653 | Macro Precision = 0.6694 | Macro Recall = 0.6673

--- Evaluando reducción desde 188 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 187 features... F1 = 0.6592 (Acc = 0.6607)
  [Intento   2/ 18] Probando modelo de 187 features... F1 = 0.6595 (Acc = 0.6610)
  [Intento   3/ 18] Probando modelo de 187 features... F1 = 0.6598 (Acc = 0.6618)
  [Intento   4/ 18] Probando modelo de 187 features... F1 = 0.6603 (Acc = 0.6627)
  [Intento   5/ 18] Probando modelo de 187 features... F1 = 0.6575 (Acc = 0.6598)
  [Intento   6/ 18] Probando modelo de 187 features... F1 = 0.6618 (Acc = 0.6644)
  [Intento   7/ 18] Probando modelo de 187 features... F1 = 0.6618 (Acc = 0.6642)
  [Intento   8/ 18] Probando modelo de 187 features... F1 = 0.6563 (Acc = 0.6581)
  [Intento   9/ 18] Probando modelo de 187 features... F1 = 0.6563 (Acc = 0.6592)
  [Intento  10/ 18] Probando modelo de 187 features... F1 = 0.6592 (Acc = 0.6610)
  [Intento  11/ 18] Probando modelo de 187 features... F1 = 0.6590 (Acc = 0.6607)
  [Intento  12/ 18] Probando modelo de 187 features... F1 = 0.6623 (Acc = 0.6642)
  [Intento  13/ 18] Probando modelo de 187 features... F1 = 0.6605 (Acc = 0.6627)
  [Intento  14/ 18] Probando modelo de 187 features... F1 = 0.6598 (Acc = 0.6621)
  [Intento  15/ 18] Probando modelo de 187 features... F1 = 0.6519 (Acc = 0.6537)
  [Intento  16/ 18] Probando modelo de 187 features... F1 = 0.6585 (Acc = 0.6610)
  [Intento  17/ 18] Probando modelo de 187 features... F1 = 0.6588 (Acc = 0.6607)
  [Intento  18/ 18] Probando modelo de 187 features... F1 = 0.6337 (Acc = 0.6348)
Mejor intento = 12
-> Sin mejora global en este ciclo. Pasos sin mejora: 2
Model = LightGBM (metricas_logs 1 punto suma) N_feat=187 Accuracy = 0.6642 | Macro F1 = 0.6623 | Macro Precision = 0.6662 | Macro Recall = 0.6642

--- Evaluando reducción desde 187 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 186 features... F1 = 0.6504 (Acc = 0.6522)
  [Intento   2/ 18] Probando modelo de 186 features... F1 = 0.6608 (Acc = 0.6633)
  [Intento   3/ 18] Probando modelo de 186 features... F1 = 0.6592 (Acc = 0.6607)
  [Intento   4/ 18] Probando modelo de 186 features... F1 = 0.6635 (Acc = 0.6650)
  [Intento   5/ 18] Probando modelo de 186 features... F1 = 0.6620 (Acc = 0.6636)
  [Intento   6/ 18] Probando modelo de 186 features... F1 = 0.6582 (Acc = 0.6604)
  [Intento   7/ 18] Probando modelo de 186 features... F1 = 0.6592 (Acc = 0.6604)
  [Intento   8/ 18] Probando modelo de 186 features... F1 = 0.6602 (Acc = 0.6610)
  [Intento   9/ 18] Probando modelo de 186 features... F1 = 0.6584 (Acc = 0.6604)
  [Intento  10/ 18] Probando modelo de 186 features... F1 = 0.6647 (Acc = 0.6673)
  [Intento  11/ 18] Probando modelo de 186 features... F1 = 0.6624 (Acc = 0.6642)
  [Intento  12/ 18] Probando modelo de 186 features... F1 = 0.6611 (Acc = 0.6633)
  [Intento  13/ 18] Probando modelo de 186 features... F1 = 0.6564 (Acc = 0.6586)
  [Intento  14/ 18] Probando modelo de 186 features... F1 = 0.6584 (Acc = 0.6604)
  [Intento  15/ 18] Probando modelo de 186 features... F1 = 0.6617 (Acc = 0.6639)
  [Intento  16/ 18] Probando modelo de 186 features... F1 = 0.6593 (Acc = 0.6607)
  [Intento  17/ 18] Probando modelo de 186 features... F1 = 0.6609 (Acc = 0.6627)
  [Intento  18/ 18] Probando modelo de 186 features... F1 = 0.6556 (Acc = 0.6578)
Mejor intento = 10
-> Sin mejora global en este ciclo. Pasos sin mejora: 3
Model = LightGBM (metricas_logs 1 punto suma) N_feat=186 Accuracy = 0.6673 | Macro F1 = 0.6647 | Macro Precision = 0.6669 | Macro Recall = 0.6673

--- Evaluando reducción desde 186 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 185 features... F1 = 0.6599 (Acc = 0.6618)
  [Intento   2/ 18] Probando modelo de 185 features... F1 = 0.6597 (Acc = 0.6612)
  [Intento   3/ 18] Probando modelo de 185 features... F1 = 0.6603 (Acc = 0.6612)
  [Intento   4/ 18] Probando modelo de 185 features... F1 = 0.6622 (Acc = 0.6639)
  [Intento   5/ 18] Probando modelo de 185 features... F1 = 0.6586 (Acc = 0.6621)
  [Intento   6/ 18] Probando modelo de 185 features... F1 = 0.6623 (Acc = 0.6644)
  [Intento   7/ 18] Probando modelo de 185 features... F1 = 0.6571 (Acc = 0.6589)
  [Intento   8/ 18] Probando modelo de 185 features... F1 = 0.6614 (Acc = 0.6633)
  [Intento   9/ 18] Probando modelo de 185 features... F1 = 0.6623 (Acc = 0.6639)
  [Intento  10/ 18] Probando modelo de 185 features... F1 = 0.6633 (Acc = 0.6656)
  [Intento  11/ 18] Probando modelo de 185 features... F1 = 0.6536 (Acc = 0.6552)
  [Intento  12/ 18] Probando modelo de 185 features... F1 = 0.6602 (Acc = 0.6621)
  [Intento  13/ 18] Probando modelo de 185 features... F1 = 0.6589 (Acc = 0.6610)
  [Intento  14/ 18] Probando modelo de 185 features... F1 = 0.6564 (Acc = 0.6581)
  [Intento  15/ 18] Probando modelo de 185 features... F1 = 0.6578 (Acc = 0.6595)
  [Intento  16/ 18] Probando modelo de 185 features... F1 = 0.6634 (Acc = 0.6659)
  [Intento  17/ 18] Probando modelo de 185 features... F1 = 0.6619 (Acc = 0.6647)
  [Intento  18/ 18] Probando modelo de 185 features... F1 = 0.6614 (Acc = 0.6636)
Mejor intento = 16
-> Sin mejora global en este ciclo. Pasos sin mejora: 4
Model = LightGBM (metricas_logs 1 punto suma) N_feat=185 Accuracy = 0.6659 | Macro F1 = 0.6634 | Macro Precision = 0.6668 | Macro Recall = 0.6659

--- Evaluando reducción desde 185 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 184 features... F1 = 0.6642 (Acc = 0.6668)
  [Intento   2/ 18] Probando modelo de 184 features... F1 = 0.6581 (Acc = 0.6607)
  [Intento   3/ 18] Probando modelo de 184 features... F1 = 0.6597 (Acc = 0.6610)
  [Intento   4/ 18] Probando modelo de 184 features... F1 = 0.6594 (Acc = 0.6612)
  [Intento   5/ 18] Probando modelo de 184 features... F1 = 0.6609 (Acc = 0.6618)
  [Intento   6/ 18] Probando modelo de 184 features... F1 = 0.6454 (Acc = 0.6464)
  [Intento   7/ 18] Probando modelo de 184 features... F1 = 0.6660 (Acc = 0.6676)
Mejor intento = 7
-> ¡Mejora encontrada! Nuevo mejor Macro F1 global: 0.6660 con 184 features.
Model = LightGBM (metricas_logs 1 punto suma) N_feat=184 Accuracy = 0.6676 | Macro F1 = 0.6660 | Macro Precision = 0.6694 | Macro Recall = 0.6676

--- Evaluando reducción desde 184 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 183 features... F1 = 0.6562 (Acc = 0.6583)
  [Intento   2/ 18] Probando modelo de 183 features... F1 = 0.6581 (Acc = 0.6604)
  [Intento   3/ 18] Probando modelo de 183 features... F1 = 0.6562 (Acc = 0.6583)
  [Intento   4/ 18] Probando modelo de 183 features... F1 = 0.6589 (Acc = 0.6612)
  [Intento   5/ 18] Probando modelo de 183 features... F1 = 0.6596 (Acc = 0.6615)
  [Intento   6/ 18] Probando modelo de 183 features... F1 = 0.6571 (Acc = 0.6589)
  [Intento   7/ 18] Probando modelo de 183 features... F1 = 0.6590 (Acc = 0.6607)
  [Intento   8/ 18] Probando modelo de 183 features... F1 = 0.6567 (Acc = 0.6578)
  [Intento   9/ 18] Probando modelo de 183 features... F1 = 0.6606 (Acc = 0.6630)
  [Intento  10/ 18] Probando modelo de 183 features... F1 = 0.6621 (Acc = 0.6639)
  [Intento  11/ 18] Probando modelo de 183 features... F1 = 0.6625 (Acc = 0.6642)
  [Intento  12/ 18] Probando modelo de 183 features... F1 = 0.6636 (Acc = 0.6659)
  [Intento  13/ 18] Probando modelo de 183 features... F1 = 0.6624 (Acc = 0.6639)
  [Intento  14/ 18] Probando modelo de 183 features... F1 = 0.6615 (Acc = 0.6630)
  [Intento  15/ 18] Probando modelo de 183 features... F1 = 0.6602 (Acc = 0.6615)
  [Intento  16/ 18] Probando modelo de 183 features... F1 = 0.6573 (Acc = 0.6589)
  [Intento  17/ 18] Probando modelo de 183 features... F1 = 0.6612 (Acc = 0.6639)
  [Intento  18/ 18] Probando modelo de 183 features... F1 = 0.6585 (Acc = 0.6610)
Mejor intento = 12
-> Sin mejora global en este ciclo. Pasos sin mejora: 1
Model = LightGBM (metricas_logs 1 punto suma) N_feat=183 Accuracy = 0.6659 | Macro F1 = 0.6636 | Macro Precision = 0.6672 | Macro Recall = 0.6659

--- Evaluando reducción desde 183 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 182 features... F1 = 0.6613 (Acc = 0.6630)
  [Intento   2/ 18] Probando modelo de 182 features... F1 = 0.6563 (Acc = 0.6583)
  [Intento   3/ 18] Probando modelo de 182 features... F1 = 0.6599 (Acc = 0.6624)
  [Intento   4/ 18] Probando modelo de 182 features... F1 = 0.6621 (Acc = 0.6633)
  [Intento   5/ 18] Probando modelo de 182 features... F1 = 0.6561 (Acc = 0.6583)
  [Intento   6/ 18] Probando modelo de 182 features... F1 = 0.6590 (Acc = 0.6604)
  [Intento   7/ 18] Probando modelo de 182 features... F1 = 0.6596 (Acc = 0.6612)
  [Intento   8/ 18] Probando modelo de 182 features... F1 = 0.6608 (Acc = 0.6627)
  [Intento   9/ 18] Probando modelo de 182 features... F1 = 0.6611 (Acc = 0.6624)
  [Intento  10/ 18] Probando modelo de 182 features... F1 = 0.6553 (Acc = 0.6572)
  [Intento  11/ 18] Probando modelo de 182 features... F1 = 0.6568 (Acc = 0.6586)
  [Intento  12/ 18] Probando modelo de 182 features... F1 = 0.6610 (Acc = 0.6627)
  [Intento  13/ 18] Probando modelo de 182 features... F1 = 0.6611 (Acc = 0.6627)
  [Intento  14/ 18] Probando modelo de 182 features... F1 = 0.6583 (Acc = 0.6601)
  [Intento  15/ 18] Probando modelo de 182 features... F1 = 0.6584 (Acc = 0.6598)
  [Intento  16/ 18] Probando modelo de 182 features... F1 = 0.6589 (Acc = 0.6610)
  [Intento  17/ 18] Probando modelo de 182 features... F1 = 0.6591 (Acc = 0.6610)
  [Intento  18/ 18] Probando modelo de 182 features... F1 = 0.6594 (Acc = 0.6615)
Mejor intento = 4
-> Sin mejora global en este ciclo. Pasos sin mejora: 2
Model = LightGBM (metricas_logs 1 punto suma) N_feat=182 Accuracy = 0.6633 | Macro F1 = 0.6621 | Macro Precision = 0.6657 | Macro Recall = 0.6633

--- Evaluando reducción desde 182 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 181 features... F1 = 0.6587 (Acc = 0.6612)
  [Intento   2/ 18] Probando modelo de 181 features... F1 = 0.6599 (Acc = 0.6615)
  [Intento   3/ 18] Probando modelo de 181 features... F1 = 0.6554 (Acc = 0.6578)
  [Intento   4/ 18] Probando modelo de 181 features... F1 = 0.6611 (Acc = 0.6630)
  [Intento   5/ 18] Probando modelo de 181 features... F1 = 0.6381 (Acc = 0.6403)
  [Intento   6/ 18] Probando modelo de 181 features... F1 = 0.6588 (Acc = 0.6610)
  [Intento   7/ 18] Probando modelo de 181 features... F1 = 0.6609 (Acc = 0.6630)
  [Intento   8/ 18] Probando modelo de 181 features... F1 = 0.6591 (Acc = 0.6621)
  [Intento   9/ 18] Probando modelo de 181 features... F1 = 0.6654 (Acc = 0.6671)
  [Intento  10/ 18] Probando modelo de 181 features... F1 = 0.6615 (Acc = 0.6630)
  [Intento  11/ 18] Probando modelo de 181 features... F1 = 0.6551 (Acc = 0.6566)
  [Intento  12/ 18] Probando modelo de 181 features... F1 = 0.6573 (Acc = 0.6586)
  [Intento  13/ 18] Probando modelo de 181 features... F1 = 0.6586 (Acc = 0.6610)
  [Intento  14/ 18] Probando modelo de 181 features... F1 = 0.6602 (Acc = 0.6615)
  [Intento  15/ 18] Probando modelo de 181 features... F1 = 0.6652 (Acc = 0.6668)
  [Intento  16/ 18] Probando modelo de 181 features... F1 = 0.6628 (Acc = 0.6650)
  [Intento  17/ 18] Probando modelo de 181 features... F1 = 0.6635 (Acc = 0.6656)
  [Intento  18/ 18] Probando modelo de 181 features... F1 = 0.6524 (Acc = 0.6540)
Mejor intento = 9
-> Sin mejora global en este ciclo. Pasos sin mejora: 3
Model = LightGBM (metricas_logs 1 punto suma) N_feat=181 Accuracy = 0.6671 | Macro F1 = 0.6654 | Macro Precision = 0.6691 | Macro Recall = 0.6671

--- Evaluando reducción desde 181 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 180 features... F1 = 0.6641 (Acc = 0.6653)
  [Intento   2/ 18] Probando modelo de 180 features... F1 = 0.6394 (Acc = 0.6395)
  [Intento   3/ 18] Probando modelo de 180 features... F1 = 0.6580 (Acc = 0.6595)
  [Intento   4/ 18] Probando modelo de 180 features... F1 = 0.6633 (Acc = 0.6644)
  [Intento   5/ 18] Probando modelo de 180 features... F1 = 0.6553 (Acc = 0.6572)
  [Intento   6/ 18] Probando modelo de 180 features... F1 = 0.6577 (Acc = 0.6592)
  [Intento   7/ 18] Probando modelo de 180 features... F1 = 0.6615 (Acc = 0.6636)
  [Intento   8/ 18] Probando modelo de 180 features... F1 = 0.6563 (Acc = 0.6586)
  [Intento   9/ 18] Probando modelo de 180 features... F1 = 0.6650 (Acc = 0.6662)
  [Intento  10/ 18] Probando modelo de 180 features... F1 = 0.6570 (Acc = 0.6595)
  [Intento  11/ 18] Probando modelo de 180 features... F1 = 0.6629 (Acc = 0.6642)
  [Intento  12/ 18] Probando modelo de 180 features... F1 = 0.6541 (Acc = 0.6554)
  [Intento  13/ 18] Probando modelo de 180 features... F1 = 0.6616 (Acc = 0.6639)
  [Intento  14/ 18] Probando modelo de 180 features... F1 = 0.6563 (Acc = 0.6581)
  [Intento  15/ 18] Probando modelo de 180 features... F1 = 0.6615 (Acc = 0.6636)
  [Intento  16/ 18] Probando modelo de 180 features... F1 = 0.6634 (Acc = 0.6650)
  [Intento  17/ 18] Probando modelo de 180 features... F1 = 0.6589 (Acc = 0.6607)
  [Intento  18/ 18] Probando modelo de 180 features... F1 = 0.6588 (Acc = 0.6607)
Mejor intento = 9
-> Sin mejora global en este ciclo. Pasos sin mejora: 4
Model = LightGBM (metricas_logs 1 punto suma) N_feat=180 Accuracy = 0.6662 | Macro F1 = 0.6650 | Macro Precision = 0.6694 | Macro Recall = 0.6662

--- Evaluando reducción desde 180 features. Probando las 18 peores candidatas ---
  [Intento   1/ 18] Probando modelo de 179 features... F1 = 0.6554 (Acc = 0.6578)
  [Intento   2/ 18] Probando modelo de 179 features... F1 = 0.6509 (Acc = 0.6528)

In [63]:
mejor_paquete_modelo['model_name']

'LightGBM (metricas_logs 1 punto suma) N_feat=173'

In [64]:
joblib.dump(mejor_paquete_modelo, f"{FOLDER_SALIDA}/models/{mejor_paquete_modelo['model_name']}.joblib")

['result/models/LightGBM (metricas_logs 1 punto suma) N_feat=173.joblib']

### <span style="color:#2ca02c">4.7. Red neuronal</span>

#### <span style="color:#2ca02c">4.7.1. Calculo de la Red neuronal</span>

In [ ]:
scaler = StandardScaler()
X_anomalia_train_std = scaler.fit_transform(X_anomalia_train)
X_anomalia_test_std = scaler.transform(X_anomalia_test)


X_train_real, X_val_real, Y_train_real, Y_val_real = train_test_split(
    X_anomalia_train_std, 
    Y_train_encoded, 
    test_size=0.2, 
    random_state=SEED, 
    shuffle=True,
    stratify=Y_train_encoded # Opcional pero muy recomendado para 53 clases (mantiene la proporción de cada clase)
)

In [ ]:
optuna.logging.set_verbosity(optuna.logging.WARNING)

N_trials = 16

# 1. Crear una barra de progreso global basada en el número total de trials
pbar = tqdm(total=N_trials, desc="Optimizando Red Neuronal")

# 2. Callback de verbose para ver el progreso de Optuna en tiempo real
def print_callback(study, trial):
    print(f"Trial {trial.number} finalizado | Mejor Loss actual: {study.best_value:.4f} | Parámetros: {trial.params}")
    pbar.update(1)
    pbar.set_postfix({
        "Mejor_Loss": f"{study.best_value:.4f}",
        "Trial": trial.number
    })

# 3. Función objetivo de Optuna recibiendo el diccionario externo de configuración
def objective(trial, config):
    num_clases = len(lista_label) - 1
    
    # Sugerir parámetros utilizando el diccionario de configuración
    n_layers = trial.suggest_categorical('n_layers', config['n_layers'])
    lr = trial.suggest_categorical('lr', config['lr'])
    batch_size = trial.suggest_categorical('batch_size', config['batch_size'])
    dropout_rate = trial.suggest_categorical('dropout_rate', config['dropout_rate'])
    
    # Construcción dinámica de la arquitectura
    model = Sequential()
    model.add(Input(shape=(X_anomalia_train.shape[1],)))
    
    for i in range(n_layers):
        units = trial.suggest_categorical(f'units_l{i}', config['units'])
        model.add(Dense(units))
        model.add(BatchNormalization())
        model.add(tf.keras.layers.Activation('relu'))
        model.add(Dropout(dropout_rate))
        
    model.add(Dense(num_clases, activation='softmax'))
    
    optimizer = tf.keras.optimizers.Adam(learning_rate=lr)
    
    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    
    callbacks = [
        EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=0),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-5, verbose=0)
    ]
    
    history = model.fit(
        X_train_real,
        Y_train_real,
        validation_data=(X_val_real, Y_val_real),
        epochs=50,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=0
    )
    
    val_loss = min(history.history['val_loss'])
    trial.set_user_attr('val_loss', val_loss)
    return val_loss

# 4. Definición externa de los hiperparámetros a probar para la Red Neuronal
params_grid_nn = {
    'n_layers': [1, 2, 3],
    'units': [64, 128, 256, 512],
    'lr': [1e-4, 5e-4, 1e-3, 5e-3],
    'batch_size': [32, 64, 128, 256],
    'dropout_rate': [0.1, 0.2, 0.3, 0.5]
}

# 5. Crear el estudio
study_nn = optuna.create_study(direction='minimize')

# 6. Enlazar la función con los parámetros mediante partial
objective_func_nn = partial(objective, config=params_grid_nn)

# 7. Ejecutar pasando el callback de verbose
print("=== INICIANDO OPTIMIZACIÓN DE RED NEURONAL CON OPTUNA ===")
try:
    study_nn.optimize(objective_func_nn, n_trials=N_trials, callbacks=[print_callback], n_jobs=1)
finally:
    pbar.close()

# 8. Resultados finales y entrenamiento del modelo definitivo
print("\n=== MEJOR COMBINACIÓN ENCONTRADA (RED NEURONAL) ===")
print(study_nn.best_params)
print(f"Mejor Val Loss: {study_nn.best_value:.4f}")

In [ ]:

# Reconstruir el modelo final con los mejores parámetros óptimos
best_params_nn = study_nn.best_params
num_clases = len(lista_label) - 1

best_model = Sequential()
best_model.add(Input(shape=(X_anomalia_train.shape[1],)))

for i in range(best_params_nn['n_layers']):
    units = best_params_nn[f'units_l{i}']
    best_model.add(Dense(units))
    best_model.add(BatchNormalization())
    best_model.add(tf.keras.layers.Activation('relu'))
    best_model.add(Dropout(best_params_nn['dropout_rate']))

best_model.add(Dense(num_clases, activation='softmax'))

best_optimizer = tf.keras.optimizers.Adam(learning_rate=best_params_nn['lr'])

best_model.compile(
    optimizer=best_optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_final = [
    EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-5, verbose=1)
]

history_final = best_model.fit(
    X_train_real,
    Y_train_real,
    validation_data=(X_val_real, Y_val_real),
    epochs=300,
    batch_size=best_params_nn['batch_size'],
    callbacks=callbacks_final,
    verbose=1
)

In [ ]:
# 1. Generar predicciones de probabilidad y convertir a índices de clase
Y_pred_prob = best_model.predict(X_anomalia_test_std)  # O X_anomalia_test según el nombre de tu conjunto de test
Y_pred_encoded = np.argmax(Y_pred_prob, axis=1)

# 2. Revertir el codificador de etiquetas para obtener los nombres originales (texto)
Y_pred_tipos = encoder_etiquetas.inverse_transform(Y_pred_encoded)

# 3. Evaluar el rendimiento del clasificador usando las etiquetas reales de test
print("=== REPORTE DE CLASIFICACIÓN DE TIPOS DE ANOMALÍA (Red Neuronal) ===")
print(classification_report(Y_test_etiquetas, Y_pred_tipos))

In [ ]:


model_name='Clasificador_Red_Neuronal'
paquete_NN = {
    'model': clf_anomalias_opt,                
    'metrics_list': lista_metric_name_vector,  # La lista con los nombres de las características
    'model_name': model_name, # Un identificador o nombre descriptivo
    'encoder_etiquetas':encoder_etiquetas,
    'scaler':scaler,
    'parametros': best_params_nn         
}



joblib.dump(paquete_NN, f'{FOLDER_SALIDA}/models/{model_name}.joblib')

#### <span style="color:#2ca02c">4.7.2. XGBoost usando penultima capa de la red neuronal</span>

In [ ]:
# En Keras 3, cogemos la salida de la penúltima capa y la conectamos directamente a la entrada de la primera capa
capa_latente_output = best_model.layers[-2].output

# Creamos el extractor usando la capa de entrada explícita del modelo
extractor_latente = Model(inputs=best_model.layers[0].input, outputs=capa_latente_output)

# Extraer el espacio latente para tus conjuntos de datos
X_train_latent = extractor_latente.predict(X_train_real)
X_val_latent = extractor_latente.predict(X_val_real)
#X_test_latent = extractor_latente.predict(X_test_real)  # O X_anomalia_test según el nombre que uses

print("¡Espacio latente extraído con éxito! Dimensiones:", X_train_latent.shape)

In [ ]:
print("¡Espacio latente extraído con éxito! Dimensiones:", X_train_latent.shape)

In [ ]:
encoder_etiquetas.inverse_transform(Y_val_real).shape

In [ ]:
# 1. Inicializar el clasificador XGBoost multiclase
xgb_clf = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=SEED,
    n_jobs=-1
)

# 2. Entrenar XGBoost usando exclusivamente el espacio latente de la red neuronal
print("=== ENTRENANDO XGBOOST CON EL ESPACIO LATENTE ===")
xgb_clf.fit(X_train_latent, Y_train_real)

# 3. Predecir sobre el conjunto de validación o test latente
Y_pred_xgb_encoded = xgb_clf.predict(X_val_latent)

# 4. Revertir a texto original usando tu encoder de etiquetas
Y_pred_xgb_tipos = encoder_etiquetas.inverse_transform(Y_pred_xgb_encoded)
Y_val_real_etiquetas= encoder_etiquetas.inverse_transform(Y_val_real)


# 5. Evaluar resultados
print("\n=== REPORTE DE CLASIFICACIÓN (XGBoost + Espacio Latente) ===")
print(classification_report(Y_val_real_etiquetas, Y_pred_xgb_tipos))

#### <span style="color:#2ca02c">4.7.3. XGBoost usando metricas originales  + penultima capa de la red neuronal</span>

In [ ]:
# 1. Crear el dataset híbrido (Concatenando características crudas + espacio latente de 256 neuronas)
# Asegúrate de usar los mismos conjuntos (aquí usamos train y test para la evaluación final)
X_train_hybrid = np.hstack([X_train_real, X_train_latent])
X_test_hybrid  = np.hstack([X_val_real, X_val_latent]) # O X_val_hybrid si estabas usando validación

# 2. Inicializar el clasificador XGBoost multiclase
xgb_clf = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=SEED,
    n_jobs=-1
)

# 3. Entrenar XGBoost con el modelo híbrido
print("=== ENTRENANDO XGBOOST HÍBRIDO (Originales + Espacio Latente) ===")
xgb_clf.fit(X_train_hybrid, Y_train_real)

# 4. Predecir sobre el conjunto de test híbrido
Y_pred_xgb_encoded = xgb_clf.predict(X_test_hybrid)

# 5. Revertir a texto original usando el encoder de etiquetas
Y_pred_xgb_tipos = encoder_etiquetas.inverse_transform(Y_pred_xgb_encoded)

# 6. Evaluar resultados frente a las etiquetas reales de test
print("\n=== REPORTE DE CLASIFICACIÓN (XGBoost Híbrido) ===")
print(classification_report(Y_val_real_etiquetas, Y_pred_xgb_tipos))

## <span style="color:#2ca02c">4.8. Clustering no supervisado</span>

### <span style="color:#2ca02c">4.8.1. K-MEANS</span>

In [ ]:
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 1. Reducir la dimensionalidad de tus datos a 2D para poder graficarlos
pca = PCA(n_components=2, random_state=SEED)
X_2d = pca.fit_transform(X_anomalia_test) # O puedes usar X_test_enriquecido

# 2. Aplicar un clustering (por ejemplo, K-Means con un número razonable de grupos visuales, ej. 5 u 8)
n_clusters_visuales = 50
kmeans = KMeans(n_clusters=n_clusters_visuales, random_state=SEED, n_init=10)
clusters = kmeans.fit_predict(X_2d)

# 3. Preparar el DataFrame para la visualización con Seaborn
import pandas as pd
df_plot = pd.DataFrame({
    'PCA1': X_2d[:, 0],
    'PCA2': X_2d[:, 1],
    'Cluster': clusters.astype(str)
})

# 4. Graficar
plt.figure(figsize=(10, 8))
sns.scatterplot(
    data=df_plot, 
    x='PCA1', 
    y='PCA2', 
    hue='Cluster', 
    palette='tab10', 
    alpha=0.6, 
    s=30
)
plt.title(f"Visualización de Clusters en Espacio Reducido (PCA) - {n_clusters_visuales} Grupos")
plt.xlabel("Componente Principal 1")
plt.ylabel("Componente Principal 2")
plt.legend(title="Cluster")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# 1. Definir un rango razonable de número de clusters a probar (por ejemplo, de 1 a 20)
# Como tienes 53 clases pero quizás se agrupan en menos familias, 20 es un buen tope para buscar el codo.
inercia = []
rango_k = range(1, 21)

for k in rango_k:
    kmeans = KMeans(n_clusters=k, random_state=SEED, n_init=10)
    kmeans.fit(X_anomalia_test) # O puedes usar X_anomalia_train
    inercia.append(kmeans.inertia_)

# 2. Graficar la curva del codo
plt.figure(figsize=(10, 6))
plt.plot(rango_k, inercia, marker='o', linestyle='-', color='b', linewidth=2, markersize=6)
plt.title("Método del Codo para Determinar el Número Óptimo de Clusters", fontsize=14)
plt.xlabel("Número de Clusters (k)", fontsize=12)
plt.ylabel("Inercia (Suma de distancias cuadráticas)", fontsize=12)
plt.xticks(rango_k)
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

# Rango de clusters a evaluar (por ejemplo, de 2 a 20)
rango_k = range(2, 21)
valores_silueta = []

for k in rango_k:
    kmeans = KMeans(n_clusters=k, random_state=SEED, n_init=10)
    clusters = kmeans.fit_predict(X_anomalia_test)
    
    # Calcular el coeficiente de silueta medio para este k
    score = silhouette_score(X_anomalia_test, clusters)
    valores_silueta.append(score)

# Encontrar el k que maximiza la silueta
k_optimo_silueta = rango_k[valores_silueta.index(max(valores_silueta))]
print(f"Número óptimo de clusters según la Silueta: {k_optimo_silueta}")

# Gráfica opcional para la memoria del TFM
plt.figure(figsize=(9, 5))
plt.plot(rango_k, valores_silueta, marker='s', color='purple', linestyle='-', linewidth=2)
plt.title("Optimización de Clusters por Índice de Silueta")
plt.xlabel("Número de Clusters (k)")
plt.ylabel("Puntuación de Silueta Media")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score
from sklearn.neighbors import NearestNeighbors

# 1. Encontrar automáticamente un valor óptimo de 'eps' usando la gráfica de k-distancias
# k se suele fijar en min_samples - 1 (por ejemplo, si min_samples = 5, k = 4)
min_samples_val = 5
neighbors = NearestNeighbors(n_neighbors=min_samples_val)
neighbors.fit(X_anomalia_test)
distances, _ = neighbors.kneighbors(X_anomalia_test)

# Ordenar las distancias del k-ésimo vecino más cercano de forma ascendente
k_distances = np.sort(distances[:, min_samples_val - 1])

# Visualizar la curva de k-distancias para buscar el "codo" visualmente si se desea
plt.figure(figsize=(9, 5))
plt.plot(k_distances, color='b', linewidth=2)
plt.title("Gráfica de K-Distancias para encontrar el 'eps' óptimo de DBSCAN")
plt.xlabel("Puntos ordenados por distancia")
plt.ylabel(f"Distancia al {min_samples_val}-ésimo vecino más cercano")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# 2. Automatizar una búsqueda rápida de un 'eps' que devuelva un número razonable de clusters válidos
# Probamos un rango de valores para eps basados en los percentiles de las distancias
mejores_clusters = 0
mejor_eps = 0
mejor_silueta = -1
mejor_etiquetas = None

# Probamos con varios umbrales de distancia
rango_eps = np.percentile(k_distances, np.linspace(50, 95, 10))

for eps_val in rango_eps:
    dbscan = DBSCAN(eps=eps_val, min_samples=min_samples_val)
    etiquetas = dbscan.fit_predict(X_anomalia_test)
    
    # Contar cuántos clusters encontró (excluyendo el ruido, que se marca como -1)
    n_clusters_encontrados = len(set(etiquetas)) - (1 if -1 in etiquetas else 0)
    
    # Para calcular la silueta, DBSCAN requiere que haya al menos 2 clusters y que no todo sea ruido (-1)
    if n_clusters_encontrados > 1:
        # Filtramos temporalmente los puntos de ruido (-1) para calcular la silueta de los clusters reales
        mask_no_ruido = etiquetas != -1
        if sum(mask_no_ruido) > n_clusters_encontrados:
            score = silhouette_score(X_anomalia_test[mask_no_ruido], etiquetas[mask_no_ruido])
            
            # Guardamos la mejor combinación según la silueta
            if score > mejor_silueta:
                mejor_silueta = score
                mejor_eps = eps_val
                mejores_clusters = n_clusters_encontrados
                mejor_etiquetas = etiquetas

print(f"\n--- RESULTADOS ÓPTIMOS DE DBSCAN ---")
print(f"Mejor eps encontrado: {mejor_eps:.4f}")
print(f"Número óptimo de clusters descubiertos: {mejores_clusters}")
print(f"Puntuación de Silueta (sin ruido): {mejor_silueta:.4f}")

# Porcentaje de datos clasificados como ruido (etiqueta -1)
if mejor_etiquetas is not None:
    porcentaje_ruido = (sum(mejor_etiquetas == -1) / len(mejor_etiquetas)) * 100
    print(f"Porcentaje de muestras consideradas ruido (-1): {porcentaje_ruido:.2f}%")

### <span style="color:#2ca02c">4.8.2. DBSCAN</span>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.neighbors import NearestNeighbors

# 1. Estandarizar los datos correctamente
# (Asegúrate de usar el scaler ajustado previamente con tus datos de entrenamiento, 
# o instanciar uno nuevo si es un bloque de análisis exploratorio puro)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_anomalia_test)

# 2. Encontrar automáticamente un valor óptimo de 'eps' usando la gráfica de k-distancias
min_samples_val = 5
neighbors = NearestNeighbors(n_neighbors=min_samples_val)
neighbors.fit(X_scaled)
distances, _ = neighbors.kneighbors(X_scaled)

# Ordenar las distancias del k-ésimo vecino más cercano
k_distances = np.sort(distances[:, min_samples_val - 1])

# Visualizar la curva de k-distancias para verificar el "codo" con los datos escalados
plt.figure(figsize=(9, 5))
plt.plot(k_distances, color='b', linewidth=2)
plt.title("Gráfica de K-Distancias (Datos Estandarizados)")
plt.xlabel("Puntos ordenados por distancia")
plt.ylabel(f"Distancia al {min_samples_val}-ésimo vecino más cercano")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# 3. Búsqueda automatizada del mejor 'eps' basada en la silueta y un nivel de ruido razonable
mejores_clusters = 0
mejor_eps = 0
mejor_silueta = -1
mejor_etiquetas = None

# Probamos con varios percentiles del rango de distancias
rango_eps = np.percentile(k_distances, np.linspace(50, 95, 15))

for eps_val in rango_eps:
    dbscan = DBSCAN(eps=eps_val, min_samples=min_samples_val)
    etiquetas = dbscan.fit_predict(X_scaled)
    
    # Contar clusters encontrados (excluyendo el ruido -1)
    n_clusters_encontrados = len(set(etiquetas)) - (1 if -1 in etiquetas else 0)
    
    if n_clusters_encontrados > 1:
        mask_no_ruido = etiquetas != -1
        if sum(mask_no_ruido) > n_clusters_encontrados:
            score = silhouette_score(X_scaled[mask_no_ruido], etiquetas[mask_no_ruido])
            
            if score > mejor_silueta:
                mejor_silueta = score
                mejor_eps = eps_val
                mejores_clusters = n_clusters_encontrados
                mejor_etiquetas = etiquetas

print(f"\n--- RESULTADOS DBSCAN (CON DATOS ESTANDARIZADOS) ---")
print(f"Mejor eps encontrado: {mejor_eps:.4f}")
print(f"Número óptimo de clusters descubiertos: {mejores_clusters}")
print(f"Puntuación de Silueta (sin ruido): {mejor_silueta:.4f}")

if mejor_etiquetas is not None:
    porcentaje_ruido = (sum(mejor_etiquetas == -1) / len(mejor_etiquetas)) * 100
    print(f"Porcentaje de muestras consideradas ruido (-1): {porcentaje_ruido:.2f}%")

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.neighbors import NearestNeighbors
from kneed import KneeLocator

# 1. Estandarizar los datos correctamente
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_anomalia_test)

# 2. Encontrar las k-distancias para el cálculo automático
min_samples_val = 5
neighbors = NearestNeighbors(n_neighbors=min_samples_val)
neighbors.fit(X_scaled)
distances, _ = neighbors.kneighbors(X_scaled)

# Ordenar las distancias del k-ésimo vecino más cercano
k_distances = np.sort(distances[:, min_samples_val - 1])
puntos_x = np.arange(len(k_distances))

# 3. Detectar automáticamente el "codo" en la curva de K-distancias usando KneeLocator
kneedle = KneeLocator(
    puntos_x, 
    k_distances, 
    curve='convex', 
    direction='increasing'
)

eps_optimo = kneedle.elbow_y

# Si por algún motivo el localizador automático no devolviera un valor, usamos un percentil de seguridad
if eps_optimo is None:
    eps_optimo = np.percentile(k_distances, 95)

print(f"--- CÁLCULO AUTOMÁTICO ---")
print(f"Valor de 'eps' óptimo detectado en el codo: {eps_optimo:.4f}")

# 4. Ejecutar DBSCAN con el 'eps' calculado automáticamente
dbscan = DBSCAN(eps=eps_optimo, min_samples=min_samples_val)
etiquetas = dbscan.fit_predict(X_scaled)

# 5. Analizar los resultados obtenidos
n_clusters_encontrados = len(set(etiquetas)) - (1 if -1 in etiquetas else 0)
porcentaje_ruido = (sum(etiquetas == -1) / len(etiquetas)) * 100

print(f"\n--- RESULTADOS FINALES DE DBSCAN ---")
print(f"Número de clusters identificados: {n_clusters_encontrados}")
print(f"Porcentaje de muestras consideradas ruido (-1): {porcentaje_ruido:.2f}%")

if n_clusters_encontrados > 1:
    mask_no_ruido = etiquetas != -1
    if sum(mask_no_ruido) > n_clusters_encontrados:
        score_silueta = silhouette_score(X_scaled[mask_no_ruido], etiquetas[mask_no_ruido])
        print(f"Puntuación de Silueta (sin ruido): {score_silueta:.4f}")

# 6. Mostrar la gráfica señalando el codo detectado
plt.figure(figsize=(9, 5))
plt.plot(puntos_x, k_distances, color='b', linewidth=2, label='K-distancias')
if kneedle.elbow is not None:
    plt.axvline(x=kneedle.elbow, color='r', linestyle='--', label=f'Codo automático (eps={eps_optimo:.2f})')
plt.title("Gráfica de K-Distancias con Codo Automático (DBSCAN)")
plt.xlabel("Puntos ordenados por distancia")
plt.ylabel(f"Distancia al {min_samples_val}-ésimo vecino más cercano")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

In [ ]:
import pandas as pd
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

# 1. Obtener el vector de clasificación (etiquetas predichas por DBSCAN)
# 'etiquetas' es el array que devolvió el modelo DBSCAN (valores de -1 a 7)
vector_clusters = etiquetas

# 2. Crear un DataFrame analítico cruzando los clusters con tus etiquetas reales
df_cruce = pd.DataFrame({
    'Cluster_DBSCAN': vector_clusters,
    'Etiqueta_Real': Y_test_etiquetas  # Asegúrate de que esta variable contenga tus 53 clases reales
})

# 3. Generar la Matriz de Contingencia (Tabla cruzada)
# Filas = Clusters de DBSCAN (incluyendo el -1 como ruido), Columnas = Tus 53 clases reales (o puedes ver una muestra)
matriz_contingencia = pd.crosstab(df_cruce['Cluster_DBSCAN'], df_cruce['Etiqueta_Real'])

print("--- MATRIZ DE CONTINGENCIA (Clusters vs Clases Reales) ---")
print("Dimensiones de la matriz:", matriz_contingencia.shape)
# Mostramos una pequeña porción para visualizarlo cómodamente en consola
print(matriz_contingencia.iloc[:, :]) 

# 4. Calcular métricas de relación / concordancia externa
# (Nota: Omitimos temporalmente el ruido -1 para evaluar qué tan bien agrupados están los puntos válidos)
mask_evaluacion = vector_clusters != -1
if sum(mask_evaluacion) > 0:
    y_real_filtrado = Y_test_etiquetas[mask_evaluacion]
    y_pred_filtrado = vector_clusters[mask_evaluacion]

    ari = adjusted_rand_score(y_real_filtrado, y_pred_filtrado)
    nmi = normalized_mutual_info_score(y_real_filtrado, y_pred_filtrado)

    print(f"\n--- MÉTRICAS DE CONCORDANCIA EXTERNA ---")
    print(f"Adjusted Rand Index (ARI): {ari:.4f}  (0 = azar, 1 = coincidencia perfecta)")
    print(f"Normalized Mutual Information (NMI): {nmi:.4f}  (Mide cuánta información comparten)")

# <span style="color:#2ca02c">5. Revision complementariedad de modelos</span>

In [ ]:
def calcular_potencial_mejora(y_true, y_pred_1, y_pred_2, average='macro'):
    """
    Calcula un valor numérico que indica si un modelo híbrido mejorará 
    el rendimiento de los modelos individuales.
    """
    y_true = np.array(y_true)
    y_pred_1 = np.array(y_pred_1)
    y_pred_2 = np.array(y_pred_2)
    
    # 1. Métricas base de los modelos individuales (ej. Macro F1)
    score_1 = f1_score(y_true, y_pred_1, average=average, zero_division=0)
    score_2 = f1_score(y_true, y_pred_2, average=average, zero_division=0)
    mejor_base = max(score_1, score_2)
    
    # 2. Techo Teórico (Oracle): Simulación perfecta donde elegimos el acierto 
    # de cualquiera de los dos modelos si al menos uno acierta la muestra.
    aciertos_1 = (y_pred_1 == y_true)
    aciertos_2 = (y_pred_2 == y_true)
    acierto_or = aciertos_1 | aciertos_2
    
    # Si simulamos que un hipotético híbrido perfecto rescata todos los aciertos posibles:
    # (Para muestras donde ambos fallan, mantenemos una predicción al azar o del mejor)
    # Una aproximación numérica directa del límite superior (Techo Oracle):
    techo_teorico = np.mean(acierto_or) # (Si usamos accuracy como base de techo)
    
    # 3. CÁLCULO DEL NÚMERO CLAVE: "Margen de Mejora Potencial" (Delta)
    # Mide cuántos puntos porcentuales hay de margen entre el mejor modelo y el límite teórico.
    # (Lo calculamos con el acierto binario general o adaptado al F1)
    acc_1 = accuracy_score(y_true, y_pred_1)
    acc_2 = accuracy_score(y_true, y_pred_2)
    mejor_acc_base = max(acc_1, acc_2)
    
    delta_mejora = techo_teorico - mejor_acc_base
    
    # 4. Tasa de Desacuerdo (Diversidad)
    tasa_desacuerdo = np.mean(aciertos_1 != aciertos_2)
    
    print("=" * 60)
    print("      INDICADOR NUMÉRICO DE POTENCIAL DE MEJORA")
    print("=" * 60)
    print(f"Score (Macro F1) Modelo 1:    {score_1:.4f}")
    print(f"Score (Macro F1) Modelo 2:    {score_2:.4f}")
    print(f"Mejor Modelo Individual:      {mejor_base:.4f}")
    print("-" * 60)
    print(f"Tasa de Desacuerdo (Diversidad): {tasa_desacuerdo * 100:.2f}%")
    print(f"Margen de Mejora Teórico (Delta): +{delta_mejora * 100:.2f}%  <-- NÚMERO CLAVE")
    print("=" * 60)
    
    # Interpretación numérica estricta:
    if delta_mejora > 0.03:  # Más de un 3% de margen teórico
        print("🟢 Veredicto: ALTO POTENCIAL DE MEJORA (> 3% de margen).")
    elif delta_mejora > 0.01: # Entre 1% y 3%
        print("🟡 Veredicto: MEJORA MODERADA O MARGINAL (1% - 3%).")
    else:
        print("🔴 Veredicto: SIN POTENCIAL DE MEJORA (< 1%). Los modelos son redundantes.")
        
    return {
        'mejor_base': mejor_base,
        'techo_teorico': techo_teorico,
        'delta_mejora': delta_mejora,
        'tasa_desacuerdo': tasa_desacuerdo
    }

In [95]:
lista_filenames=[
    'result/models/RandomForest (metricas_logs 3 puntos)(todas las features).joblib',
    'result/models/RandomForest (metricas_logs 3 puntos)   N_feat=63.joblib',
    
    'result/models/RandomForest (metricas_logs 1 punto suma)(todas las features).joblib',
    'result/models/RandomForest (metricas_logs 1 punto suma)   N_feat=78.joblib',
    
    'result/models/XGBoost (metricas_logs 3 puntos)(todas las features).joblib',
    'result/models/XGBoost (metricas_logs 3 puntos)   N_feat=102.joblib',
    
    'result/models/XGBoost (metricas_logs 1 punto suma)(todas las features).joblib',
    'result/models/XGBoost (metricas_logs 1 punto suma)   N_feat=160.joblib',
    
    'result/models/LightGBM (metricas_logs 3 puntos)(todas las features).joblib',
    'result/models/LightGBM (metricas_logs 3 puntos)   N_feat=147.joblib',
    
    'result/models/LightGBM (metricas_logs 1 punto suma)(todas las features).joblib',
    'result/models/LightGBM (metricas_logs 1 punto suma)   N_feat=202.joblib',
    
#     'result/models/RandomForest (metricas_log) N_feat=44.joblib',
#     'result/models/XGBoost con metricas_logs (3 puntos y todas las metricas).joblib',
#     'result/models/XGBoost (metricas_log) N_feat=93.joblib',
#    'result/models/XGBoost con metricas_logs (1 punto 3 intervalos todas las metricas).joblib'
#     'result/models/XGBoost (metricas_log) N_feat=110.joblib'
]

In [96]:
paquete_modelo['resultado']

{'accuracy': 0.6882438316400581,
 'precision': 0.6910796659371462,
 'recall': 0.6882438316400581,
 'f1': 0.6878356873422209}

In [97]:
lista_modelos=[]
for filename in lista_filenames:
    paquete_modelo = joblib.load(filename)
    lista_modelos.append(paquete_modelo)

In [98]:
for paquete_modelo in lista_modelos:
    model_name      = paquete_modelo['model_name']
    accuracy        = paquete_modelo['resultado']['accuracy']
    macro_f1        = paquete_modelo['resultado']['precision']
    macro_precision = paquete_modelo['resultado']['recall']
    macro_recall    = paquete_modelo['resultado']['f1']
    print(f"Model = {model_name:70s} Accuracy = {accuracy:.4f} | Macro F1 = {macro_f1:.4f} | Macro Precision = {macro_precision:.4f} | Macro Recall = {macro_recall:.4f}")

Model = RandomForest (metricas_logs 3 puntos)(todas las features)              Accuracy = 0.6232 | Macro F1 = 0.6255 | Macro Precision = 0.6232 | Macro Recall = 0.6192
Model = RandomForest (metricas_logs 3 puntos)   N_feat=63                      Accuracy = 0.6374 | Macro F1 = 0.6414 | Macro Precision = 0.6374 | Macro Recall = 0.6352
Model = RandomForest (metricas_logs 1 punto suma)(todas las features)          Accuracy = 0.6136 | Macro F1 = 0.6076 | Macro Precision = 0.6136 | Macro Recall = 0.6008

KeyError: 'precision'

In [115]:
paquete_modelo['resultado']

{'accuracy': 0.6275761973875181,
 'macro_f1': 0.6197418658287879,
 'macro_precision': 0.6283339292003264,
 'macro_recall': 0.6275761973875182}

In [ ]:
lista_Y_pred=[]
Y_pred =  predict_modelo(lista_modelos[0],lista_feature_names1_sum,X_test_sum)
lista_Y_pred.append(Y_pred)
Y_pred =  predict_modelo(lista_modelos[1],lista_feature_names1,X_test)
lista_Y_pred.append(Y_pred)
# Y_pred_tipos                                = encoder_etiquetas.inverse_transform(Y_pred)

In [ ]:
calcular_potencial_mejora(Y_test_encoded,lista_Y_pred[0],lista_Y_pred[1])

In [ ]:

from sklearn.linear_model import LogisticRegression

# 1. Obtener las matrices de validación con las features específicas de cada modelo
X_val_sub_1 = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_val, lista_feature_sel=lista_modelos[0]['lista_features'])
X_val_sub_2 = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_val, lista_feature_sel=lista_modelos[1]['lista_features'])

# 2. Generar las probabilidades sobre ESE conjunto de validación (datos no vistos)
probs_val_1 = lista_modelos[0]['model'].predict_proba(X_val_sub_1)
probs_val_2 = lista_modelos[1]['model'].predict_proba(X_val_sub_2)

# 3. Construir las meta-features de entrenamiento para el metamodelo
X_meta_train = np.hstack((probs_val_1, probs_val_2))

# 4. Entrenar el metamodelo
meta_model = LogisticRegression(max_iter=1000,class_weight='balanced')
meta_model.fit(X_meta_train, Y_val_encoded)


X_test_sub_1 = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test, lista_feature_sel=lista_modelos[0]['lista_features'])
X_test_sub_2 = X_matrix_sel_data(X_matrix, lista_feature_names, lista_idx_filas=idx_test, lista_feature_sel=lista_modelos[1]['lista_features'])

probs_test_1 = lista_modelos[0]['model'].predict_proba(X_test_sub_1)
probs_test_2 = lista_modelos[1]['model'].predict_proba(X_test_sub_2)

# 5. Para test (haces lo mismo pero con X_test)
X_meta_test = np.hstack((probs_test_1, probs_test_2))
y_pred_meta = meta_model.predict(X_meta_test)

In [ ]:
Y_pred_tipos                                = encoder_etiquetas.inverse_transform(y_pred_meta)

In [ ]:
print(classification_report(Y_test_etiquetas, Y_pred_tipos))